### ISSUE TITLE
Sign up placeholder text missing in IE

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#100]
Beta tester says the 4 boxes for signing up is blank using IE 9 (no placeholder tex shows up):
http://screencast.com/t/nu9o4xnlVQ

Can we fix this ASAP and maybe make the placeholder text darker gray so they're easier to see?

**Comment by loicginoux** [comment]
I was thinking about these placeholder few days ago and thought we should add labels above the input. a placeholder only is not a good practice and bad user experience anyway.
I will add labels above fields instead. IE9 doesn't support placeholder anyway.

**Comment by loicginoux** [comment]
here is how it wil look: http://awesomescreenshot.com/051o2b943
is that ok?

**Comment by loicginoux** [comment]
I also added it to the register page

**Comment by jdaudier** [comment]
I would say left align it and make it black so it's easier to read?

**Comment by loicginoux** [comment]
ok

**Comment by jdaudier** [comment]
"Lost password" can stay gray and be centered though.

**Comment by loicginoux** [comment]
done
