### ISSUE TITLE
Log in bug [IMPORTANT]

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#101]
Beta tester can't log in. Tried resetting the password. Didn't work. Tried creating a new account. Not working either. She is using email: engtutor_mg@yahoo.com

She is getting this error: username and/or password is incorrect

**Comment by loicginoux** [comment]
she hasn't confirmed her email so sh can't log in. she needs to click the verification email link

**Comment by loicginoux** [comment]
I attach the new task for that #102

**Comment by jdaudier** [comment]
She said she confirmed her email. She said: It said it couldn't locate my account

**Comment by loicginoux** [comment]
can i or you close this?
