### ISSUE TITLE
when logging in without having confirmed, message should be appropriate

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#102]
message should be something like "email not verified, please click the link in the email we sent"

**Comment by loicginoux** [comment]
the message is "Your account is not confirmed" is that ok?

**Comment by jdaudier** [comment]
How about:

Please check your email to to complete the sign-up process.

Gmail       (links to www.gmail.com)
Hotmail    (links to www.hotmail.com)
Outlook    (links to www.outlook.com)
Yahoo      (links to www.yahoo.com)
iCloud      (links to www.icloud.com)
AOL (really?)        (links to mail.aim.com)

Resend email

**Comment by jdaudier** [comment]
updated the above

**Comment by loicginoux** [comment]
I don't think listing all email site is really helpful, users know how to go to their account quickly. and the list will never be complete anyway.
also "resend email" is actually another feature to implement and test, etc... this would be nice to have but I will need time to do it. can we create an issue for this and put it in a future sprint.
thanks

**Comment by jdaudier** [comment]
I think it saves time to add the list of emails for one click access.  See how FB does it: http://screencast.com/t/T71Xuwq5B

**Comment by loicginoux** [comment]
Ok so When they finished registration AND when they login without having confirmed, I wil put a link to their email provider for them to check their email.
note that if the email provider is unknown, the message will not appear.
Can you give me the exact message when the provider is known and when it's not? thanks

**Comment by jdaudier** [comment]
How about this:

Provider is known:
Check your email at [insert email] to complete the sign-up process.  [Go to your email] 

Button like FB http://screencast.com/t/T71Xuwq5B]

Provider is unknown:
Check your email at [insert email] to complete the sign-up process.

**Comment by loicginoux** [comment]
ok

**Comment by loicginoux** [comment]
this has been implemented ad can be tested.

**Comment by jdaudier** [comment]
Minor suggestions: http://screencast.com/t/I6gVVKyCR

**Comment by jdaudier** [comment]
I just tried to log in without confirming my account and got this: http://screencast.com/t/NZQl8c21V

Should the message be the same as the previous screen minus the "Thanks for signing up" part?

Like this:
Provider is known:
Check your email at [insert email] to complete the sign-up process. 
[Go to your email]

Provider is unknown:
Check your email at [insert email] to complete the sign-up process.

**Comment by loicginoux** [comment]
which color do you want for the button? http://bootswatch.com/journal/#buttons
I will change the message as well when trying to login without confirming

**Comment by jdaudier** [comment]
How about orange large button?

**Comment by jdaudier** [comment]
Can you share a screenshot and then I can close this?

**Comment by loicginoux** [comment]
is that ok? http://awesomescreenshot.com/0f1po8zc1

**Comment by jdaudier** [comment]
Looks good.  How about when you try to login without confirming?  I think you were going to change that message too.

**Comment by loicginoux** [comment]
ah yes, this is the screenshot: 
http://awesomescreenshot.com/096posn80
because registration is done by a plugin "authlogic", I couldn't make the message dynamic. I hope it's fine like that.
