### ISSUE TITLE
Follow user link in emails

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#105]
When a user is followed by another user and receive a notification email, you can follow that person back.  When you click "follow user" link, you're taken to a page where you can follow the user manually.  Is there a way to follow the user straight from the link in the email?

**Comment by loicginoux** [comment]
Yes I can change that. But all new issue/feature/request/bug goes to future sprints (6,7 or future). I change the label of this issue

**Comment by jdaudier** [comment]
Can you confirm and close this? I don't have a way to check this.

**Comment by loicginoux** [comment]
I will delete our friendship and follow you again, you should receive the message where you will be able to follow me directly and test that this is correct.

**Comment by loicginoux** [comment]
You should have received the email when I followed you... let me know if everything is ok

**Comment by jdaudier** [comment]
Works!
