### ISSUE TITLE
Profile photo enahancement

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#106]
Here's a suggestion from Chrissy: I signed up using my PC. I uploaded a picture of myself, but I'm not sure whether or not if my picture is actually there - it is a faint color. When I'm in FoodRubix I don't see my profile pic so it's difficult to know whether other people can successfully see my pic or not.

My solution: http://screencast.com/t/CL9rDbodmcpj

**Comment by loicginoux** [comment]
I agree

**Comment by loicginoux** [comment]
I did it locally this way:
- I always put on top the user's picture: brown bag if no picture or uploaded picture (remember that we will have less brown bag picture now that all facebook registered users will have automatically their fb pic added)
- if you are on a user's diary, their photo will show up.
- In settings the photo stays with an opacity filter, do you want to remove that?

**Comment by jdaudier** [comment]
Settings: I think no opacity filter.  That's how most site does it, right?

**Comment by jdaudier** [comment]
I noticed this feature is in place but I think you were planning to remove the opacity filter under Settings, correct?

**Comment by loicginoux** [comment]
I removed the opacity
