### ISSUE TITLE
"invalid date" popup 

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#11]
in week view, when hovering a data point

**Comment by loicginoux** [comment]
I can't replicate the issue.
Could you try again? if it's still here can you tell me your login details, and the photo for which it's happening (by giving me the day for example)

**Comment by jdaudier** [comment]
Username: joannedaudier
Pwd: foodrubix

Week view
Click on any data point in the chart, popup says "invalid date"

**Comment by loicginoux** [comment]
ahhhh ok I was hovering the data point image... I realised it was on the graphic. I also have this issue on mine. To help debugging, just try to describe as much as possible how and where you get the issue. It will help me solve it quicker :)

**Comment by loicginoux** [comment]
ok I changed it to "Sunday: 1450 calories"
