### ISSUE TITLE
Upload button not working in Safari  5.1.7 

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#111]
Beta tester Annick says:

I am unable to upload picture using my Mac. 
When I click on the upload button nothing append (never prompt for a file).
I am using Safari Version 5.1.7 (6534.57.2)
To upgrade Safari to 6.0.2 I will need to upgrade my OS to Mountain Lion 10.8 who I am not convince is stable enough yet.
I don't known when you are planning to release your apps, but I suggest that you but a webpage with the browser compatibility.

**Comment by jdaudier** [comment]
Can we fix this ASAP?

**Comment by loicginoux** [comment]
yes I am trying to find a way to install this version...

**Comment by loicginoux** [comment]
Ok I manage to downgrade my version of safari to 5.1.7 and I manage to open the upload box.
I can't replicate the issue...

**Comment by jdaudier** [comment]
ok thanks... i will see if i can try too

**Comment by loicginoux** [comment]
this is fixed.

**Comment by jdaudier** [comment]
Annick (tremblaa) says:
I try unsuccessfully to upload a picture with Safari 5.1.7 last night.
I then upgrade my computer to OS 10.8 and Safari 6.0.2 and was able to upload a picture.

**Comment by jdaudier** [comment]
Closed since this is related to a later bug: https://github.com/loicginoux/joanne_project/issues/160
