### ISSUE TITLE
Log in bug 

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#115]
Login error reported by Justin:

Date: Fri, 30 Nov 2012 23:36:56 +0100

Currently not able to sign in. Signed up via email on Safari I believe. It was not recognizing my login info

I also confirmed the email link.  I actually get an email sent to me telling me I must be starving :) hahaha. But can't log in for some reason

Email used is either:
justin06@email.com
justintmiller06@gmail.com

**Comment by loicginoux** [comment]
Sorry the heroku logs at the moments don't save datas that far ago in the past (at the moment I am talking the first entry in logs is from 6 hours ago)... I installed a plugin in heroku that should be able to monitor logs better and keep them for a longer time...
