### ISSUE TITLE
Rotate images

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#121]
Lots of beta testers have their photos sent in sideways

Maybe I can swap this with something in sprint 6.

Might be able to use: www.filepicker.io

**Comment by loicginoux** [comment]
this is a big feature and Changing the system by filepicker.io even more work. I wouldn't advise you to add that to sprint 6 but if you really want it, you will need to remove one or more... let me know which one you would remove.
I found the code to do it with our techno (paperclip + s3).
http://railsmonkey.net/2009/10/simple-image-rotation-with-paperclip-and-amazon-s3/

**Comment by jdaudier** [comment]
Do you think it's worth to switch to filepicker.io?  If not, we don't have to.  Does filepicker let you rotate photos?

**Comment by jdaudier** [comment]
Is there a way to prevent pictures from being sideways or will the user have to correct them each time themselves? http://screencast.com/t/rngHv76jhe7w

**Comment by loicginoux** [comment]
I can't guess where is the bottom of the picture but we could have a way for the user to rotate their images.
see example:
http://jsfiddle.net/7TyJG/

**Comment by jdaudier** [comment]
I guess if we end up using www.filepicker.io, this might allow for rotation too.

**Comment by loicginoux** [comment]
yes it could be an option. I am just listing advantages/disadvantages of using it. Just to see if it's worth it or not.
advantages:
- cleaner
- a lot more features for uploading and editing files

disadvantages:
- more work: be sure that it can do everything we need, integrate it nicely, rewrite all upload and edit photos  functionalities
- need to check if we can change the look of it to integrate it nicely in our app.
- at one point, if the app grows we will have to pay it...(https://www.filepicker.io/pricing/)

I am ok to swap to filepicker if you are willing to

**Comment by jdaudier** [comment]
I am going to send out a survey to the first round of beta testers.  I guess I can ask them if they would like to be able to upload photos from FB, Instagram, and Gmail.  The advantage would be that we won't have to build a mobile app since they can take photos with Intagram and use those images if they'd like.  But I guess that's an extra step, take photo and upload to FB / Instagram, upload photo from FB / Instagram to FoodRubix.

**Comment by loicginoux** [comment]
I have found a feature on the image library I use that can auto detect if the image is sideway or not, apparently this  info is added on metadata of the image. this option I added is live but didn't take time to test uploading photos with my phone... Hoepfully this is enough to make this feature... we will see

**Comment by loicginoux** [comment]
This seems to work automatically on testing instance.
I tries uploading from my phone 3  photos taken with the phone in 3 different positions and I had the photo correctly displayed in the site.
you can try on testing instance by sending photos to pic@devfoodrubix.mailgun.org

**Comment by jdaudier** [comment]
Should we push it to the live site and see if it works there?

**Comment by loicginoux** [comment]
it's already there :)
