### ISSUE TITLE
Trouble sending photos in by phone

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#125]
Beta tester Vicky (vixydish) says:

I sent two emails today to upload pics of food (a muffin) that I'm eating today and they still haven't showed up on the site.  Is there a delay?

I will forward you the email she sent.

**Comment by jdaudier** [comment]
Vicky found another bug:
Not sure if it helps, but I tried to use the "Upload" button on the website itself beforehand, and it just kept on going forever, so I closed the window.  It never uploaded the pics directly from the website either.

5 min later:
The upload button now works.  I'll upload the rest now.

**Comment by jdaudier** [comment]
We should still figure out this bug even though she uploaded the photos manually.

**Comment by loicginoux** [comment]
can you forward me the email please? I will see if I can find that in logs.
Thanks

**Comment by jdaudier** [comment]
I think I sent the email 3 days ago with the muffin photos from vicky.  Is that what you wanted?
