### ISSUE TITLE
Food Feed

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#128]
Beta tester Vicky's idea:

What would be cool is to get a daily or weekly email summary of what the folks I'm following are eating.  Right now, I have to go to their pages individually to see what they're eating.

It's like those LinkedIn weekly email updates that I get (or even those Twitter weekly update emails).

**Comment by loicginoux** [comment]
Yes, and/or having a feed page, where you see what all your friends have been eating recently. I think this is quite useful too.

**Comment by jdaudier** [comment]
Feed page inspiration: http://posts.foodia.com

**Comment by loicginoux** [comment]
I would prefer to add this feature in a feed page rather that in another email (or make it optional in settings)

**Comment by jdaudier** [comment]
In the survey, a lot of people said they wanted to switch between current view and feed view.
http://screencast.com/t/IIktFvR8ZK0w

So my thought is since the right side of the Following page is blank, let's add a feed column there and make it endless scroll like Pinterest?  What do you think?

**Comment by loicginoux** [comment]
ok with me. In the following page is ok.

**Comment by loicginoux** [comment]
In the feeds, do you want to be able to like? comment? see other's comments? (like in facebook)
I would say yet to all.

**Comment by jdaudier** [comment]
Yes, just like FB would be ideal.

**Comment by loicginoux** [comment]
current state: http://awesomescreenshot.com/07bv8nuea

**Comment by jdaudier** [comment]
Can we try putting a CSS border on the images like this?
![css](https://f.cloud.github.com/assets/1666031/113041/544ce2fe-6b38-11e2-99fb-4a1c6b2221de.png)

**Comment by jdaudier** [comment]
Can we change "Feed" to "What everyone else is eating"

Can we remove the period from "People that inspire you"

**Comment by loicginoux** [comment]
now in testing site, let me know if it's ok

**Comment by jdaudier** [comment]
My suggestion is to make the Username and description in orange so they stand out more.  What do you think?
![2013-01-31_0756](https://f.cloud.github.com/assets/1666031/115027/494a7902-6bbf-11e2-939b-6004141418b9.png)

**Comment by loicginoux** [comment]
I agree with the username but I am not sure about the description...
screenshot: http://awesomescreenshot.com/097vgpv02

**Comment by loicginoux** [comment]
also, I put at the bottom a "show more" button like in team rubix page. This is the quickest way but it could be nicer with an infinite scroll as this is a feed page, what do you think? do you want me to make it?

**Comment by jdaudier** [comment]
I like infinite scroll idea.

OK - no orange for the description, but we can make it in this font style and maybe a bit larger font size to try?  Can you show me what that might look like?

![font](https://f.cloud.github.com/assets/1666031/117132/913115ec-6c22-11e2-959d-4c0297a744e4.png)

**Comment by loicginoux** [comment]
this? http://awesomescreenshot.com/0b5vkjhb7

**Comment by jdaudier** [comment]
looks nice!

**Comment by loicginoux** [comment]
infinite scrolling is in testing site now

**Comment by jdaudier** [comment]
Looks nice! Today I was thinking it would be nice to have a GLOBAL feed that shows what everyone is eating in case the user is not following anyone (and have it show up as default).

Maybe we can do a toggle button?

Option A: What people I'm following / everyone else is eating
Toggle on: people I'm following / everyone

Option B: To the right of "What everyone else is eating", add toggles: Following | Everyone

**Comment by loicginoux** [comment]
I would say option B.
but then does it make sense to have it under "following"?

**Comment by jdaudier** [comment]
One idea is to change "Following" header to "Feed"

**Comment by jdaudier** [comment]
The awards ribbons are not showing up in the Feed view.

**Comment by jdaudier** [comment]
Will my photos show up on the feed even though i'm hidden from leaderboard?

I think I'm supposed to be hidden but I see this.
![me](https://f.cloud.github.com/assets/1666031/128331/e15c8a24-6fb5-11e2-8389-144be71477f0.png)

**Comment by loicginoux** [comment]
Now that this is live every new stuff is either a bug or a new feature, so I would prefer to create a new issue for these. I prefer to do it this way if you don't mind. I created the bug for the ribbon not displayed in feed page #262.
For your photo in leaderboard, this is not a problem, it's appearing only for you and even if you show more, you won't be displayed.
your photos will be shown on feed if people starts following you. When we wil have all people feed, your photos will also show up

**Comment by loicginoux** [comment]
new feed page is in testing site now, new features are:
- ribbons on photo
- toggle for everyone
- fixed top navigation bar
- following page renamed to "feed"

Now if you go to the admin panel and edit a user you will see 2 new checkboxes:
- the first one is be automatically added to users as their first friend (by default this is false and you will be the only one to have this checked)
- the second one is to be hidden from the leaderboard, default to false, this will be checked for your account and my account in the live site. in the testing site "lginoux" is the user who has these two checkboxes checked.

Wating for feedback before deploying in live...

**Comment by jdaudier** [comment]
1) Is the font size for "My Diary" and "Feed" the same?  Somehow "My Diary" looks bigger but maybe it's an optical illusion?

2) Change toggle label from "Friends" to "Following"

3) Move "Everyone" to be the right toggle

4) Can the award ribbons be moved closer to the corner so it blocks less of the image?

5) Change "What people I'm following is eating" to "What people I'm following are eating"

**Comment by jdaudier** [comment]
Can we add in infinite scroll for "People that inspire you" box while we're at it?

**Comment by jdaudier** [comment]
2 questions:

1) So I will be  auto added as a new user's first friend and my meal photos will show up in their "Following" and "Everyone" feed?

3) Default setting is "Everyone" and if user choose "Following", it will stay that way the future times they log in, correct?

**Comment by jdaudier** [comment]
For the admin changes, I don't see it on the current admin site. Is it on the staging admin site?

**Comment by loicginoux** [comment]
1) yes to everything
2) yes again

changes are in the admin panel of the staging site

**Comment by loicginoux** [comment]
Hi Joanne, I made all changes requested except the infinite scrolling for friends because I don't think it is gonna work technically.

**Comment by jdaudier** [comment]
Looks great. Let's go live.

1) Is the font size for "My Diary" and "Feed" the same? Somehow "My Diary" looks bigger but maybe it's an optical illusion?

**Comment by jdaudier** [comment]
Just a reminder...under Feed page, to add "Co-Founder" next to your name and my name since we have no points. Can other users see you under Feed page, right column?

![2013-03-20_0114](https://f.cloud.github.com/assets/1666031/279739/8639c5d6-9138-11e2-81d8-eebaf113245c.png)
