### ISSUE TITLE
Comment enhancement

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#129]
When another user comments on my photo and I comment back, they should get an email notification and not me (like FB).

**Comment by jdaudier** [comment]
Going to move this to sprint 6 and remove matching users to sprint 7

**Comment by loicginoux** [comment]
ok

**Comment by loicginoux** [comment]
So what you want here is all users except the one commenting that have commented on a photo previously should receive an email when someone else has commented after?

**Comment by jdaudier** [comment]
Right - is that how Facebook does it?

**Comment by jdaudier** [comment]
This will be a good feature to work on next I think once Annick's upload in Safari bug is fixed.

**Comment by loicginoux** [comment]
ok

**Comment by loicginoux** [comment]
I will check if I can upload with Safari

**Comment by loicginoux** [comment]
Have you read my comment here?
https://github.com/loicginoux/joanne_project/issues/161#issuecomment-11350554

You should think about it. maybe it's better to not spend time to send emails... but implement right now the notifications feature. what do you think?

**Comment by loicginoux** [comment]
Ok, this is done, so this is how it should work:
- photo owner is always notified when someone comment his photo (except when he comment his own photo)
- previous commenters of a photo (except photo owner) are also notified by a new comment.

**Comment by jdaudier** [comment]
I will try this out with a few beta testers and let you know.
