### ISSUE TITLE
Photo upload time error

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#131]
kspillma reported @ 10:45 PM:

Bug report: It is having trouble correcting the time of day of food
I tried 3 times on one and then gave up.
I am trying to put my margarita pizza to noon.
First it was on the wrong day (probably my fault), then it ended up at 2:40 something am.
I'm using firefox.

emailing directly from my phone isn't working
I am using the same email address and putting the number in the subject.

**Comment by loicginoux** [comment]
This should be the problem about the timezone and should normally be fixed.
Do they still have issue with the mobile uploading?

**Comment by loicginoux** [comment]
duplicate of #156. closing this one. If the user still can't send photos by phone, can you create another issue. Thanks
