### ISSUE TITLE
Upload button bigger

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#134]
Since upload button is so important, maybe it should be more noticeable and bigger.

**Comment by jdaudier** [comment]
Should we make the upload button orange so that it stands out?

**Comment by loicginoux** [comment]
I agree, we can try orange

**Comment by jdaudier** [comment]
I think this Upload button should be orange too: http://screencast.com/t/N6F7gCBbbz

**Comment by jdaudier** [comment]
Do you think we can make the Upload button on diary page

And this one orange by Jan 1 when the new batch of tester starts?

http://screencast.com/t/N6F7gCBbbz

**Comment by loicginoux** [comment]
I need to finish the leadeboard before deploying changes to live site. buttons will be orange.

**Comment by loicginoux** [comment]
can we actually close this one?
