### ISSUE TITLE
Tutorial overlay for upload button

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#136]
Just like how we tell users about Settings page with the tutorial overlay, should we add one that shows up first that points to the upload button?  Then proceeds to the Settings overlay.

**Comment by loicginoux** [comment]
You mean, when they first login we show them throw boxes how to use the app?

**Comment by jdaudier** [comment]
Correct - right now we point them to the Settings.  Maybe we can point to Upload and then Settings.  I put this as sprint 7.

**Comment by jdaudier** [comment]
Inspiration: http://screencast.com/t/i4cyzrNLWO

**Comment by jdaudier** [comment]
Inspiration: http://cdn4.tympanus.net/codrops/wp-content/uploads/2013/01/IMG_0015.jpg?84cd58

Popup text: Why not upload your first photo now? You can also send in photos by phone to pic@foodrubix.mailgun.org with calories (just the number) as the subject line.

**Comment by jdaudier** [comment]
Closed since I added the text to the actual Upload form: https://github.com/loicginoux/joanne_project/issues/174
