### ISSUE TITLE
LIKE button bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#137]
Chrissy reported:

On your diary page, I noticed your lunch on Monday (chicken salad: http://www.foodrubix.com/data_points/603). T picture had a thumb down pic. 

I don't think I've clicked 'Like' on that pic before. Anyway I clicked the thumb down pic and now thumbs up again. I think it thinks I've clicked 'like' and is giving me the option to click 'unlike'.

Joanne says: I got 2 emails saying I liked the same photo even though I didn't click LIKE>

**Comment by loicginoux** [comment]
duplicate with #159. I close this one
