### ISSUE TITLE
Photos disappearing

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#141]
All of my food photos disappeared from Sunday, 12/2 when I uploaded a new pic for today.  

Other beta testers such as vixydish and kspillma experienced the same thing.

**Comment by loicginoux** [comment]
Can you tell me a bit more? do you know which photo in particular? can you find it in the admin panel?

**Comment by jdaudier** [comment]
if you take a look at my photos from Sunday, they're all gone for somereason

**Comment by loicginoux** [comment]
this is a duplicate of #157. I close this one
