### ISSUE TITLE
Calorie summary in daily email

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#143]
we should add an area where it totals up the daily calories for yesterday in the daily email.

how hard is this to do?

**Comment by loicginoux** [comment]
not too complicated, We just need to see where it should fit in the email

**Comment by jdaudier** [comment]
http://screencast.com/t/693I56rDoT

can I move this to sprint 6 since i moved matching users to sprint 7?

**Comment by loicginoux** [comment]
ok

**Comment by jdaudier** [comment]
I wonder if it's hard to have this text added to the emails for people who've set up a daily calorie goal.

For people that were below their calorie goal:
You stayed within your daily calorie limit of <   > calories.  Way to go!

For people that went over their calorie goal:
You went over your daily calorie goal of <    > calories.  Don't be sad.  Try again tomorrow!

**Comment by loicginoux** [comment]
I changed it to:
http://awesomescreenshot.com/003pivj18

I changed the daily email to receive it at 2am (so now a task is running every hour to find if a user has his current time at 2am). Becasue I had to change the heroku scheduler, you might not receive a daily email tonight. 
Sorry for the inconvenience.

**Comment by jdaudier** [comment]
Looks good.  Do you think we should make the gray a tiny bit darker so it's easier to read?

**Comment by loicginoux** [comment]
let's see the one from tonight, maybe in the actual email it's easy to read... if not I will change it.

**Comment by jdaudier** [comment]
Can we make the gray this color? #434343

For these text: 
This is what you ate yesterday

Total calories for the day: 1550 cal

You went over your daily calorie goal of 1400 calories. Don't be sad. Try again tomorrow!

**Comment by jdaudier** [comment]
So if user didn't set a daily calorie goal, they won't see the last line, correct?

**Comment by loicginoux** [comment]
yes
