### ISSUE TITLE
User box sizing bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#145]
When I visit another user's diary and jump back to the FOLLOWING page, the boxes around each user go from small to normal size.  Can you see it from the video here? http://screencast.com/t/kFpYpgV6I6ph

**Comment by loicginoux** [comment]
ok, if I understand, it's because the user's photo is not loaded yet. when the phot is loaded it displays correctly, no?

**Comment by jdaudier** [comment]
oh yea... closed
