### ISSUE TITLE
Copy photo feature

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#148]
Easy way to copy photos from a previous day by pressing ctrl + drag

Do you think this should be in sprint 6 or 7?

**Comment by loicginoux** [comment]
It should go in sprint 7. normally new features for sprints are defined at the beginning of the sprint. So when we start, new features can't be added. Maybe we could do smaller sprints, for you to be able to change the features priority between sprints.

**Comment by jdaudier** [comment]
ok - i removed matching user feature to sprint 7.  let me know if we can move this to sprint 6

**Comment by jdaudier** [comment]
now that pairing user is sprint 7, can this be sprint 6?

**Comment by loicginoux** [comment]
no sorry

**Comment by jdaudier** [comment]
no problem

**Comment by loicginoux** [comment]
I think this is a useful one, seeing how photos are repeating for different days. It shouldn't be too hard to implement. The only thing is find how to add it to the UI. ctrl+drag is a shortcut, we should have a more clearer way to do it... like in view box, having a "duplicate" button or something like this

**Comment by jdaudier** [comment]
Let's do the Ctrl + drag shortcut first since most users are sending photos by phone.  And later on in a future sprint, we can add the 2 other regular ways.

Do you think it should Ctrl or Cmd for Macs?

**Comment by loicginoux** [comment]
I would say cmd + drag for Mac. 
And how would you let the user know that this shortcut is available?

**Comment by jdaudier** [comment]
I will create an Intercom pop-up that shows up when user goes to the site... maybe on their 2nd or 3rd use.

**Comment by loicginoux** [comment]
this is now in testing.
FYI:
-  I removed all awards, comments and liked on the copied photo
- It keeps the number of calories
- the uploaded time is not the same as the duplicated item but depends on where you drop the duplicate item, lt follows the same rules as when moving a photo around.

**Comment by jdaudier** [comment]
Nice!  Just tested it and seemed to work ok in staging site.

**Comment by jdaudier** [comment]
So cmd + drag for Mac user and ctrl + drag for PC?

**Comment by loicginoux** [comment]
yes

**Comment by jdaudier** [comment]
ok let me know when you are ready for the beta testers to test this

**Comment by loicginoux** [comment]
ok, I will let you know when I deploy it

**Comment by jdaudier** [comment]
Should we deploy this before the new cohort starts on Feb 1?

**Comment by loicginoux** [comment]
I need to finish the feed page before deploying, and I need to test everything on testing site before deploying. I will try but can't be sure I will manage to finish everything.

**Comment by jdaudier** [comment]
Ok no rush. I rather have less bugs after we deploy. I'm getting quite a few new beta testers for this round since I had a food blogger post it on social media for me.  I didn't share the URL, just my email for them to contact me.
