### ISSUE TITLE
Order of photo is wrong in Firefox

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#150]
Photo order is wrong in Firefox and 2 additional photos were added to today that were not from today.

Order and photos seems ok in Chrome.

Can we start testing in both Chrome, Firefox, and Safari?

**Comment by jdaudier** [comment]
Vicky reported:

I think I figured out that the bugs I saw are browser-related.  Check out the attached screenshots.  Notice that different images highlighted are placed under different days?  Also, notice that the subway sandwich I ate on Tuesday is completely missing from the Chrome image?  Looks like some food pictures I posted from Sunday, 12/2 (the first day) are still missing as well.  

https://dl.dropbox.com/u/125982/food_rubix_chrome.jpg
https://dl.dropbox.com/u/125982/food_rubix_firefox.jpg

**Comment by loicginoux** [comment]
I have the same thing in both browser. What that might happened is that:
- either she took it at different moment and the bugs I corrected have changed things around.
- she edited these photo (from what I can see in logs) and the time has changed at this moment.

**Comment by jdaudier** [comment]
Just making a note that when I view my entries in Firefox and Chrome, it's different.  And that's why I'm getting 2 extra photos in my daily email since the 2 extra photos are showing up in Firefox.

**Comment by loicginoux** [comment]
Hi, do you still see 2 different things in different browsers? I can't replicate that...
