### ISSUE TITLE
Add Terms of Use and Privacy Policy Pages

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#152]
We should probably add Terms of Use and Privacy Policy to the bottom of homepage in light gray text and small font.  http://screencast.com/t/K5duODyxJaEV

Text sent via email.

**Comment by jdaudier** [comment]
reference: http://blog.upcounsel.com/legal-actions-every-app-developer-should-take-right-now/

**Comment by loicginoux** [comment]
I agree. this should be quick

**Comment by jdaudier** [comment]
Can we make this change?  http://screencast.com/t/HxDrvTYPaVmn

**Comment by loicginoux** [comment]
do you mean changing "Terms of services" by just "Terms"?

**Comment by jdaudier** [comment]
yes
