### ISSUE TITLE
Photos from a different day showing up in my daily email

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#153]
These 2 photos are from a previous day and they're showing up in my recap email today.  Any idea what is going on here?

http://screencast.com/t/2OEHDiLOs0U

**Comment by loicginoux** [comment]
I think this is due to the am/pm bug... I just pushed the app with the fix for the bug. I will continue to test to see if this is still doing it.

**Comment by loicginoux** [comment]
Hi Joanne,
So on this one, this is what's happening. We send the email at 10am UTC (for you it makes it 2am).
the query to get the photos is from (now - 24hours) to now.
the problem with that query is:
- in your timezone, you will receive photos from 2am yesterday to 2am today
- in my timezone (UTC) I will receive photos from 10 am yesterday to 10 am today

I now changed the query to be from yesterday at midnight to today at midnight in the current timezone so:
-  in your timezone, you will receive the mail at 2am with photos from 12am yesterday to 12am today.
-  in my timezone, I will receive the mail at 10am with photos from 12am yesterday to 12am today.

The only issue that I can see now is that people in australia for example: at 10am UTC, it is 9pm their. So they will receive the daily email from yesterday at 9pm... not amazing.

The only solution I can imagine that wouldn't be too costly (in terms of process and performance). would be to send daily emails not every 24hours but every 6 hours. Every 6 hours, we check that the time for all users, if the current time is between 12am and 6am, then we send the daily recap email to these users.
running this task every 6 hours will ensure that all users receive the yesterday recap email between midnight and 6am.

What do you think? should I implement what I described last or should I leave it like this for now.

**Comment by loicginoux** [comment]
or we can run it every hour, and send email only to people that have 2am as their current time...

**Comment by jdaudier** [comment]
Which option do you suggest? Running every hour or every 6 hours?  Which one is easier to implement (less chances of bugs)?

**Comment by loicginoux** [comment]
I changed it to run every hour. This is already implemented so you should receive it at 2am tonight. Everyone should receive it at 2am as well depending on their timezone.
