### ISSUE TITLE
Time bug still

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#156]
Annick (tremblaa) sayas:

Le 2012-12-08 à 14:58, Annick Tremblay annick_tremblay@videotron.ca a écrit :

I send an email today at 12:32 but it was labeled as 5:32 PM on the web site.

I did another test, I upload a picture from the web using the default time 2:43PM and after the save
it was 7:43PM. I did not correct the time so you can see. 

Maybe you have a problem, you are saving in Greenwich time instead of eastern time (-5) ?

**Comment by loicginoux** [comment]
Hi, are users still experiencing this issue?

**Comment by jdaudier** [comment]
I will ask her

**Comment by jdaudier** [comment]
She said: I have this screen, half english and half french. It is still not working.

https://dl.dropbox.com/u/125982/AnnickMacBug.tiff

**Comment by loicginoux** [comment]
I think she has her computer in french, that's why she has this button in french... I can't manipulate this text, it depends on the computer language settings.
What does she mean by not working? she can't upload? she has the wrong time when she upload  or when she edit the photo?

**Comment by jdaudier** [comment]
I'll find out.

**Comment by jdaudier** [comment]
JPG file works for her.
