### ISSUE TITLE
Double emails when someone LIKED my photo

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#159]
Sometimes I get 2 of the same emails when people LIKE my photo.  Is it because she clicked LIKE and then UNLIKE, then LIKE again?

http://screencast.com/t/OWyLNtiO

Also, the images seems cropped.  Is that a new thing you changed recently? http://screencast.com/t/Vrp86y2X

**Comment by loicginoux** [comment]
There were an issue with the like button. you could like twice a photo. I fixed that.
Note that if a person LIKE and then UNLIKE, then LIKE again, you will be notified twice. this is not a bug.
images have alwyas been cropped by the system to have a square size.
