### ISSUE TITLE
Upload progress bar stuck

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#160]
tremblaa reported tonight:

I try to upload a picture from my MAC but were unable to upload. I had the Uploading button
for more than 5 minutes and had to use the cancel button.  I have a Mac OS 10.8 and Safari 6.0.2.

**Comment by loicginoux** [comment]
I can upload in both Safari 5.8 and 6.0.2
does she see the upload button like this:
http://awesomescreenshot.com/087pox396
or like this:
http://awesomescreenshot.com/0a3poxfb1

What can be happening:
For all browsers I use the button from the second screenshot, the button is nicer and constant between different browsers except that it doesn't work with Safari (for a reason that I can develop but it will be a bit long and more technical). Anyway, what I did recently is changing only for Safari, the button that everyone has to the file input from screenshot one.

So what I can imagine is that she has still the button from screenshot 2, and I imagine that if she clear her cache for Safari, the new button should appear (screenshot 1)

how to clear her cache in Safari: https://discussions.apple.com/thread/4448839?start=0&tstart=0

**Comment by jdaudier** [comment]
Ok - Sent this message to her and will let you know what she says.

**Comment by jdaudier** [comment]
So which version of button will everyone else see?  Version 1 or 2?

**Comment by loicginoux** [comment]
everyone should see 2 except users using Safari.

**Comment by loicginoux** [comment]
what's the state on this one?

**Comment by jdaudier** [comment]
I'm waiting for Annick Trembla to get back to me on this.  Stay tuned...
