### ISSUE TITLE
LIKE email bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#161]
Vicky reported:

I got email that says Chrissy liked my meal: http://screencast.com/t/3tFgAIb2KM

But when I click on it, it goes to a sushi picture with no likes.

http://www.foodrubix.com/data_points/1036

**Comment by loicginoux** [comment]
I don't think this is a bug... from the log, I can see that she liked the photo and then delete the like object. 
So I guess she liked it and then unclick the like button. this delete the like for the photo but will still send the email.
possible solution for this:
- not sending email for likes and comments, but create a notification (like Facebook). this notification will be visible in the app only. If a user unlike or delete a comment, we could then delete also the notification attached.

This solution will avoid to be notified if the object of the notification has been deleted.

Notifications could be for:
- new comment on your photo
- new like on your photo
- someone else commented on a photo you commented previously
- someone started following you

And I would remove the emails for new comment and new like...
What do you think?

**Comment by jdaudier** [comment]
I prefer having the emails because it brings people back to the site.  It's an engagement strategy.  Although I think it would be good to have the notifications still in a future sprint. 

Maybe we should add an option to turn off the emails on LIKES and comments under Settings > Emails once the notification is in place in the future?

**Comment by loicginoux** [comment]
ok. I will implement the emails for comments for now.
