### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#163]
I got comments from beta testers that they want a more scientific way to calculate points for Leaderboard.   Do you think this is something we can do for sprint 6, so that the current beta testers can get accurate points instead of me guessing.  I was thinking that the Leaderboard can basically be the "TEAM RUBIX" page where the users are listed in Leaderboard format with users with highest points at the top.

Here are my thoughts about calculating points.  What do you think?

Breakfast photo = 1 pt. 
Lunch photo = 1 pt.
Dinner photo = 1 pt. (the most each user can get per day is 3 points for all 3 photos)
Liking someone else's photo = 1 pt. / image liked
Following someone = 1 pt. / user followed
Commenting on someone else's photo = 3 pts. / image commented
Setting daily calorie goal = 5 pts.
Adding a profile photo = 5 pts.
Enabling social sharing on Facebook = 10 pts.

Bug? - Can we take bugs submitted from UserReport to add that in?  Is this technically feasible?
Idea? - Can we take ideas submitted from UserReport to add that in?  Is this technically feasible?

**Comment by loicginoux** [comment]
Ok sounds good for motivating people. If someone want to cheat to be first in leaderboard, you realize it's quite easy? you can comment/like all photos or follow everyone, etc... I imagine people are not here to cheat but just to let you know. 
Now questions:
- Why do you divide breakfast, lunch and dinner photos if they all have 1 point? 
- What happens if you upload more than 3 photos? do you get 3 points (maximum) or do you get 1 point/photo uploaded?
- If we use the "team rubix" page, do you want to display users the same way (with their points underneath the name, and sorted by points)?
- Also in this page, what order should we use? would you still keep the order: "not followed" people first and then "followed" people? or all mixed up but ordered by points?
- would you display somewhere the way we calculate points or not? if yes, were would it go?
- would you display for each user, the details of their point calculation? if yes, were would it go?
- Do you get points if you like/comment your own photos?

Sorry I don't understand the last 2 lines about UserReport. Do you want me to check the UserReport page for bugs and ideas? I only see the "feedback" tab for that, no?

**Comment by jdaudier** [comment]
1) Why do you divide breakfast, lunch and dinner photos if they all have 1 point?

Not sure what you mean.  Can you clarify?

2) What happens if you upload more than 3 photos? do you get 3 points (maximum) or do you get 1 point/photo uploaded?

I was thinking 3 points max or else people will just post a lot of photos.  I was assuming that each person will have breakfast, lunch, and dinner at the minimum.

3) If we use the "team rubix" page, do you want to display users the same way (with their points underneath the name, and sorted by points)?

I think points should go the right of their name so that it looks like a leaderboard.  See www.skinnyo.com and click "People" as example.
http://screencast.com/t/x31ncwGl4D
http://screencast.com/t/lZEc17aT9z

4) Also in this page, what order should we use? would you still keep the order: "not followed" people first and then "followed" people? or all mixed up but ordered by points?

One option is we can do it like Skinnyo where they list users on the left, leaderboard on the right, and latest memebers on bottom right.  Or we can just make the page a leaderboard completely with all users.  Which one do you think makes sense?

I think if we do a Leaderboard, then we'll have to go by points and mix in "followed" and "not followed".

5) would you display somewhere the way we calculate points or not? if yes, were would it go?

Yes, maybe a sidebar on the Leaderboard page that explains how you get points.  Or a button that links to a JS modal that explains it.

6) would you display for each user, the details of their point calculation? if yes, were would it go?

I would say for the first phase, just the total points without details so that way people don't start calculating themselves and complaining about wrong points being added or something like that.  Thoughts?

7) Do you get points if you like/comment your own photos?

No since we want to get people to engage with other users.

8) Sorry I don't understand the last 2 lines about UserReport. Do you want me to check the UserReport page for bugs and ideas? I only see the "feedback" tab for that, no?

I was wondering if the bugs and ideas that people submit through UserReport can be used to calculate points.  Can we pass the data somehow to our own system for calculating?

**Comment by jdaudier** [comment]
So in my daily email, I have been awarding Smart Choice and Hot Photo Awards, I think that should get added as points.

Smart Choice Award = 3 pts.
Hot Photo Award = 3 pts.

Is there a way for me and you to "award" photos through the site and the photo can have a little award icon?  And that can count towards the Leaderboard?

**Comment by loicginoux** [comment]
1) to simplify points for photos, I will give a point per photo per day with a max limit of 3 points per day.
2) 3 points max per day is ok with me.
3 -4 -5 -6 -7) OK
8) no I can't find anything that allow the content of userreport to be exported automatically.

the smart choice and hot photo awards could be added as a field for a photo. 
**How to award a photo?**
The easiest way I can think is to have a checkbox for each award when editing a photo in the admin panel.
**what happens for a awarded photo?**
if a checkbox for "Smart Choice Award" is selected for a photo, then he user win 3 points and the photo can have a little icon.
**about the icons**
can you get me 2 icons for this awards? maybe the once from the mail are fine...
award icon will appear in all views, "day", "week", and "month" + view photo modal box. basically everywhere we display a photo.

**Comment by loicginoux** [comment]
one question about the awards, I know it's not yet that we have a lot of users but how will you awards photo if you have thousands of users? it won't really be possible to go through all manually and select the awarded photos...

**Comment by jdaudier** [comment]
I will go through and randomly find photos to award.  Probably won't go through all of the users but I'll try to look at different ones each day.

**Comment by jdaudier** [comment]
Regarding #4:
One option is we can do it like Skinnyo where they list users on the left, leaderboard on the right, and latest memebers on bottom right. Or we can just make the page a leaderboard completely with all users. 

Which one do you think makes sense?
See example:
http://screencast.com/t/x31ncwGl4D
http://screencast.com/t/lZEc17aT9z

**Comment by jdaudier** [comment]
Another example for inspiration: http://www.weendy.com/stats/leaders/weekly

**Comment by jdaudier** [comment]
I also want to add in a "Slackerboard" listing all users who have not done anything.  This way I don't have to do it manually by hand.  Maybe the page can be split in half... Leaderboard on left and Slackerboard on the right?

**Comment by jdaudier** [comment]
Updated:

Smart Choice Award = 5 pts.
Hot Photo Award = 3 pts.

**Comment by jdaudier** [comment]
Maybe the left is Leaderboard and right side is Slackerboard.  For the Slackerboard, we'll have to check at midnight which user has posted 0 photo and add their name to the Slackerboard.  Slackerboard is only for people who posted nothing in the last 24 hours.  Thoughts?

**Comment by loicginoux** [comment]
Personnaly I don't like this idea of slackerboard. Leaderboard is good, it pushes people in the right direction. Slackerboard, for me, it doesn't add anything to the app, it's just to point a finger at the "bad" users... not really constructive

**Comment by loicginoux** [comment]
if a photo has the two awards, how do you wan it to be displayed?
solutions can be:
- only one will be displayed (currently implemented like this, I supposed you won't give both awards to a photo)
- or we always display "smart choice" on corner top right and "hot photo" on corner top left, so that both can be displayed if needed.

**Comment by loicginoux** [comment]
Another thought, how will you see your points? because in the page "team rubix" if we display only the leaderboard, only the X first people will be shown with their points.

**Comment by loicginoux** [comment]
screenshot of ribbons from my local app:
http://awesomescreenshot.com/09eq68078
http://awesomescreenshot.com/0d1q68ca8

I also finished the system to count the points automatically. Now I need to rethink the team rubix page. I will deploy changes after that.

If you want I can deploy now before changing the team rubix page. This way, you will already have the leaderboard points in the admin panel, and you will be able to attribute awards to photos.

**Comment by jdaudier** [comment]
OK - no Slackerboard for now then

**Comment by jdaudier** [comment]
Each photo will only have 1 award.  I was thinking the Team Rubix page is now the Leaderboard, so all users or ordered by points.  And we can still the "FOLLOW" buttons along with points, correct? http://screencast.com/t/jUSEKgq2snlt

**Comment by jdaudier** [comment]
It'd be great if you can deploy points in the admin panel first.  Do you have the list of award winners for all the days so far or do you need me to send you a list?

**Comment by jdaudier** [comment]
For the ribbons: Can we go with "Smart Choice" and "Hot Photo" - capitalize the 2nd word?  Thanks!

**Comment by loicginoux** [comment]
ok

**Comment by jdaudier** [comment]
Do you have the list of award winners for all the days so far (from the emails), or do you need me to send you a list?

**Comment by loicginoux** [comment]
Do you want me to add the awards to the photos from the previous days?

**Comment by jdaudier** [comment]
Yes, that'll be great.

**Comment by jdaudier** [comment]
Idea: Maybe we can add the leaderboard automatically in the bottom of daily emails.  Maybe list the top 15 with the name, photos, points, and a follow button?  And a link for "More" which  links to the Team Rubix page?  http://screencast.com/t/aj8GnuWzDCw

**Comment by loicginoux** [comment]
ok, awards added to all photos. Do you want the bottom of the daily email to be like the one you send everyday? (I mean in terms of styling)

**Comment by jdaudier** [comment]
maybe we can make it similar to this but in our colors?
http://www.weendy.com/stats/leaders/weekly
rank, name, points, follow button
and then "More" at the bottom which links to Team Rubix page?

**Comment by loicginoux** [comment]
I am not sure this would be useful to have the leaderboard in the daily email, if it's already in the team rubix page. In my point of view it would put too much emphasis on this point system. Why not leave it only on the team rubix page? this is easy enough to go and check... 
One though: how can you check your own points if you are not in leaderboard?

**Comment by loicginoux** [comment]
this is what I have at the moment on the team rubix page
http://awesomescreenshot.com/0f8qq8y8b
Notes:
- the "show more" will only appear after 10 people, I just put it here for you to see it.
- the list of users is sorted by username
- the leaderboard will also have the "show more" after 15 people.
- the last members will only show the last 5 users created without the "show more" feature.

ideas:
- I think a search input is missing for searching people. It's ok for now but when we will have more people, finding will be hard without a search feature.
- I would add a field for users for "why are you here?" or "a bit more about yourself?"  this would be displayed next to the name in the people list (like http://screencast.com/t/x31ncwGl4D)
- I would also add first name and last name for a user. For me, it feels odd to call people by their username. this would be used for example in the emails, comments and other places where displaying a user by its first name is more appropriate ...

**Comment by jdaudier** [comment]
This company resets their Leaderboard every week: http://www.weendy.com/stats/leaders/weekly

Ours can reset every cohort perhaps (see my email for details).

**Comment by jdaudier** [comment]
Can we make "Latest Members" with capital "M"?

**Comment by jdaudier** [comment]
I like having the Leaderboard in daily emails because the beta testers seems to like that.  They feel like they eat better because it's like a competition.  Maybe above the Leaderboard in the email, it can say: Currently, you have ____ total points.

**Comment by jdaudier** [comment]
To add to my email, this site has 2 types of Leaderboard: All Time and Weekly.  This is another option for us to do All Time and Monthly.

http://content.screencast.com/users/jdaudier1223/folders/Jing/media/9ffe5c3d-04d7-45c9-b9ff-7ba5290bbaed/00000217.png

Notice how they user my own points too after 3 dots:
http://content.screencast.com/users/jdaudier1223/folders/Jing/media/d7939d4b-a322-4b58-b19a-44fde1172b23/00000218.png

And maybe users can see their points on their Settings > Profile page.

Here's how Erli Bird does it:
http://screencast.com/t/MDd473i2wM

**Comment by jdaudier** [comment]
Another Leaderboard for our reference: http://www.hypejar.com/about

**Comment by jdaudier** [comment]
My idea for the Team Rubix page.  Let me know what you think. http://content.screencast.com/users/jdaudier1223/folders/Jing/media/453e442d-5c37-474f-979b-69dffd108cee/00000227.png

**Comment by jdaudier** [comment]
When the modal opens, can we create a TABLE with the following text?

All-Time Leaderboard text:

The all-time leaderboard will be updated daily based on member activity. Ranking is basically a combination on how active you're on the site and how healthy you're eating. Participate in the community and eat healthy, and watch your points go up.

Breakfast photo = 1 pt. 
Lunch photo = 1 pt.
Dinner photo = 1 pt.
Following someone = 1 pt. / user followed
Liking someone else's photo = 1 pt. / image
Someone likes your photo = 2 pts. / like
Commenting on someone else's photo = 3 pts. / image
Someone comments on your photo = 2 pts. / image
Winning a Hot Photo Award = 3 pts. / image
Winning a Smart Choice Award = 5 pts. / image
Setting daily calorie goal = 5 pts.
Adding a profile photo = 5 pts.
Enabling Facebook social sharing = 10 pts.

Monthly Leaderboard text:

The monthly leaderboard will be updated daily based on member activity, and the results will be reset every month. Ranking is basically a combination on how active you're on the site and how healthy you're eating. Participate in the community and eat healthy, and watch your points go up.

Breakfast photo = 1 pt. 
Lunch photo = 1 pt.
Dinner photo = 1 pt.
Following someone = 1 pt. / user followed
Liking someone else's photo = 1 pt. / image
Someone likes your photo = 2 pts. / like
Commenting on someone else's photo = 3 pts. / image
Someone comments on your photo = 2 pts. / image
Winning a Hot Photo Award = 3 pts. / image
Winning a Smart Choice Award = 5 pts. / image
Setting daily calorie goal = 5 pts.
Adding a profile photo = 5 pts.
Enabling Facebook social sharing = 10 pts.

**Comment by jdaudier** [comment]
Note that I added these two new triggers for points:

Someone likes your photo = 2 pts. / like
Someone comments on your photo = 2 pts. / image

**Comment by jdaudier** [comment]
We might want to double check to make sure we're calculating correctly.

I just updated these 2 new triggers...

Someone likes your photo = 2 pts. / like  (For example, if you get more 2 LIKES, then you get 4 pts)
Someone comments on your photo = 2 pts. / image (You can only get 2 pts. max per image even if there are lots of comments back & forth since conversations can start easily.  Do you agree?)

**Comment by loicginoux** [comment]
ok, I got it. Just one question, do you want to reset the monthly points automatically every 1st of the month or do you want to do that task manually? I am asking because I am not sure cohorts will start exactly every first of the month...
How do you prefer to do it?

**Comment by jdaudier** [comment]
Yes, the monthly leaderboard should reset the 1st of the month.  I think that's the easiest way to remember when a cohort will start.

**Comment by loicginoux** [comment]
I just realised something.
If you reset the leaderboard every month. everyone should be at 0 points the 1st of every month, ok?
but that brings an incoherence if people already have a profile pic or have their daily calorie goal set.
So maybe when resetting every month, people won't start at 0 but they will have their monthly points based on:
Setting daily calorie goal = 5 pts.
Adding a profile photo = 5 pts.
Enabling Facebook social sharing = 10 pts.

you see? do you agree?

**Comment by jdaudier** [comment]
Right, so even with the monthly reset, users can still have a baset set of points from these:
Setting daily calorie goal = 5 pts.
Adding a profile photo = 5 pts.
Enabling Facebook social sharing = 10 pts.

How about this one?
Following someone = 1 pt. / user followed

**Comment by loicginoux** [comment]
ok this one as well

**Comment by jdaudier** [comment]
Sounds good.  Do you think the monthly reset can be ready by Jan 1st since I'll be starting with a new batch of beta testers?

**Comment by loicginoux** [comment]
in the app yes. I will see if I can do it in the email as well.

**Comment by loicginoux** [comment]
About the points when you follow. I understood that you win points if a new person follows you, but it seems you are saying the contrary.
So when user A follows user B. who should win points?
For me it seems more fair if only user B win points. if user A also win points, then it will be easy to follow everyone to win points.
your thoughts?

**Comment by loicginoux** [comment]
I have deployed this in the staging instance. This is not completely ready as I am waiting for your response on previous comment and I haven;t implemented the leaderboard in email but, the team rubix page and the point system is in place.

**Comment by jdaudier** [comment]
I think to encourage people to follow other people and create engagement, we can try:

Following someone = 1 pt. / user followed
Someone follows you = 2 pts. / follower

**Comment by jdaudier** [comment]
I will encourage people not to game the system - since they can just follow lots of people and LIKE a lot of photos.

**Comment by jdaudier** [comment]
Do you think we should keep this or is this a point thing that's easy to abuse?  Or we can try it out starting Jan 1 and see how it goes.

Liking someone else's photo = 1 pt. / image

**Comment by loicginoux** [comment]
or we could limit it to max one point per image and per day..

**Comment by jdaudier** [comment]
ok... how about we leave it as is and see if people abuse it: Liking someone else's photo = 1 pt. / image

**Comment by loicginoux** [comment]
ok

**Comment by jdaudier** [comment]
For the Leaderboard, we just need to add this to both tables: Someone follows you = 2 pts. / follower

Can we make the column width of the left column and right column the same?  So kinda like this: 
http://content.screencast.com/users/jdaudier1223/folders/Jing/media/9ffe5c3d-04d7-45c9-b9ff-7ba5290bbaed/00000217.png

If the list gets longer, should we add the 3 dots and your profile?
http://content.screencast.com/users/jdaudier1223/folders/Jing/media/d7939d4b-a322-4b58-b19a-44fde1172b23/00000218.png

**Comment by loicginoux** [comment]
do you prefer like this:
http://awesomescreenshot.com/088r6yz1d
the 3 dots are implemented but the first 15 users are loaded so you will see the dots if you are at position > 16
for the look, it will be like this:
http://awesomescreenshot.com/0d4r6zf09
and when you click show more:
http://awesomescreenshot.com/0ear6zhf4

**Comment by jdaudier** [comment]
Yes, I like this: http://awesomescreenshot.com/088r6yz1d

Can we make the 3 dots orange?

And will the columns be even in height at the bottom once 15 users are loaded?  Meaning, either the All-Time or Monthly Leader have to be longer to line up to the bottom of the Latest Members board (since this can be on the left or stay on the right column).  I understand that once users click "show more", the page will get longer, so it might be uneven then but we can try to start it off even.

**Comment by jdaudier** [comment]
Should we make the points (just the number part) in orange and bold?  Kinda like: http://content.screencast.com/users/jdaudier1223/folders/Jing/media/9ffe5c3d-04d7-45c9-b9ff-7ba5290bbaed/00000217.png

**Comment by jdaudier** [comment]
Oh and we should make the Follow button orange too... right now it's blue

**Comment by jdaudier** [comment]
Another option to make the length even is to add another column to the left of the Latest Members.  Maybe we can do

Most Liked Photos
Inspired by: http://screencast.com/t/h7i3Nxjimay

Let me know what makes sense to you.

**Comment by loicginoux** [comment]
I wouldn't put the most liked photos here. This is the page for the "team". It's not really relevant to put it here.
What we could do is put the all time leaderboard loading 20 users at a time and the monthly leaderboard 10. 
This would equal more or less the left and right panels. But It won;t always be perfect as if the current user is displayed in leaderboard with the 3 dots, the panel will be higher.
With all the small changes you asked, this is more or less how it could look like:
http://awesomescreenshot.com/084r8k58f

**Comment by jdaudier** [comment]
looks good!

**Comment by jdaudier** [comment]
Will this stay in the base points even during the monthly reset unless your follower's account is deleted?  Or should we reset per month and only count your new followers for that month?

Someone follows you = 2 pts. / follower

**Comment by loicginoux** [comment]
I would keep this in the monthly leaderboard. if we reset it, people wouldn't understand why they have 0 "monthly" points even if they already have 30 followers...

**Comment by loicginoux** [comment]
I would keep it during the month reset. If not that will create incoherence as one user can see lot of followees/followers and not have any month points.

**Comment by jdaudier** [comment]
ok - this is part of the base points that carries over month to month

**Comment by jdaudier** [comment]
Looks good.  I just have these minor suggestions: http://screencast.com/t/7lyyyBgIj

I couldn't tell if this is an optical illusion.

**Comment by loicginoux** [comment]
yes there is a difference, I am correcting this.

**Comment by jdaudier** [comment]
Cool.  I noticed that this is fixed.  Looks great now.

**Comment by jdaudier** [comment]
Suggestions: 
http://screencast.com/t/ECl4oHWJK9
http://screencast.com/t/l18oBXL33CCS
http://screencast.com/t/7cKhOFzbjF

**Comment by jdaudier** [comment]
http://screencast.com/t/uVJFLUk9j6rq

**Comment by jdaudier** [comment]
Monthly Leaderboard calculation table, can we add asterisks to these 5?
Following someone*
Someone follows you*
Setting daily calorie goal\* 
Adding a profile photo*
Enabling Facebook social sharing*

Updated 1st sentence of description:
The monthly leaderboard will be updated daily based on member activity, and the results will be reset every month (except for the asterisked actions).

**Comment by jdaudier** [comment]
Do you think we can add this ribbon next to the monthly winner like this?
http://d.pr/i/vTWG

Would it be possible to have a tooltip that pops up when you hover over the badge that says:  Dec 2012 Winner

Here's a SVG of the winning badge: https://dl.dropbox.com/u/125982/Winner%20Ribbon.svg

**Comment by jdaudier** [comment]
Did you put negative points for me so I don't show up on Monthly Leaderboard?  I wasn't sure how one would get negative points.  http://d.pr/i/fHxa

**Comment by loicginoux** [comment]
For your suggestions:
- this is the same orange for points
- I removed you from leaderboards
- I put the unfollow grey
- the following page has now 15 people before "show more" and his twice as small in width.
- the footer is now pushed down in all pages to not stick to the content of the page

**Comment by loicginoux** [comment]
for the ribbon next to the user, I created the issue #197 and will be done in future sprint

**Comment by loicginoux** [comment]
negative points is a bug... I will see if I can find it

**Comment by jdaudier** [comment]
Oh and don't forget this one.  The rest of the changes look good in staging site.

Monthly Leaderboard calculation table, can we add asterisks to these 5?
Following someone*
Someone follows you*
Setting daily calorie goal\* 
Adding a profile photo*
Enabling Facebook social sharing*

Updated 1st sentence of description:
The monthly leaderboard will be updated daily based on member activity, and the results will be reset every month (except for the asterisked actions).

**Comment by jdaudier** [comment]
did you want to remove yourself from both Leaderboards too?

**Comment by loicginoux** [comment]
ok

**Comment by jdaudier** [comment]
Open items:
1) Remove yourself from Leaderboards
2) http://screencast.com/t/9oFjsnNDg

**Comment by loicginoux** [comment]
this will be done on next release, this is already implemented but I just want to finish the IE bug before deploying changes

**Comment by jdaudier** [comment]
Good to go live.  Will you be hidden on the Leaderboards once it's live? The font on the staging site looks a bit different.  I assume that's just for the staging site.
