### ISSUE TITLE
allow tiff file to be uploaded

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#164]

**Comment by jdaudier** [comment]
one other thing... i'm not sure if Tiff images shows up on a browser

**Comment by jdaudier** [comment]
The tiff image upload works now but shows a broken link during the progress bar which might make users think they cannot upload a tiff

http://screencast.com/t/YLzruWsPncQz

**Comment by loicginoux** [comment]
it's because a tiff can't be displayed in the browser. This image we see when uploading is a preview of the file (using HTML5) and this is not possible to fix it. Either for this type of file we don't show any preview, or we remove the possibility to upload tiff file...

**Comment by jdaudier** [comment]
I think we should include tiff and maybe add a note like this?  I'm not sure if I got all the support file formats we allow.

http://screencast.com/t/rQ2bdHZu

**Comment by loicginoux** [comment]
The note is added only if you try uploading a wrong file. I changed it to your message (which has all the format supported) and put it underneath.
so what about the preview for tiff images?

**Comment by jdaudier** [comment]
Will the note be visible before the upload?  I think if it's visible before, then it's ok if the progress bar preview doesn't work for Tiffs since we stated it ahead of time.

**Comment by loicginoux** [comment]
ok, I'll add it before.

**Comment by jdaudier** [comment]
http://screencast.com/t/n0tNUFj9l
