### ISSUE TITLE
Photos not showing up

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#165]
Vicky (vixydish) said: None of my photos are showing up today.  Uploaded via Firefox browser and verified date is today.

**Comment by jdaudier** [comment]
Vicky said: Uploading via Chrome is fine though.  I'm doing that now.

**Comment by jdaudier** [comment]
Were you able to fix this Firefox bug?

**Comment by loicginoux** [comment]
I will have a look today. I was doing the leaderboard yesterday

**Comment by loicginoux** [comment]
I can see photos everyday on her profile and I can upload via firefox. Can she make a screenshot of what's wrong and/or explain me a bit more about the bug?
Thank you.

**Comment by jdaudier** [comment]
Looks like it's fixed now.
