### ISSUE TITLE
LIKE bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#167]
Did Vicky like this image twice?  I got 2 emails from her for the LIKE.

http://www.foodrubix.com/data_points/1321

**Comment by loicginoux** [comment]
I am not sure if it's a bug or not. What I am gonna do to prevent it. before adding a new like I will check that there is not another existing "like"  between the user and the photo before creating it. This should prevent the system to add copies of the same "like" object.
What It will not prevent is the case where a user like, then unlike, then like again. In this case, unliking will delete the first "like" object so the second one will be created. This will send you 2 emails.

**Comment by jdaudier** [comment]
Would it be hard to show who LIKED a image?

**Comment by loicginoux** [comment]
I think it's useful. I will see how to add that.

**Comment by jdaudier** [comment]
I noticed that with FB, when you hover over the word "person" or "people", a tooltip pop-up opens with the names like this: http://screencast.com/t/CVQqhOiCj2

**Comment by loicginoux** [comment]
That's how I want to do it, yes. The only thing is that for now, I won't implement the popup box which shows when there are lot of people who like an image.
