### ISSUE TITLE
add foodrubix twitter account

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#170]
I think we should create an account.
You could use it post whatever related to interesting food links and another cool features would be to automatically add a tweet on this account when you award a photo. Something like:
"congrats to <username> for the award on her photo  <link to public photo view>"

This would surely attract more people in.
what do you think?

**Comment by jdaudier** [comment]
Funny thing I just created an account last night.  www.twitter.com/foodrubix

**Comment by loicginoux** [comment]
:) good one.
And what do you think about the idea to post awarded photos there?

**Comment by jdaudier** [comment]
Yea, we can post award photos there.  And add our twitter handle in the tweet this button: http://us4.campaign-archive2.com/?u=dddad37ee2371428c41dd9031&id=ffa64be531&e=5291068b6c

https://github.com/loicginoux/joanne_project/issues/169
