### ISSUE TITLE
Invite code

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#171]
Can we add an "Invite code" field to the sign-up page? http://www.foodrubix.com/register

I will be creating a landing page to collect emails around the New Year's time (since people usually have losing weight as their New Year's resolution), and I want to limit the next beta testing cohort to 50 people or so.  

We can perhaps create an invite code that each cohort can use.  Thoughts?

**Comment by loicginoux** [comment]
I don't understand the use of the invit code... to limit to 50 people? We could but I won't do that in sprint 6, that would be for next sprint.

**Comment by jdaudier** [comment]
This is related to my email where I was thinking of running the site in cohort style.  I noticed that most health-related challenges do that - have a start and end date.  This way people feel like they're part of a team and give up less easily.

If we run the site cohort-styles, we might want to limit the amount of users per cohort (at least in the beginning in case we run into a lot of bugs).

**Comment by loicginoux** [comment]
ok... I need to investigate how easy is it to create this invitation system. I'll come back to you on this.

**Comment by jdaudier** [comment]
Or we can take a chance and not have a cap
