### ISSUE TITLE
Daily calorie calc added to Settings > Preferences page

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#173]
For this page: http://screencast.com/t/ztsbKJWs

Can we add a Daily Calorie Calculator widget?  I will email you the code since it doesn't show up here.

**Comment by loicginoux** [comment]
ok added locally http://awesomescreenshot.com/022qsou31

**Comment by jdaudier** [comment]
Should the Update button be above the Daily Calorie Calculator?

**Comment by loicginoux** [comment]
maybe... I will try

**Comment by jdaudier** [comment]
This look good.  Just need to move Update button up above the calculator.
