### ISSUE TITLE
Wolfram calories counter on upload popup

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#174]
Can we add a calorie counter to the Upload popup like this?  https://www.dropbox.com/s/x25ypsdblq222ou/new-upload4.png

I had to move the "Cancel" and "Upload" buttons up a tad.  The output of the widget will be 500px w x 400px h.

I got the widget from here.  Check your email for the code.
http://www.wolframalpha.com/widgets/view.jsp?id=562b3ac0ac8023ffe92c962859e02763

Do you want to have this in sprint 6 or 7?

**Comment by jdaudier** [comment]
Updated the mock-up URL: https://www.dropbox.com/s/x25ypsdblq222ou/new-upload4.png

**Comment by jdaudier** [comment]
Can this widget show up even when the user edits a photo? Meaning, if user takes a photo by phone, they can come back to the image and use the calculator to update the calorie count.

**Comment by loicginoux** [comment]
sure

**Comment by jdaudier** [comment]
Note that I updated the mockup with this text:
TIP! You can also send in photos by phone to pic@foodrubix.mailgun.orgwith calories (just the number) as the subject line.

https://www.dropbox.com/s/x25ypsdblq222ou/new-upload4.png

**Comment by jdaudier** [comment]
![new-upload4](https://f.cloud.github.com/assets/1666031/90464/3d5dcdd6-6577-11e2-90ad-c8cc70f3dde0.png)

**Comment by loicginoux** [comment]
I can try to see how it goes but my opinion is that with this inside the popup box, the actual popup box loose his purpose. A popup box is usually to display a bit of text or to fill a small form. With what we would have now, I would just go to another page, and come back when the photo have been uploaded.
thoughts?

**Comment by loicginoux** [comment]
According to wolfram, this is for personal use only. You won't be able to have this for commercial use...

**Comment by jdaudier** [comment]
Then how about if we link to it under the Calories text box? It should open a new window.

Calorie counter  (link to: http://www.wolframalpha.com/widgets/view.jsp?id=bcefea6791129b219e2530d3eb6a112f)

**Comment by jdaudier** [comment]
Here's a better idea on where we can link to http://www.wolframalpha.com/widgets/view.jsp?id=bcefea6791129b219e2530d3eb6a112f

http://screencast.com/t/X6My7x5kL

**Comment by loicginoux** [comment]
I prefer it like that, with just a link to the wolfram website. And should I keep the "TIP" message below? (I would say yes)

**Comment by jdaudier** [comment]
Yes, keep TIPS.  

And add this at the end:  and an optional description in the body of the email.

**Comment by jdaudier** [comment]
Updated:

TIP! You can also send in photos by phone to pic@foodrubix.mailgun.org with calories (just the number) as the subject line and an optional description (in quotes) in the body of the email.

Bold: TIP! 
Bold: calories
Bold: description
Orange: pic@foodrubix.mailgun.org

**Comment by jdaudier** [comment]
For the tip, should we change
"and the description (in quotes)" to "and an optional description (in quotes)" so they know it's optional?

Can we have (help me calculate) in orange so it stands out?

**Comment by loicginoux** [comment]
ok

**Comment by jdaudier** [comment]
Reminder:
For the tip, should we change
"and the description (in quotes)" to "and an optional description (in quotes)" so they know it's optional?

Can we have (help me calculate) in orange so it stands out?

**Comment by loicginoux** [comment]
ok, this is done in testing

**Comment by jdaudier** [comment]
I don't see the changes on staging.  Maybe it wasn't pushed?

**Comment by loicginoux** [comment]
yes sorry it wasn't pushed yet

**Comment by jdaudier** [comment]
ok let me know when.  don't see it yet

**Comment by loicginoux** [comment]
this is in testing now

**Comment by jdaudier** [comment]
looks good
