### ISSUE TITLE
Image doesn't load fully

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#175]
I'm not sure if this is a bug or not but some photos load very slowly and some get stuck, and all I would see is the top white bar.

Here a screen capture: http://content.screencast.com/users/jdaudier1223/folders/Jing/media/bd7f3da5-7a80-4439-8b6f-9d7471e63b0e/00000228.png

Here's a video:
http://screencast.com/t/qoSBj5A1

**Comment by loicginoux** [comment]
Ok, first I should put a loading state when opening a modal box. 
Then, for what I saw on the video, there is no bug, just a server that takes time to get back to you. This is more performance issue that can be improved with the tricks we saw on the article you shared few days/weeks ago about how to improve heroku's free plan.
The problem at the moment is that we run on only one process. if 10 people do a request at the same time, they will be processed one by one, so the last user of the stack will see his request taking a lot more time that the first one.

**Comment by jdaudier** [comment]
Sometimes the box would be stuck like this and not load fully: http://content.screencast.com/users/jdaudier1223/folders/Jing/media/bd7f3da5-7a80-4439-8b6f-9d7471e63b0e/00000228.png

I was pretty sure I was the only one on the site too since it was late.

**Comment by jdaudier** [comment]
OK - I think we need to figure out a way to fix this.  Check out how slow it loads (the last image).  The earlier images load faster since I clicked on them already so it's probably cached.

http://screencast.com/t/LRu0Wina0Fks

**Comment by loicginoux** [comment]
are you still experiencing this?

**Comment by jdaudier** [comment]
Yes, not as often but once in a while.
