### ISSUE TITLE
User session bug?

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#176]
Not sure if this is a bug but Min-ru (http://www.foodrubix.com/voyanimg) reported:

http://screencast.com/t/GZ8fQKcRZ

**Comment by loicginoux** [comment]
does she mean that the browser doesn't remember that she is logged in? would she need a "remember me" option in the login page? normally browsers have this integrated but most of the sites also have this feature in their app.

**Comment by loicginoux** [comment]
currently if you close your browser or computer, then you will have to login next time you come back to the site. this would be "fixed" by putting a "remember me" option on login page

**Comment by jdaudier** [comment]
I will find out what she means.

**Comment by loicginoux** [comment]
any news here?

**Comment by jdaudier** [comment]
She didn't respond, but maybe we can leave this to remind us to add a "remember me" option?

**Comment by jdaudier** [comment]
Another request for this feature today.  Is this hard to implement?

The visitor named the idea:
having to put my name and email every time

Description of the idea:
for example below. if i am already logged in you should know who i am and my email

**Comment by loicginoux** [comment]
this is the "remember me" option... I will see if it's quick to implement

**Comment by loicginoux** [comment]
Ok the "remember me" checkbox will be added on the login page on the next push.
This adds the following feature:
- if checked when logged in, the user is kept logged in unless he clicks "logout". Even if the tab or the browser is closed.

**Comment by loicginoux** [comment]
this is now live
