### ISSUE TITLE
Photo owner

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#178]
I got this email:http://screencast.com/t/zQzvwNKoWN

And clicked to view the image.

It made it look like the image was from my diary.  Is that how it's supposed to be? 
http://screencast.com/t/fW3s7ZuTG

**Comment by loicginoux** [comment]
I didn't think about it actually, because at the beginning it was only for your photos. So you would like to display her profile pic and name, right?

**Comment by jdaudier** [comment]
I guess I never noticed this till today.  Do you think we should change the photos to display the photo owner's profile and name?  Or leave it as is since I'm the one looking at her photo?

**Comment by jdaudier** [comment]
When I clicked on the link, I forgot whose photo that was and I look at different profiles to find out it was Chrissy's.

**Comment by loicginoux** [comment]
I think it should be the profile picture of the photo owner.

**Comment by loicginoux** [comment]
I changed it, that makes more sense.

**Comment by jdaudier** [comment]
cool!  should we close this?  I wasn't sure how I can test this.

**Comment by loicginoux** [comment]
yes, this is done locally but I am confident there will be no bugs on this one. This will be available on the next push to live  site

**Comment by loicginoux** [comment]
or let's put it in testing and when it's live I will give you a url to try and check
