### ISSUE TITLE
Drag and drop to move photos

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#18]
As a user, I want to be able to drag and drop to reorder my images (see https://zapier.com)

**Comment by loicginoux** [comment]
So just to clarify what you want.
- In month view: you will be able to change the day by dropping it in another day of the month. 
  Do you want the ability to drop to a previous or next month? 
  note:This will not affect the time, only the day
- in week view: you will be able to change the day by dropping it in another day of the week. 
  Do you want the ability to drop to a previous or next week?
- in day view: this feature won't be implemented.

Is it how you see it?

**Comment by jdaudier** [comment]
I don't think we need to drop to a previous / next month or week unless it's easy to implement.  What are your thoughts on this?

Do you think we should allow this in day view?  That might be helpful for reordering your meals for the day?

**Comment by loicginoux** [comment]
I would leave this one out for the sprint 4. I would prefer to dedicate the sprint 4 for all "social" features, are you ok to report this to sprint 5?

**Comment by jdaudier** [comment]
Sure

**Comment by loicginoux** [comment]
Is this not working for you?

**Comment by jdaudier** [comment]
Oh this is working for me.  Not sure why I reopened it.  Question: If I move something to today, will it show up in my daily  email?

**Comment by jdaudier** [comment]
Reopened since I have another question: Can we make it so you can reorder as well for the day?  Like moving 2nd picture to be the 1st picture for the day in daily and weekly view?

**Comment by loicginoux** [comment]
If you move a photo to the button "today" it won't do anything.
In a day, pictures are ordered by the time they have been taken. So if you move one above another, what should I do? change the time for this photo or make the edit box appear to change time or something else?

**Comment by jdaudier** [comment]
How are you currently doing it when you move a photo from one day to another?

**Comment by loicginoux** [comment]
I just changethe day, not the time.

**Comment by jdaudier** [comment]
Then does it makes sense to swap the time between the 2 photos when you swap the order?

**Comment by jdaudier** [comment]
Question: If I move something to today, will it show up in my daily email?

**Comment by loicginoux** [comment]
yes

**Comment by jdaudier** [comment]
Is the yes to 
Q1: Then does it makes sense to swap the time between the 2 photos when you swap the order?

or Q2: If I move something to today, will it show up in my daily email?

**Comment by loicginoux** [comment]
sorry,  yes it will show  on your daily email.
Q1: you don't want to swap time. example: you have 4 photos in this order [ph1, ph2, ph3, ph4]. if you move ph4 on top, then you have the new order ph4, ph2, ph3, ph1... ph1 shouldn't pass at the end becasue you moved ph4. What you can do is when moving ph4, get the time of ph1 and remove 1 minute... for me it's a bit hacky, and you loose the meaning of the "time" field for a photo. 
The question is why do you want to move photos around during a day? is it not easier just to edit the time for the photo?

**Comment by jdaudier** [comment]
Should I the beta tester what they think about this?  To me, since you can move photos to a different day, it seems half finished not to be able to move the order in a given day.

**Comment by loicginoux** [comment]
I agree but we need to find a way to do the "same day" change nicely. I propose:
- when you drop an image before another one, you change the time to the next photo minus one minute/one hour or whatever. 
- when you drop the image, the edit box appear to ask you to change the time... (but you may enter a time that will put the photo in another place)
- Or photos don't appear by time order, only the order you make them to appear... (then the time field lost his meaning, and we can remove it from the form )

my favorite (or less worse) would be first idea

**Comment by jdaudier** [comment]
I like the first idea.  And the photo can be one hour earlier or later (depends on the drag) since you typically eat like 3 hours apart.  If the user wants to update the time, they can always do it manually later.  But I think it's nice to have the time change automatically when you drag and drop so that it's convenient to use.

**Comment by loicginoux** [comment]
Ok so this will be working this way:
- if you place it in a position where their is a photo after, then the photo dropped has his time changed to the next photo minus 1h
- if you place it at the end of the pile, it takes the time of the previous photo + 1h
- if their is one photo on the day, and you try moving it, it doesn't change the time

**Comment by jdaudier** [comment]
sounds good

**Comment by jdaudier** [comment]
It seems like you can reorder by day now?  But it added 8 hours to my photo when I loved it below another one.

**Comment by loicginoux** [comment]
Really!!! I don't think it's possible to reoder in the day view as I haven't implemented it yet.

**Comment by loicginoux** [comment]
I finished implementing this.
In month and week view, do you also want to be able to move photos up and down in the same day (like we will do in a day view)?
I also decided that the difference between the next and previous photos when moving will not be +/- 1h like in my previous comment but +/- 1 minute. This is to avoid certain corner cases that we have with one hour like:
case 1:
you have photo 1 (taken at 00:30 AM) and photo 2, if you move photo 2 before photo 1, the date of the photo 2 would become 11:30 pm in previous day and would then disappear from the day view
case 2:
photo 1 at 1pm, photo 2 at 1:30pm, and a photo 3. if you move a photo 3 between photo 1 and 2, then the time will change to 12:30, which will then redisplay the photo 3 before photo 1, something that we don't want.

With 1 minute instead of 1 hour, these problems are still  here but this will occur only at a smaller scale.

**Comment by jdaudier** [comment]
Can you reorder photos in the same day currently?  I couldn't do it.  But I think it would be nice to be able to re-order photos in the day, week, and month view.  Thoughts?

**Comment by loicginoux** [comment]
No currently in the same day you can't reorder. This is done locally only in the day view.
So **locally**, what I have is:
- month view: can move photos from one day to another **without changing uploaded time**.
- week view: same.
- day view: you can move photos up and down in the same day.

My question was, do you also want, in week and month view, to be able to move photos up and down during a day?
The only downside of this would be that, if you start drag and dropping photos you will always loose the time of this photo. It will calculate the new "uploaded time" based on the sibling photo you dropped it in. you understand? is it what you want.
For now I will leave it only in the day view, you will try and let me know if you also want this feature in the month and week view.

**Comment by jdaudier** [comment]
Ok - let me know when you have this pushed so I can try the day view.  I think we should add this feature to week and month view too.

**Comment by jdaudier** [comment]
This is related to https://github.com/loicginoux/joanne_project/issues/148

**Comment by jdaudier** [comment]
Would it be hard to add the copy feature while we're at this?  Ctrl + drag to copy.  https://github.com/loicginoux/joanne_project/issues/148

**Comment by loicginoux** [comment]
I would prefer to finish sprint 6 first. I would include that in sprint 7 and make it first if you want.

**Comment by jdaudier** [comment]
ok

**Comment by jdaudier** [comment]
You know how when you drag to a different day, the background changes to orange so you know something is going on?  Can we do the same when you drag a picture to reorder in the same day?  This way user is aware something is happening.

**Comment by loicginoux** [comment]
ok I will see what I can do

**Comment by jdaudier** [comment]
I have beta testers who would like to be able to reorder in week and month view as well.

**Comment by loicginoux** [comment]
I am not sure to understand.... What we cannot do yet:
- moving from a week to another in week view 
- moving to another month in month view 
- moving to another day in day view 

or maybe you mean moving inside the same day in the week and month view?

**Comment by jdaudier** [comment]
Ability to reorder photos in the same day in week view (right now you can only move to a different day)
Ability to reorder photos in the same day in month view (right now you can only move to a different day)

Like how you can do this but only in day view

**Comment by jdaudier** [comment]
Am I supposed to be able to do this in the staging site yet? 
Ability to reorder photos in the same day in week view (right now you can only move to a different day)
Ability to reorder photos in the same day in month view (right now you can only move to a different day)

**Comment by loicginoux** [comment]
no you can't

**Comment by jdaudier** [comment]
Let me know if you want me to create a new feature and close this one.

**Comment by loicginoux** [comment]
No I will just remove the label "live" and finish it for sprint 6

**Comment by loicginoux** [comment]
Are you happy with this one? can we close it?

**Comment by jdaudier** [comment]
So it looks like we can do this now, correct?  It worked when I tried it.

Ability to reorder photos in the same day in week view 
Ability to reorder photos in the same day in month view

**Comment by loicginoux** [comment]
yes
