### ISSUE TITLE
Coaching intensity during sign up

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#182]
During signup it would be nice to ask the user to specify their coaching intensity.  I found a nice bar toggle that we can use: https://dl.dropbox.com/u/125982/FoodRubix-Images/Coaching-Intensity-Bar.png

I will share the 3 PSD layered files (for low, med, high) with you via dropbox.

**Comment by loicginoux** [comment]
url doesn't work for me

**Comment by jdaudier** [comment]
https://dl.dropbox.com/u/125982/FoodRubix-Images/Coaching-Intensity-Bar.png

**Comment by jdaudier** [comment]
These are the 2 questions I'd like to add during sign-up:

What is your goal in joining this challenge? This way we can support you.

What level of coaching intensity would suit you the best? Low, medium, or high.  (use the PSD files I shared with your through Dropbox - just the toggle - you can add the text directly to the site if that's easier)

And then these 2 input can be added to the Settings page: http://screencast.com/t/RBTXzLIqJ

Notice that I changed "Emails" to "Email Recap" so that people don't think that's where you update your email address.

**Comment by loicginoux** [comment]
Why do we not just add a select box "high", "medium", "low" for the coaching intensity?
Using a progress bar like this is nice for the eye but it doesn't add much and take a lot more time to implement.
What do you think?
It is one of these components that were nice in a desktop application but that have disappeared in web app. I can't remember having seen one of these in a web app, do you?

**Comment by loicginoux** [comment]
a nice example could be something like this  (see "Radio" example)
http://twitter.github.com/bootstrap/javascript.html#buttons
with the text changing underneath for each level

**Comment by jdaudier** [comment]
How about if we just do check boxes to match the other pages like this: http://screencast.com/t/452gmNImZW

**Comment by loicginoux** [comment]
checkboxes implies that you can check more than one option, it's not what you want, no? 
radio boxes are made to choose only one among different options, and because a noraml radio box is a bit boring, the twitter bootstrap example makes it prettier...

**Comment by jdaudier** [comment]
Sure, let's try the bootstrap radio boxes and make them orange?

**Comment by loicginoux** [comment]
ok

**Comment by loicginoux** [comment]
another question, What do you use the coaching level for? is it just for info? for example if I choose High, what will happen?
I am asking this because, if it's just for your information, it is a better practice to add that to settings page and ask to fill it later (in a tooltip for example). You should only only have the minimum fields during registration process for the user to log in and use the app.
for reference: http://blog.hubspot.com/blog/tabid/6307/bid/31517/12-Ways-to-Create-a-User-Friendly-Website-Registration-Process.aspx

**Comment by jdaudier** [comment]
Coaching level is used so the nutrition coach, Justin, and I can comment or give feedback more on people that want a high level of coaching.  I think if we don't ask during sign-up, wouldn't most users just skip it?

**Comment by loicginoux** [comment]
Ok, no problem, I just wanted to let you know on this point.

**Comment by jdaudier** [comment]
Will there be a way to sort users to see the high level coaching users in the admin console?

**Comment by loicginoux** [comment]
not yet, will be on next release

**Comment by jdaudier** [comment]
Here's my suggestion on how to make this page look even better. Can we make the buttons vertical and text on the right?

![Coaching Intensity](https://f.cloud.github.com/assets/1666031/126411/8919f52c-6f5b-11e2-9a00-ca5cdf27f398.png)

**Comment by jdaudier** [comment]
Are users asked about this during signup, or do they set it after they sig up?

**Comment by loicginoux** [comment]
they are asked during sign up as well

**Comment by loicginoux** [comment]
buttons are now vertically aligned in "staging" site. This is only in edit page. On the register page, they remains horizontal (see http://calm-gorge-1213.herokuapp.com/register)
I left it this way in register page as putting them vertically wasn't working with the style of the page.

**Comment by jdaudier** [comment]
Suggestions for Settings page:
1) Move high button to the top
2) Please add comma after "goals": I ate a donut. Remind me about my health goals, and give me a grief.

**Comment by jdaudier** [comment]
Suggestions for Create Account page
![2013-02-07_0726](https://f.cloud.github.com/assets/1666031/135969/025ba250-713c-11e2-8cdf-46c3293a5deb.png)

**Comment by loicginoux** [comment]
about your suggestions for register page:
-  left align: ok
- line of space: ok
- darke-color: ok
- sign-up: this is happening because you are still login with your account. if you log out and come back it will work. For new people, they won't be login so they will see "sign up".

about settings page:
ok I will change them

**Comment by loicginoux** [comment]
Sorry I said something wrong. I thought that the whole register page was alin in center but realised that it was the coaching intensity that was wrong.
Everything will be left aligned in the register page and the buttons will also be vertical, like in settings page.

**Comment by jdaudier** [comment]
Do you know if there's a way to pass the coaching intensity level to Intercom?

**Comment by loicginoux** [comment]
yes, I'll add it now, it will be there next time I push it.

**Comment by loicginoux** [comment]
Can we close this?
