### ISSUE TITLE
Follow bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#183]
I think I followed this guy by pressing the "follow" button twice (by mistake) and now he shows up twice on my following page: 

http://screencast.com/t/WtswDeSe

**Comment by loicginoux** [comment]
Ok I will check what I can do. For now I deleted the duplicate friendship object

**Comment by loicginoux** [comment]
Ok for this, I disable the button just after the first click

**Comment by jdaudier** [comment]
Ready to go live.
