### ISSUE TITLE
Upload window missing in IE9

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#186]
fongdiggler 9:26pm, 1 Jan 2013

Trying to upload a photo using IE 9 and having trouble.

Using an HP laptop and when I click on upload, I don't get a window to upload the photo.I'm thinking there should be a browse button and an upload button, but don't see a browse button.

**Comment by jdaudier** [comment]
any luck with this?

**Comment by jdaudier** [comment]
Andy said: 
I am also was able to upload photo's with Google Chrome.  So it seems that IE 9 was causing the issues when I upload from IE.

**Comment by loicginoux** [comment]
I installed virtual box with ie9. I can now reproduce the error. I am investigating the error now...

**Comment by jdaudier** [comment]
Do you want to push this fix onto the live site and I'll ask Andy to try it since I'm on a Mac?

**Comment by loicginoux** [comment]
Now that I have a hand on IE I will test everything on this browser before deploying to live site.

**Comment by jdaudier** [comment]
Ok - I can ask Andy to test this once it's live since I don't have IE9.

**Comment by loicginoux** [comment]
just reopen if it's not working
