### ISSUE TITLE
Log in bug from iPhone 5

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#188]
Sho Masui reported:

When I clicked the "create account" button, nothing happened. But, I think I got it with the Facebook login. But I didn't get a confirmation email so I wasn't sure.

I did it on my phone (iPhone 5)

**Comment by loicginoux** [comment]
Do you have an Iphone 5 to test that? on 4S, it is working fine.

**Comment by jdaudier** [comment]
Sho reported at 12:25 pm today:

It says that the app does not have access to my photos when I upload from my iphone5.

**Comment by loicginoux** [comment]
After a bit of research this looks like an Iphone privacy security. she need to go to settings>privacy>photos and allow the browser that she uses to access the site to upload photos
see [link](http://ipod.about.com/od/UsingiOS6/ss/Using-Iphone-Privacy-Settings-In-Ios.htm)
and another [one](http://support.tenthbit.com/customer/portal/questions/515993-this-app-does-not-have-access-to-your-photos-or-videos-)
I close the issue, reopen if it didn't fix the problem
