### ISSUE TITLE
View other people's profile

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#19]
As a user, I want to be able to view other people's profile

**Comment by loicginoux** [comment]
What would I see from them?
how would I search and find other people?
I need more information and I would maybe need wireframes.

**Comment by jdaudier** [comment]
There's a page that shows everyone:
https://www.dropbox.com/s/j25r3814qg7wf3n/everyone-page.png

From that page, maybe we can add a follow icon to the top right corner of the image (an eye icon) that will let you follow that person.

That person will then show up on your "following" page:
https://www.dropbox.com/s/np09erztnt8dqau/following-page.png

When you click on a person you're following from that page, you see their journal - just like how you would see your journal.

**Comment by jdaudier** [comment]
3 text changes: http://screencast.com/t/wBxZwkwAlYh6

**Comment by jdaudier** [comment]
2 more text changes: http://screencast.com/t/WT4pQ7q6
