### ISSUE TITLE
Emailing photo bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#190]
Song reported at 7:25pm today:

I emailed a food pic 10 minutes ago, it's not on the site

**Comment by loicginoux** [comment]
to find it more easily, could you tell me how much calories did he put? I will try to find a email sent around this time but that would be easier with calories

**Comment by loicginoux** [comment]
That's ok I found it... I'll come back when I know more

**Comment by loicginoux** [comment]
Can you ask him, wasn't it this one?
http://www.foodrubix.com/data_points/1652
This is the only photo I can see in mailgun sent by "coldangelfire311@gmail.com"  that had problems. At the end the system managed to process it. Can you ask him? thanks

**Comment by jdaudier** [comment]
He said the issue had to do with his phone and that the image showed up eventually.
