### ISSUE TITLE
Log in bug 

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#192]
Hani reported today around 9pm:

I click the email verification and saw this page: http://cl.ly/image/332y0L3j3b0L

when I tried to log in, I got this error: http://cl.ly/image/221f1B2y3C3X

**Comment by jdaudier** [comment]
I went in the admin console and manually confirmed him

**Comment by jdaudier** [comment]
ok - so this is all fixed?  You extended the time.

**Comment by loicginoux** [comment]
no I just closed the duplicate issue on github, to clean up the list of issues. I am looking at this now.

**Comment by loicginoux** [comment]
So what I did:
- I extended the time limit from 10 minutes to one hour.
- I added in the verification email, the line 

"Note that you have one hour to complete your registration, in case you verify your account too late, you will be asked to restart the registration process."
- if the user still verify too late, the user is redirected to the registration page, and the message is now:

"We're sorry, but you verified your account too late. you had one hour to do it. Please restart the registration process."

you can test directly in testing instance by creating a new account and wait an hour between registering and verifying your account.

**Comment by jdaudier** [comment]
Minor text update: 

You have one hour to complete your registration. If you don't, you will be asked to restart the registration process.

Registration page:
Your verification link has expired. It is only valid for one hour. Please restart the registration process.

**Comment by loicginoux** [comment]
This is now live.

**Comment by jdaudier** [comment]
ok so you were able to make the minor text updates, correct?

**Comment by loicginoux** [comment]
yes, sorry I didn't notice you, I just did directly after you put your comment.
