### ISSUE TITLE
Adding description and time to images is not responsive

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#194]
User's name: Song Zheng

Request received: 1/2/2013 6:11:40 AM

Message from Song Zheng:

Adding description and time to images is not responsive.

I filled up the time and description of my food and then clicked on submit. It seems to be loading forever. 

Screenshot:
http://cl.ly/image/2q1C2S2Q2a0d

I'm using Chrome

**Comment by loicginoux** [comment]
I think this is linked to #193 
if she tried to do it in the url link that goes to a photo given by the email, It wasn't working. Now this should be fixed.

**Comment by jdaudier** [comment]
ok - i will ask him to try it again

**Comment by loicginoux** [comment]
Can we close this one?
