### ISSUE TITLE
Admin console broken

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#195]
I can't award users: I get a "something went wrong" message

if I award Chrissy for an old photo from yesterday (last month's cohort), will the point count in this month's leaderboard or last month?  I want it to count to the all-time but not this month.

**Comment by loicginoux** [comment]
ok you should be able to award photos when I push to live site.
At the moment when you award a photo, monthly and all time leaderboard points are updated without taking into account the uploaded date of the photo.
I created the issue: https://github.com/loicginoux/joanne_project/issues/200
