### ISSUE TITLE
Links at bottom of Leaderboard and Slackerboard in email

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#196]
Add this link below Monthly Leaderboard in email:

Don't see yourself here? Click here.

"Here" should link to the Team Rubix page showing the user's ranking on the monthly leaderboard.

**Comment by jdaudier** [comment]
When user click "here" from the email, they'll see their ranking on the Team Rubix page, correct?

**Comment by loicginoux** [comment]
yes

**Comment by loicginoux** [comment]
is that ok to close this?
