### ISSUE TITLE
ribbon for winner of leaderboard

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#197]
show a ribbon in the leaderboards for the winner of last month: http://d.pr/i/vTWG

Would it be possible to have a tooltip that pops up when you hover over the badge that says: Dec 2012 Winner

Here's a SVG of the winning badge: https://dl.dropbox.com/u/125982/Winner%20Ribbon.svg

**Comment by loicginoux** [comment]
do you want it for last month only or for all previous months?

**Comment by jdaudier** [comment]
all previous months will be good

**Comment by loicginoux** [comment]
What if a person has too many ribbon to fit in the page?

**Comment by jdaudier** [comment]
we can put a max amount that will fit on the line perhaps?

**Comment by loicginoux** [comment]
ok

**Comment by loicginoux** [comment]
Hey, I am working on this.
Would you display the ribbons in both Monthly leaderboard and total leaderboard (like in the screenshot above)? I think I would only display it on the  total leaderboard, duplicating it would be too much for me.
your thoughts?

**Comment by loicginoux** [comment]
concerning the limit per line, I put the last 3 prices. So at the moment if a user wins more than 3 prices, it will only show the last 3 ones.
this is not a perfect solution and that still can break if a user has a really long name like [this screenshot](http://awesomescreenshot.com/02dy08y09) but this can do for now.
We can improve it later if we see that users starts having more than 3 prices.
what do you think?

**Comment by jdaudier** [comment]
Looks good...just on the all time leaderboard is good

**Comment by loicginoux** [comment]
this is in testing now

**Comment by jdaudier** [comment]
Got this error when I tried to view the Team Rubix page on staging site: We're sorry, but something went wrong.

**Comment by loicginoux** [comment]
ah yes I forgot something. Also Anything won't appear until end of the month. If you want I can manually generate the ribbon for "Winner January 2013".

**Comment by jdaudier** [comment]
That's ok, we can start the ribbons starting Feb 2013

**Comment by loicginoux** [comment]
Hi this is live now. We should see the first one on the first of next month.
I added a panel in the admin console.
http://www.foodrubix.com/admin/leaderboard_prices
this list all monthly prices, if you create one, the name field correspond to the name of the price, i.e. "Winner february 2013"
You can create or edit them from here. 
You can also test this in the staging site first.
I close this for now. If there is anything open a bug issue. 
Thanks

**Comment by jdaudier** [comment]
It should be Prizes, not Prices =)

**Comment by jdaudier** [comment]
Do I need to manually give you the awards or will the system do it automatically at the end of each month?

**Comment by loicginoux** [comment]
It will work manually.

**Comment by jdaudier** [comment]
So I should do it at the 1st of each month, correct?

**Comment by loicginoux** [comment]
sorry sorry, I meant automatically, the system does it, you shouldn't have to do anything. 
You can still check in the admin panel if there is anything wrong.

**Comment by jdaudier** [comment]
Can we change it from Prices to Prizes?

**Comment by jdaudier** [comment]
Where does the "Winner Feb 2013" show up?  Does it show up on the live site when they hover over the ribbon?

**Comment by loicginoux** [comment]
yes, you can see it here
http://calm-gorge-1213.herokuapp.com/team_rubix

**Comment by jdaudier** [comment]
Nice!
