### ISSUE TITLE
Date bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#198]
8:17am
Gwen Frederick
the email wasn't uploading my photos to the website from my photo.  i think that might be a bug. i was using this one. pic@foodrubix.mailgun.org

8:23am
Gwen Frederick
i think i posted on meal in march 3 2013.... you might want to program the calendar to know what day is today and preventing users to upload on a future date. like a warning text message next, above, or below the calendar.
i also forgot were to send these feedback too. maybe a feedback button in our profile on the website?

8:25am
Gwen Frederick
yup there is a bug! i pressed 31 from the january calendar and it automatically reschedule it to march 3 2013. So i had to go into december calendar to press 31 to record a previous date.

I'm using google chrome for Mac

**Comment by loicginoux** [comment]
Hi,
1) this was due to capital email (issue #204)
2 & 3) I managed to reproduced the bug, this looks like a bug from the datepicker library we are using.

**Comment by loicginoux** [comment]
2 & 3) I manage to fix the bug by updating the library to its latest version

**Comment by jdaudier** [comment]
Ok to go live.  Do you think we should prevent people from adding a date that's in the future?

**Comment by loicginoux** [comment]
no, I don't think so. there is no need for that.
