### ISSUE TITLE
Comment on someone's photo

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#20]
As a user, I want to be able to comment on someone else's meal photos

**Comment by loicginoux** [comment]
where will I put the "comment" button? how would I display comments on meal? will I notify the owner of the meal that is photo has been commented? Will I notify the people that have left a comment that a new comment has been added?
Will I notify them by mail or only a notify icon in the app?
cann I edit/delete my comment?

**Comment by jdaudier** [comment]
I was thinking of a transparent pop-up on the bottom like this site http://www.sweeterspoon.com that has these things:

https://www.dropbox.com/s/gijl0vy4lcgg5ft/Image-detail.jpg

1st icon: heart / yum / like icon
2nd icon: comment bubble icon (like the bubble icon on http://dribbble.com)
3rd icont: follow icon (eye icon like this site: http://dribbble.com)
last icon: share icon (FB icon)

We will notify the owner via email about a comment as well as a notify icon in the app (like this: http://screencast.com/t/hVMEWYtT6tq).

It would be great if the commentator can edit or delete a comment.

**Comment by jdaudier** [comment]
I think we need to have a large pop-up when you click on an image (like this: http://dribbbleboard.com/#popular).

And the comments can be added below the large image like this: http://dribbble.com/shots/663779-Left-navigation

**Comment by loicginoux** [comment]
- ok, I agree with the popup to show the larger image, with number of "yum", comments, calories....
- do you want to show the comments on the popup or to have it  like on dribbleboard (I mean only having a link "show 12 comments" on the popup  that goes to another page "data point view page" with all details about the photo (all yums, all comments, calories...))
- I won't add all my thoughts about notifications as I already did it for the yum issue (#21) and the way it works will be similar.

**Comment by jdaudier** [comment]
I think the popup should be as big as possible to show off the photo.  I think it would be nice to see all the comments and yums on the popup so there's less clicks.

**Comment by jdaudier** [comment]
Remind me again what we decided about these features...

last icon: share icon (FB icon)

We will notify the owner via email about a comment as well as a notify icon in the app (like this: http://screencast.com/t/hVMEWYtT6tq).

**Comment by loicginoux** [comment]
- fb icon:
  I didn't add it. to be fair I don't really understand the point of it. Does anyone could share on his facebook a meal from anyone else? should we let the user leave a message with it? what text should we add with the photo?
- app notification:
  I didn't add that either, could we add that on sprint 5? Users will be notified on the app as well as per mail. 
  I think it would be better to put that on sprint 5 as it requires some more discussion the exact way it will work.

I propose to add these two in sprint 5, what do you think?

**Comment by jdaudier** [comment]
Sounds good - maybe we don't need the manual FB share.  I was thinking that can be an option in case user turned off the auto-share via FB.  What do you think?

**Comment by loicginoux** [comment]
so you mean that you would see the fb share icon only if you don;t have the auto-share on and only if it's your photo? no need to share other's people photo?

**Comment by jdaudier** [comment]
Right, only FB sharing of your own photo.  But do you think that'll be useful?  Maybe not?

**Comment by loicginoux** [comment]
I don't think this is a high priority. For now only the option to share or not on facebook is fine. I would do that later if users think that sharing everything is too much bu they still need to share some of their best meal.

**Comment by jdaudier** [comment]
OK - let's leave that for future.

**Comment by jdaudier** [comment]
Quick question - is there an easy way to make the javascript popup font be the same font type as the other fonts on the site (I think sans-serif might be easier to read)?
