### ISSUE TITLE
Sending photo by Hotmail via computer not working

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#205]
Sending a photo in hotmail to pic@foodrubix.mailgun.org from a computer doesn't work

Using Google Chrome

Is there a file size limit?

**Comment by jdaudier** [comment]
I sent in a 1.3MB photo at 5:31pm today.  It has not shown up.

**Comment by loicginoux** [comment]
the limit is 3Mb. I will try to send a photo by mail as well

**Comment by loicginoux** [comment]
I notice in logs that lot of people use a different address than the one in the database to send photo by mail.
example:
- Eric C. sent with address etc.chou@gmail.com. I am not sure who is this user... but he doesn't use the right address.
- Colin sent photo using his email colin.nederkoorn@me.com but is registered in app with colin.nederkoorn@gmail.com
- you too... :) you sent your photo using jdaudier@outlook.com but you are registered with joanne@learnstreet.com

One solution in case the user is not found is to send back an email saying that no account has been found with this email address and that maybe the user used another address to login, and that he can check what email address is registered by going to his setting page.

Another solution would be to have a way to register a main email address (the current one) but being able to add more address with which you could send photos.

**Comment by loicginoux** [comment]
Also can you let me know which user had this problem, and with which email address he sent it? 
thanks

**Comment by loicginoux** [comment]
I think it was 
gwenfred     with email Thegwenster@hotmail.com

This was same issue as #204 so I lowercased her email

**Comment by jdaudier** [comment]
I like this idea: send back an email saying that no account has been found with this email address and that maybe the user signed up with another address, and that he can check what email address is registered by going to his setting page.

Maybe we can link them to the Settings page so they can go there with one click to update the email.

**Comment by jdaudier** [comment]
Duh - I sent in a photo from Hotmail but of course it didn't work since that's not my email in my account.   Oops!

**Comment by jdaudier** [comment]
Actually this is probably even a better idea since they can choose which email to get the daily emails and which one to send the photos in from.

Have a way to register a main email address (the current one) but being able to add more address with which you could send photos.

The email could link them to Settings and have them add an additional email and set which one to send the photos from.

**Comment by loicginoux** [comment]
I close this one as I think this was the issue. Please reopen if lowercasing didn't fix the issue
