### ISSUE TITLE
YUM a photo

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#21]
As a user, I want to be able to "YUM!" (LIKE) someone else's meal photos

**Comment by loicginoux** [comment]
same questions as for comments: where to put the button? how to display it? shall we notify the owner?

**Comment by jdaudier** [comment]
How's this: https://www.dropbox.com/s/gijl0vy4lcgg5ft/Image-detail.jpg

And when someone likes the image, you get an email and a notification on your profile.  Where would be a good place for a red circle notification?  Maybe over the Home link like this: http://screencast.com/t/hVMEWYtT6tq.

I was thinking of a transparent pop-up on the bottom like this site http://www.sweeterspoon.com that has these things:

https://www.dropbox.com/s/gijl0vy4lcgg5ft/Image-detail.jpg

1st icon: heart / yum / like icon
2nd icon: comment bubble icon (like the bubble icon on http://dribbble.com)
3rd icont: follow icon (eye icon like this site: http://dribbble.com)
last icon: share icon (FB icon)

**Comment by loicginoux** [comment]
- I wouldn't put the follow icon on an image, it will be already on a user's journal page. Im my opinion, you follow a user, not a photo...
- I like the tools that appears at the bottom of the pics when hovering over the pic like in the site sweeterspoon. I will do it this way.
- I would leave the fb share icon for now. I think that can be discussed for the next sprint.
- Personally I have a problem with the apps (i.e. facebook, github,etc...) that send an email AND have a notification on the site. I have to see the notification twice, the first time in my email box, and the second time on the site. Do you see what I mean? In my opinion, it's not a good user experience. it's repetitive, but I guess necessary. Maybe we can have on the settings page a checkbox for "send me an email when someone yum and comment my photos"... your thoughts?
- concerning the photo you "yumed", do you want to be able to browse them? shall we need another page to display them? do you want to be notified when someone else liked or commented a photo you like (could be optionnal, with checkbox in settings page)?
- can you "yum" one of your photo?
  -another though, we need a name or description for a photo, I open a new issue for that for clarity (see issue#33 )
- we need a "notifications" page (a page or a box like fb, what do you prefer?), that list all your unread notifications, for now all notifications that I can think of are:
  - "personX yumed your photo 'orange juice'"
  - "personY commented your photo 'orange juice' "
  - "personZ commented a photo you yumed"
  - "personZ also yumed a photo you yumed"

anything eles?

**Comment by jdaudier** [comment]
OK with follow icon on a user's journal page and not individual photos.

I like the idea of having a checkbox for:
Send me an email when someone yums my photo.
Send me an email when someone comments on my photo.

Q: concerning the photo you "yumed", do you want to be able to browse them? shall we need another page to display them? 
A: I think not for this sprint.

Q: do you want to be notified when someone else liked or commented a photo you like (could be optional, with checkbox in settings page)?
A: I think not for this sprint unless it's easy to implement.

Q: can you "yum" one of your photo?
A: I guess so since FB allows this.

Q: we need a "notifications" page (a page or a box like fb, what do you prefer?), that list all your unread notifications, for now all notifications that I can think of are:
        "personX yumed your photo 'orange juice'"
        "personY commented your photo 'orange juice' "
        "personZ commented a photo you yumed"
        "personZ also yumed a photo you yumed"

A: I like a red notification box like FB since that's pretty addicting for people to look at.

**Comment by jdaudier** [comment]
Some icons here: http://iconmonstr.com

You can search "heart" for example.
