### ISSUE TITLE
Replace image does not work

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#210]
Jerry Huyhn reported @ 11am today:

replace image no workie...had to delete and make new one...

**Comment by jdaudier** [comment]
He is using Firefox 17.0.1 on XP.  It was the steak picture.

**Comment by loicginoux** [comment]
I realised this as well while working on the IE bug, this should be fix on next release.

**Comment by jdaudier** [comment]
Is this the same bug?

User's name: Monelle Lewis

Users e-mail: monellelewis@yahoo.com

Request received: 1/8/2013 2:34:57 AM

Message from Monelle Lewis:

Editing

When I uploaded a picture and found that it didn't center correctly I tried to fix it by clicking the edit button. I updated the photo and clicked save changes but it did nothing. I tested it by trying to change the time and still nothing.

**Comment by jdaudier** [comment]
This is good to go live.
