### ISSUE TITLE
Email verification broken

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#211]
Monelle Lewis reported at 9 am today:

So I tried to follow the link after signing up for an account and it said : 
We're sorry, but we could not locate your account.
I tried to log in to my account and it said it is not active.
I tried to create a new account and it said my email and username have already been taken.
Monelle

--- On Sun, 1/6/13, hi@foodrubix.com hi@foodrubix.com wrote:

From: hi@foodrubix.com hi@foodrubix.com
Subject: [FoodRubix] Verify your account
To: monellelewis@yahoo.com
Date: Sunday, January 6, 2013, 8:57 AM

Thank you for signing up to FoodRubix!

Please click the following link to verify your email address:

http://www.foodrubix.com/user_verifications/9LadbC4HVxeQWbh3FgRS

**Comment by jdaudier** [comment]
She is using: Chrome Mac OS X 10.5

**Comment by loicginoux** [comment]
ok, It might come from the user not being active yet so the system can't find it... I will need to find out more.

**Comment by loicginoux** [comment]
this is a duplicate issue of #192 
closing this one
