### ISSUE TITLE
Drag & drop bug?

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#212]
A user have reported a bug using CrowdIntelligence from your website FoodRubix

User's name: Sho

Users e-mail: sho@shomasuicorp.com

Request received: 1/6/2013 11:51:39 PM

Message from Sho:

click drag pictures

click-drag doesn't work across weeks. I have pictures on Sunday that I want to put into Saturday of the previous week.

**Comment by jdaudier** [comment]
He was trying to take pictures from today (Sun) and dragging it to yesterday (Sat).  Maybe that's not possible.

**Comment by loicginoux** [comment]
no it's not yet implemented. I close this issue as this is not a bug. I created the issue #217 for this feature in future sprints.
