### ISSUE TITLE
Decimal as calories

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#214]
When I enter a calorie with decimal, the progress bar is stuck when I press save.

http://screencast.com/t/dzGm7LB6

**Comment by jdaudier** [comment]
Decimals shouldn't be allowed to be entered or just round the number after someone hits submit.  

Old school way is to have an alert saying "No decimals allowed".

**Comment by loicginoux** [comment]
I will just round the number.

**Comment by jdaudier** [comment]
I tested 100.7 and 100.8 but it didn't round up to 101.  Did you mean to have it that way?

**Comment by loicginoux** [comment]
I am taking the entire part of the number, i.e. you should have had '100' saved and displayed, didn't you?
this is what's happening for me when testing these two numbers

**Comment by jdaudier** [comment]
Ok i see.  I thought you were rounding it based on math.  But I guess you're rounding it to the whole number by removing the decimal.

**Comment by loicginoux** [comment]
Yes, I didn't really think about that... and I guess one calorie difference is not that important
