### ISSUE TITLE
Weird message after signing in using Safari

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#216]
Signed in using Safari about 10:46pm today and saw this error message: "user does not exist"

http://screencast.com/t/MymO1F3LS63

**Comment by loicginoux** [comment]
I am not sure to know why but here is how this appears:
- if you go to url  foodrubix/joanne this will find the user with username "joanne" and go to your diary
- if you go to url  foodrubix/jooaaannnnee this will not find the user with username "jooaaannnnee". It will redirect you to the current logged in user with this message.

That explained, I can't reproduced your bug, can you know reproduce it?

**Comment by jdaudier** [comment]
I couldn't duplicate this error again.
