### ISSUE TITLE
change picture when editing photo in IE9 not working

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#219]
technical reminder: 
due to IE setting the method "GET" on the form instead of "PUT" (as all other borwsers do...)

**Comment by loicginoux** [comment]
I think this is a bug which is not worth fixing at the moment. From Google analytics, there were only one user who visited the site and he is not a registered user. If in the future you have a lot more users coming from ie9, this can be re-considerated.
I Already spent some time on this without success and I think it will be a waste of money to continue trying to fix that.
What do you think?

**Comment by jdaudier** [comment]
OK let's close it for now
