### ISSUE TITLE
Thur (July 26) bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#22]
If you log in to my account, you'll notice that on Thur, the calories didn't add up correctly.

username: joannedaudier
pwd: foodrubix

I tried to upload one photo a couple of times but it didn't show up, but I think the calories are being added somehow.  This is the photo that would not get uploaded correctly: http://dl.dropbox.com/u/125982/280299_10150989124802444_1590677102_o.jpeg

**Comment by loicginoux** [comment]
duplicate with issue #29
