### ISSUE TITLE
Like bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#220]
Chrissy reported @ 9:30 am today

I'm not sure what I did.. I've just followed Monelle, and when I looked at her diary it shows that I've hit 'like' on many of her pictures, which I've never clicked like for them (I never clicked like for the banana milk shakes, the nachos, or the tea). I don't know if it was because I started to follow her that it automatically liked all those pics. I only remember clicking 'like' on the cranberry soup and the salad picture.

**Comment by loicginoux** [comment]
changed to medium priority as it doesn;t stop the user to use the app

**Comment by jdaudier** [comment]
She said: This morning I used my iPhone to browse, so maybe it's because of that..?

**Comment by loicginoux** [comment]
Ok the problem is when you open different photos popup, and then click one "like", it will like all the ones you previously open in the same page... I change that

**Comment by loicginoux** [comment]
now live
