### ISSUE TITLE
Daily Caloriei Goal will not update

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#222]
User's name: monelle

Users e-mail: monellelewis@yahoo.com

Request received: 1/9/2013 3:46:19 AM

Message from monelle:

Daily Caloriei Goal will not update

I have tried 3 times to update my personal information like age and sex and it doesn't seem to be updating

**Comment by loicginoux** [comment]
I don't think I will be able to do anything on this one as this will be due to Wolfram. let's wait what she answered to your email

**Comment by jdaudier** [comment]
Does our setting calorie goal part (not Wolfram) work though?

**Comment by loicginoux** [comment]
yes

**Comment by loicginoux** [comment]
I close this as we can't reproduce. Reopen if it still happening or yo u can reproduce it.
thanks
