### ISSUE TITLE
Pwd reset not working for Justin

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#223]
Justin reported around 8pm today:

Cannot log in at the moment. I tried to reset the password but no luck.

**Comment by loicginoux** [comment]
I can't replicate the issue, does she have more info about what is going wrong for her? what did she do and where did it stop working correctly? 
thanks. 
I will check the logs to see if I can find what happened

**Comment by loicginoux** [comment]
I close this as she was inactive
