### ISSUE TITLE
Show more bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#225]
I see a "Show more" on the Following page but when I click, it doesn't expand:

http://screencast.com/t/tPRDhqoDb

**Comment by jdaudier** [comment]
Could it be because I deleted a user (tremblaa)?

**Comment by loicginoux** [comment]
can you replicate it after relaoding the page? which box is it?

**Comment by jdaudier** [comment]
yes, i can replicate it.  It's the Following page for me.  Link to video above

**Comment by loicginoux** [comment]
aaah because it wasn't intented to be on this page. I will make it work

**Comment by jdaudier** [comment]
What happens if I have a lot of followers?  Would "show more" show up?

**Comment by jdaudier** [comment]
I can't find Josh on my FOLLOWING page even though I followed him: http://www.foodrubix.com/joshonketo

**Comment by jdaudier** [comment]
Don't see Nikki either: http://www.foodrubix.com/lafemmeniketo

**Comment by loicginoux** [comment]
This is because I was showing only the first 15... I am fixing that now

**Comment by loicginoux** [comment]
I don't have that much people on the live site but that was working for me when testing locally, can you let me know and close this if it's ok?
thanks

**Comment by jdaudier** [comment]
works now
