### ISSUE TITLE
0 calorie bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#226]
https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-prn1/v/59962_636497107656_616084157_n.jpg?oh=9ac2dc364bd113e141eaec65f2834fa7&oe=50EFC00F&__gda__=1357963719_f5284bbd7a3bd54618afac6680b199fe

notice a bug for entering "0" for water.

the 0 calorie did work when i posted it from the email account but it was set at the wrong time so i tried to adjust the time and it would not let me save with 0 calories so i had to write in 1 calorie.

**Comment by loicginoux** [comment]
ok
