### ISSUE TITLE
Uploading not working

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#228]
User's name: monelle

Users e-mail: monellelewis@yahoo.com

Request received: 1/10/2013 5:08:20 AM

Message from monelle:

not uploading

i have tried twice to upload a meal and it is not showing up or counting the calories
i am using chrome

**Comment by loicginoux** [comment]
I cannot reproduce this bug, can you?
does she still have this bug? if yes what are the steps that lead to this bug?

**Comment by jdaudier** [comment]
She said: The photo never showed up. It was a sandwich w/o soup.

**Comment by loicginoux** [comment]
I think this is a bug I fixed on last release. I will close it for now. As we can't reproduce it
