### ISSUE TITLE
Comment bug?

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#230]
Account switched during commenting:

http://www.foodrubix.com/data_points/2291#

**Comment by loicginoux** [comment]
sorry, I don't understand. This photo belongs to lafemmeniketo, see http://www.foodrubix.com/admin/data_points/2291
what's wrong?

**Comment by loicginoux** [comment]
ah was it before the photo from "Joshonketo"?

**Comment by jdaudier** [comment]
yea somehow she was logged in as her but the comment had her husband Josh's name

**Comment by loicginoux** [comment]
I think she was login as her husband when she commented, when she receive the mail notifying her that you previously commented on her meal, she click the link and open the page. I guess her husband was previously login in this browser so she didn't notice that she was logged in as him... I can't see another way. She didn't respond your two questions you asked in comments, that would be helpful. I will close this in few days if there is no news on that.
