### ISSUE TITLE
can't open the upload box after having uploaded an image

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#231]
the only way is to reload the page :(

**Comment by jdaudier** [comment]
that's not good =)

**Comment by loicginoux** [comment]
I fixed that already, this will appear shortly

**Comment by jdaudier** [comment]
Is this the same bug? 
Vicky reported @ 4:44 pm today:

After I use the "upload" button to upload a photo, the button wouldn't pop-up the window again.  Using Firefox and Chrome (same issue).  Jerry said the same thing happens for him as well.

**Comment by loicginoux** [comment]
Yes, It must be, this is on the testing site but not yet live. this will be shortly, I want to finish other bugs before deploying again on live site.

**Comment by loicginoux** [comment]
this is done
