### ISSUE TITLE
Award in emails

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#234]
If I select 2 awards per day by 2am, it'll get added automatically to the daily recap emails. 

Don't think we need it for the weekly email since it'll already show up on the daily email on Sunday.

**Comment by loicginoux** [comment]
So the award will be displayed in email if a photo from the previous day (at 2am) has the award. So if you award a photo  from 2 days ago, it won't appear in emails.the award needs to be given to a photo from the finishing day.
You can see the email preview 
http://www.foodrubix.com/admin/mailer/preview_daily

**Comment by jdaudier** [comment]
Can you add "on" to "Congrats Sho on winning the Hot Photo Award."?

**Comment by loicginoux** [comment]
I close this. I added the "on"
