### ISSUE TITLE
add code snippet to inform users that his browser is outdated

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#235]
http://www.browserawarenessday.com/

**Comment by loicginoux** [comment]
For records, I supposed the browser is outdated when the release date was in 2011 or before. I don't  think this is too short as now most browsers are automatically updated.
outdated browsers:
Chrome < 16
Firefox < 10
IE < 9
Safari < 5
Opera < 11

**Comment by loicginoux** [comment]
This will only appear in pages with the homepage layout (home, login, register, tos, privacy). I didn't put it in the pages of the app, is that ok?

**Comment by jdaudier** [comment]
ok - because the assumption is that they'll see the alert and update before they sign up, right?

**Comment by loicginoux** [comment]
Some people will not change even if this message appears. I prefer to have it only on the first pages they visit (homepage or login or register) and not having it everywhere in the site

**Comment by jdaudier** [comment]
agreed
