### ISSUE TITLE
Email error

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#238]
Chrissy lives in Montreal and she reported:

The email 'this is what you ate yesterday' from last night showed I only ate 1 thing (470 cal) when I ate 3 things. (All 3 pics were there when I went on the site) 

Also it didn't talk about the new Smart Choice & Hot Photo awards.

**Comment by jdaudier** [comment]
Vicky added photos yesterday but got an email saying she didn't upload any.

**Comment by loicginoux** [comment]
Yes I realised that today as well and I had to update the time of few pictures from yesterday. Unfortunately I did that after that  the email was sent and pictures were not yet moved. I think it should be better now.

**Comment by jdaudier** [comment]
Since the email goes out at 2am in each time zone, does that mean not everyone will see the 2 award photos?

**Comment by jdaudier** [comment]
Chrissy reported today: Everything looks ok in the daily email except the picture of my 'Smart Choice award' was from 2 days ago.

**Comment by loicginoux** [comment]
could she forward the email she received? from my daily email of today, her photo were from yesterday, it was this photo:
http://www.foodrubix.com/data_points/2605
in your email did you not receive the same one?

Concerning your timezone question, this is a good point and I didn't realize that. What I already did anyway because of this problem of timezone is that I show in the emails the last awarded photo (sorted by their date) and I don't take into account the date it has been taken. The only issue I see with this way is that if one day you don't award a photo, the awarded photo that will appear in the daily email will be the same as the day before. Does it sound ok?

**Comment by loicginoux** [comment]
by the way this is a good tool for working in a team with different timezone http://www.worldtimebuddy.com/time-converter

**Comment by jdaudier** [comment]
I saw these images: http://screencast.com/t/uMeTf8Kj5Pb

Chrissy is in Montreal, Canadian time and she saw these: http://screencast.com/t/LnEruFA7

**Comment by jdaudier** [comment]
I'm ok with your workaround of taking the last 2 awards posted regardless of date it was taken.

**Comment by jdaudier** [comment]
Since email is sent out at 2am in each user's time zone, does that mean I have to pick them earlier if I want the correct ones to show up in Chrissy's email?

**Comment by loicginoux** [comment]
If you want her to see the same award as you you need to choose your award before her 2am (more exactly 2:10am).
If you don't she will always see the award from the day before.
This is a problem with all timezones that are in advance to you. For example, how we would do with someone in my timezone? my 2am is your 6pm, so I will always see the one from last day...
Another solution will be to send all emails at your 2am. So, in my timezone, I will receive the daily email recap at 10am the day after...
what do you think is best?

**Comment by jdaudier** [comment]
What do you think about this? Maybe we can have the email go out at 7am for everyone instead of 2am (push it out by 5 hours)?  This way I'll have extra time and people in North America will see the same Award Photos at least. For other countries, I think different award photos are ok.  Thoughts?

**Comment by loicginoux** [comment]
Ok that's fine.

**Comment by loicginoux** [comment]
just for linking them together: #249
