### ISSUE TITLE
Time bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#239]
I sent this photo in at 10:23pm but it showed up in the diary with the time 6:23 am the next day.

http://screencast.com/t/8DfhlHbRQJX

**Comment by loicginoux** [comment]
I saw this photo as well. This was the same bug as Chrissy's. the time for this photo should have been updated with the other photos I moved but I only run the script for the photos that had the time before "now" (this morning around 11am) so I missed yours. Let me know if you still encounter issues with time in the days to come.

**Comment by loicginoux** [comment]
duplicate of #238
