### ISSUE TITLE
can't upload when fb sharing unchecked

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#24]
I unchecked FB sharing button.  And now I can't upload the attached image to my account.  I get a broken link.

**Comment by loicginoux** [comment]
I can't replicate,
the steps I followed:
- with fb sharing checked: uploading works and get added to fb
- with fb sharing unchecked: uploading works and doesn't get added to fb 

Can you try again please and give me more info (the broken link that you have, the exact time for your failed attempt etc..)?
have you tried with same image with the fb sharing checked to see if it was not the image the problem?

**Comment by jdaudier** [comment]
Works now.  I think it wasn't working before due to the file extension jpeg.
