### ISSUE TITLE
start doing automatic testing

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#241]

**Comment by loicginoux** [comment]
Are you still ok to do this one?
Just because it can takes some time to do if you want to test everything correctly. It's a good one to have in the long term though.
Also note that having that won't remove all bugs, it will only insure that that is tested works. New bugs not tested can still be discovered.
What I would do is spend few hours on this in order to set the testing environment, and run the tests during deployment. I will then start to write few tests. I will then have a clearer idea of the work involved to test everything properly.
Is that ok like this? Do you have anything to add?

**Comment by jdaudier** [comment]
Yup, I still think this is a good idea. I'd like to prevent bugs like repeat photos from happening whenever we push.

**Comment by loicginoux** [comment]
I started writing  tests. There are lot of different kind of tests that can be written and it could be another full-time job. What I will do is start by writing the integration tests. These only test the behaviour of the app in general like if it was a real user. It won't see if the style is broken but more if features are not working.
This is the link I used to get started:
http://net.tutsplus.com/tutorials/how-i-test

So if we now start testing all new features and use BDD (Behaviour Driven Development) we should change the way we approve and work on a new feature. we will write new features this way: 

```
Feature: Signing In
  In order to use the application
  As a registered user
  I want to sign in through a form

Scenario: Signing in through the form
  Given there is a registered user with email "user@example.com"
  And I am on the sign in page
  When I enter correct credentials
  And I press the sign in button
  Then the flash message should be "Signed in successfully."
```

While you can write the feature part, I will write the different scenarios that goes with it. This is useful for several reasons:
- It will serve as a contract for a feature. We will know through the different scenarios what a feature implies. It's clearer for both of us
- From a feature written this way, I can start testing with Cucumber like explained on the link above.

Is that ok with you?

**Comment by jdaudier** [comment]
Sure, sounds good

**Comment by loicginoux** [comment]
I close this one if it's ok.
