### ISSUE TITLE
security check

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#243]
with this tool https://detectify.com/

**Comment by loicginoux** [comment]
Ok looking at it a bit deeper now, this is 99$ per scan so I guess we will wait for that.

**Comment by loicginoux** [comment]
Good news. After having sent a constructive feedback on there app, they offered me a credit for a free scan.
So I will try that.

**Comment by loicginoux** [comment]
this is the report from detectify:
https://detectify.com/report/5821/calm-gorge-1213.herokuapp.com/d8b0960ec0ee4205315b9851c477db4d98d8a86a%20

I don't think there is anything major here.

**Comment by jdaudier** [comment]
I couldn't see the report. Do I need to sign in using your logins?

**Comment by jdaudier** [comment]
I'll defer to your expertise here since I don't quite understand the errors.
