### ISSUE TITLE
Empty States for dashboard

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#247]
When there's no photo in week view, we should add in a gray arrow pointing to the Upload bar (like this: http://bit.ly/YrEbv5) with text:

"A journey of a thousand miles begins with a single step." -- Confucius

Inspirations: http://emptystates.tumblr.com/

**Comment by loicginoux** [comment]
do you want that for every week empty week (when you go in future week as well?) what about month view and day view? should it be only for the current week/month/day?

**Comment by jdaudier** [comment]
I was thinking just for the current WEEK view since that's the default view they'll see when they log in.  Thoughts?

**Comment by loicginoux** [comment]
ok

**Comment by loicginoux** [comment]
And I imagine this is only visible on your own dashboard...

**Comment by jdaudier** [comment]
Right

**Comment by loicginoux** [comment]
this is what I see when I first login: http://awesomescreenshot.com/008vljce0
the upload button is hidden by the tip...
Should we move the upload button to the left?
In terms of user experience, it will also be better. In websites the most important parts of your content must be on the top left (this is the part of the screen that people see first). That should be a better place for the upload button.
how it would look like: http://awesomescreenshot.com/0cdvlkn26
what do you think?

**Comment by loicginoux** [comment]
another empty state when new people join: http://awesomescreenshot.com/0b0vllhaa
we should do something for that, don't you think? maybe having the "all people" feed like discussed in #128 and in the box "people that inspire you" a text to explain them they can "bookmark" friends with a link to the team rubix page.
thoughts?

**Comment by loicginoux** [comment]
ok what about the empty state arrow then? If I point the arrow to the new place of the button. the text won't be aligned in the center of the screen, is it a problem?

**Comment by jdaudier** [comment]
Once the user closes the tip, they will see the arrow pointing to the Upload button, correct?

**Comment by loicginoux** [comment]
yes sure, it's just when they first log into the site for the first time, that it will be a bit weird

**Comment by loicginoux** [comment]
or maybe it's not that much important and we can leav it like that... (but for me it's not 100% clear)

**Comment by jdaudier** [comment]
To make it easier, maybe we just leave the orange upload button location unchanged.  But can we move the arrow up just a tad like this? Arrow doesn't have to be straight. I only had a straight arrow to draw with.

![arrow](https://f.cloud.github.com/assets/1666031/119312/29dd2ace-6ca0-11e2-9fa1-d32607fa008c.png)

**Comment by jdaudier** [comment]
I think the user will think we're pointing out the tool tip which will be ok.  And then once they close the tip, the arrow will still make sense as it'll point to the Upload then.

**Comment by jdaudier** [comment]
Regarding Following page, I would suggest these changes:

Change heading from "Following" to "Feed" and show global feed by default with option to toggle to "Following".  Once you set that, it should stay that way in the future when you log in unless you toggle again.

Under "People that inspire you", I would put a text that says:

Don't be a loner. Follow a few people to fill this empty space to get inspired instantly.

**And "Follow a few people" can link to the Team Rubix page.

One other idea, MySpace used to add the founder Tom to your friends list automatically. Maybe I can be auto added as someone they're following after they sign up since I am hidden on the Team Rubix page?

**Comment by jdaudier** [comment]
Can we put the Confucius quote in quotes: "The journey of..."

**Comment by loicginoux** [comment]
Ok with everything, I will add it.

**Comment by jdaudier** [comment]
Do you have a screenshot of our empty state for me to submit to this site? http://emptystates.tumblr.com/
Thanks!

**Comment by loicginoux** [comment]
http://awesomescreenshot.com/0d9w44n3f

**Comment by jdaudier** [comment]
Can we put the Confucius quote in quotes: "The journey of..."

**Comment by loicginoux** [comment]
done

**Comment by jdaudier** [comment]
So I found out it's not Confucious who said that quote (A journey of a thousand miles begins with a single step.
) but Laozi.  Can we update that?

**Comment by loicginoux** [comment]
No problem
