### ISSUE TITLE
add description when uploading image by mail

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#248]
the description is the body of the email

**Comment by jdaudier** [comment]
I just sent out a quick email to everyone to ask if they have default signature when they use their phone.  Because some phones have default signature, so we might have to account for that.  Maybe email body that starts with spaces are ignored... since it's usually spaces followed by signature.

**Comment by loicginoux** [comment]
what if you have a body like this?

```
  my super description
      sent by iphone
```

I mean when you have a description and a signature

**Comment by jdaudier** [comment]
Maybe we take everything before the word "sent"?

**Comment by loicginoux** [comment]
corner cases when it won't work:
- the word "sent" is actually in the description
- the signature is different (as the signature can be modified in you mail...)

**Comment by jdaudier** [comment]
Ok we can ask the users to put the description in quotes then?

**Comment by loicginoux** [comment]
ok, just to be clear, by quotes you mean these quotes "bla bla bla".
These ones won't be supported 'bla bla bla' because they can be misunderstood, like in this example: 'I won't eat this again' where only the "I won" will be taken as description.

**Comment by jdaudier** [comment]
Right, double quotes like these: "greek yogurt"
