### ISSUE TITLE
Freeze top bar

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#251]
Do you think we should freeze the top bar so that users can easily switch pages?

![bar](https://f.cloud.github.com/assets/1666031/117794/0e891f70-6c56-11e2-932e-e84a9e14d25e.png)

**Comment by loicginoux** [comment]
what do you mean? you mean that even if we scroll down, we keep the bar on top of the window?

**Comment by jdaudier** [comment]
Right - here's an example: https://dl.dropbox.com/u/125982/codermatch/index.html

Do you think we should do that?  I know that means it takes up space for the photos.

**Comment by loicginoux** [comment]
I am not sure... according to this article:
http://ux.stackexchange.com/questions/31439/whats-the-reason-behind-fixed-position-navbars

it's good to do that when the page is really long, especially in infinite scrolling website. the only place were it will be useful in our site will be on the "feed" page. For the rest of the site, this is not needed. Now if people use more and more the feed page, that will be better to add it.
I would say no for now, what do you think?

**Comment by jdaudier** [comment]
OK - let's push this out for sprint 8 when there might be more users.
