### ISSUE TITLE
Profile photo upload error

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#252]
Justin Miller said:

I'm having a tough time uploading a profile image.

Just won't let me upload it. I believe I am on Safari

**Comment by jdaudier** [comment]
I uploaded a photo for him using Safari, but we should still check on this bug.

**Comment by loicginoux** [comment]
I managed to do it as well, maybe it's his file, can he send us the photo he had problem with?

**Comment by jdaudier** [comment]
The image he had problem with is the one I uploaded for him.  Do you see it?

**Comment by loicginoux** [comment]
if no one can replicate the issue and I can't see anyting wrong in the logs, we can't really do anything... I will let the issue open for a bit to see if others have the same problem or if we can replicate it, but if there isn't any news on that I will then close it.
