### ISSUE TITLE
Profile photo enahancements

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#253]
For the default image, should we make the image fill the whole square?
![profile photo](https://f.cloud.github.com/assets/1666031/120571/5bed0280-6d06-11e2-9093-9d9d4b86925a.png)

And for the first time that you upload a photo, should it say "Save" instead of "Update"?  It can say "Update" once you have a photo set and is trying to update it.

![profile photo 2](https://f.cloud.github.com/assets/1666031/120574/8e9efe4a-6d06-11e2-94a3-b91b2febf787.png)

**Comment by loicginoux** [comment]
I already change the photo size on testing instance, I will change the button text

**Comment by jdaudier** [comment]
The button text only needs to change for the first time only.  It can stay "Update" once they already have a photo uploaded.

**Comment by jdaudier** [comment]
So this is live?
So it'll say "Save" the first time, and "Update" the following times, correct?

**Comment by loicginoux** [comment]
yes
