### ISSUE TITLE
Leaderboard points check

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#254]
Can we check the Leaderboard points again?

Not sure how Justin got up to the top without uploading any photos.  And he shows up as # 1 on Team Rubix and # 2 under Following, but shouldn't they match?

![2013-02-01](https://f.cloud.github.com/assets/1666031/120583/fc4fc7ac-6d07-11e2-9ee0-ac6ccdc2a27e.png)

![2013-02-01_2311](https://f.cloud.github.com/assets/1666031/120584/031b5c5e-6d08-11e2-97b1-6bfeb968216e.png)

**Comment by jdaudier** [comment]
Adding 2nd sort on username

**Comment by jdaudier** [comment]
I think you added the 2nd sort, right?

**Comment by loicginoux** [comment]
yes
