### ISSUE TITLE
Follow link in email

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#256]
When you follow someone and the email goes out, they should be able to automatically follow you straight from the email link.  You'll get to their diary page and button will say "Unfollow".

When you first follow: a message pops up to say:
"You're now following [Username]. You'll see what [Username] is eating under the Feed page."

("Feed" is a link)

**Comment by loicginoux** [comment]
I think it's better to not put anything in the mail if you are already following him, or maybe a message like "<USER> is now following you back". (adding the back at the end if you are already friend with him)

what do you prefer?

**Comment by jdaudier** [comment]
I agree. If you someone follows you (who you already follow).  Message could be:

[Username] has followed you back. One more reason to eat better - someone's watching you and cheering you on!

**Comment by jdaudier** [comment]
So this mean you can follow directly from the email link?

**Comment by loicginoux** [comment]
yes, this should work

**Comment by loicginoux** [comment]
I am gonna send you a follow email, you will be able to follow me if you are not already doing it

**Comment by jdaudier** [comment]
1) Should the error message be "You're already following [Username]. You'll see what [Username] is eating under the Feed page."

![2013-02-23_2347](https://f.cloud.github.com/assets/1666031/189239/cd21c8c6-7e5b-11e2-8d65-d3900b22e974.png)

**Comment by jdaudier** [comment]
Should we make "Feed" a link?

![2013-02-23_2348](https://f.cloud.github.com/assets/1666031/189240/1b962baa-7e5c-11e2-9ed3-849d633c9526.png)

**Comment by jdaudier** [comment]
Can we change the text to be: Follow [Username] back.

![2013-02-24_0008](https://f.cloud.github.com/assets/1666031/189241/2b33886e-7e5c-11e2-9a02-961f4b8747e1.png)

**Comment by jdaudier** [comment]
Is this implemented?

If you someone follows you (who you already follow). Message could be:
[Username] has followed you back. One more reason to eat better - someone's watching you and cheering you on!

**Comment by loicginoux** [comment]
Yes, I just forwarded you the message I received few days ago when you followed me back.

**Comment by jdaudier** [comment]
Can we make the change above in the email? 

Follow [Username] back.

**Comment by loicginoux** [comment]
Ok I change it now.

**Comment by loicginoux** [comment]
this is done as well

**Comment by jdaudier** [comment]
So now the email says, "Follow [Username] back.", correct?

**Comment by loicginoux** [comment]
yes see here:
http://www.foodrubix.com/admin/mailer/preview_follower
I noticed that the ink was the whole sentence, I changed it to be only the username. this will be push shortly.

**Comment by jdaudier** [comment]
Do you think we should hide the default user graphic when there's no real photo?

**Comment by jdaudier** [comment]
Regarding my question, it was related to this email actually. Did we add the word "back"?

![2013-03-15_1012](https://f.cloud.github.com/assets/1666031/264587/94774d42-8d93-11e2-957e-e84a2b7a18b0.png)

**Comment by loicginoux** [comment]
yes this has been added. The email generated now that people will see is the one from the link I passed you above. you're right, I will remove the default picture when there is no photo set.

**Comment by jdaudier** [comment]
I see a different email from your earlier link.
![2013-03-15_1102](https://f.cloud.github.com/assets/1666031/264759/b4ca935e-8d9a-11e2-8cd5-7e8fb9bfc54b.png)
