### ISSUE TITLE
empty state for feed page

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#258]
#128

**Comment by jdaudier** [comment]
Inspiration: http://emptystates.tumblr.com/

**Comment by jdaudier** [comment]
Under "People that inspire you", below my photo, can we add this text?

Don't be a loner. Follow a few people to fill this empty space to get inspired instantly.

"Follow a few people" can link to the Team Rubix page.

**Comment by jdaudier** [comment]
So next to my photo under "People that inspire you", there should be no points, right?

**Comment by loicginoux** [comment]
the text "Don't be a loner. Follow a few people to fill this empty space to get inspired instantly." should be there everytime? or only when you have no friends (or only you)?
If you prefer I can not display points for you (and more generally for people that are "hidden"), do you prefer?

**Comment by jdaudier** [comment]
Q: the text "Don't be a loner. Follow a few people to fill this empty space to get inspired instantly." should be there everytime? or only when you have no friends (or only you)?

A: I think every time when they only have 1 friend (me).

No points shown for me is good.

**Comment by loicginoux** [comment]
ok, I'll add that

**Comment by jdaudier** [comment]
I think we can make the font size for that sentence larger like the size of the "Feed" on the navigation.

**Comment by loicginoux** [comment]
I think if we do it as the navigation font size it will be too big.
- with the same size (18px): http://awesomescreenshot.com/0c2wtng83
- a bit smaller (16px): http://awesomescreenshot.com/00dwtnla1
- other option http://awesomescreenshot.com/0ffwtnr12

I would go for the last one

**Comment by jdaudier** [comment]
I like the last option. Can you show me how it would look with 1 user above it (since I'm auto added)?  I think we should add some blank space after the one user before we add the text.

Updated text (added comma, !, & "and"): Don't be a loner. Follow a few people to fill this empty space, and get inspired instantly!

**Comment by loicginoux** [comment]
with a bit more space and one user: http://awesomescreenshot.com/0f5ww6456

**Comment by jdaudier** [comment]
What if we made "Follow a few people" not a link and add a button below instead to draw more attention?

The button can be orange perhaps with the text: Who can I follow?

**Comment by loicginoux** [comment]
you prefer it like this? http://awesomescreenshot.com/04fwz85d2

**Comment by jdaudier** [comment]
yes!!

**Comment by loicginoux** [comment]
in testing with the button added.

**Comment by jdaudier** [comment]
Text suggestion:

OLD: Don't be a loner. Follow a few people to fill this empty space, and get inspired instantly!

NEW: Don't be a loner. Follow a few people to fill this empty space, and get inspired instantly by clicking on their profile photos!

**Comment by loicginoux** [comment]
closing as this is done
