### ISSUE TITLE
2 more sign-up questions

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#266]
Add 2 more sign-up questions after "What is your goal in joining this challenge?":

1) What kind of diet are you on?
Low carb
Weight Watchers
Jenny Craig
Nutrisystem
Paleo
Vegetarian
Vegan
Volumetrics
Raw foods
Other
I eat everything

2) Describe yourself and your eating habits in one sentence, so other Rubixsters can decide whether to follow you or not

**Comment by jdaudier** [comment]
And the data from the 2 questions can show up on Team Rubix page

![filter](https://f.cloud.github.com/assets/1666031/139058/b68f4b7a-71da-11e2-82c1-cfec23df83a8.png)

**Comment by loicginoux** [comment]
so your responses from "What kind of diet are you on?" will be used as filter in the drop down, right?

**Comment by jdaudier** [comment]
Right

**Comment by jdaudier** [comment]
For question 2, we should make a character limit since there's limited space. Would it be hard to add a character limit count down like Twitter?

**Comment by loicginoux** [comment]
Ok I will see how much space and letters can be put in there, I will see what I can do, I will have to redesign it a bit anyway to include the "goal" under the username and the description. I will show you that before continuing.

**Comment by jdaudier** [comment]
I was thinking we don't need to show the goal on Team Rubix page.  I think goal should be private perhaps in case people are sensitive about that?

**Comment by jdaudier** [comment]
If we agree not to show goal but to use it for coaching purposes, we might want to update this question during sign-up.

OLD: What is your goal in joining this challenge?

NEW: What is your goal in joining this challenge (this will be kept private)?

**Comment by loicginoux** [comment]
I don't like all these questions on the register form :( 
every field that is on the register form should respond yes to this question: "Is it essential for the user to answer this field to start using this site?"
If it's no to this question then, this should go somewhere else in the site:
example:
username => yes
password => yes
goal => no
coaching habits => no
diet => no
eating habits => no

What I propose is to ask for eating habits and diet the first time you go on the team rubix page, explaining something like: "To connect to each other more easily, provide us with the following: your diet? your eating habits?
this will appear on your public profile, etc.."

concerning the goal and your coaching level, maybe the second time you login, a popup appear saying something like: "Need any help? we have a personal coach here to help you, just let him now what is your goal and how much coaching advises do you want from him. This will stay private and help him on his advises."

You see my point?

**Comment by jdaudier** [comment]
username => yes
password => yes
diet => yes
eating habits => yes

I think diet and eating habits are useful since they're gonna be used as filters for Team Rubix page.  I feel like these 2 questions will be easy to fill out and not take too much time.

For the goal and coaching intensity, maybe we can have a pop-up when they first log in to ask for that? Thoughts?

**Comment by jdaudier** [comment]
One other thought, maybe after someone signs in for the first time, we throw them straight to the Settings page and add some instructions about the fields they should fill out: set their goal, upload a profile photo, set daily calorie goal and coaching intensity. Thoughts?

**Comment by loicginoux** [comment]
I prefer the first proposition:
- diet and eating habits in form. 
-  goal and coaching intensity when first entering the app.
  If we do it this way, we need to change the "TIP" box about the calories limit then. We can't have 2 popup box when first entering the app. 

What about having the calories limit popup after your first upload of photo?

**Comment by jdaudier** [comment]
OK - diet and eating habits in form.

Can you tell me the text of the current "TIP" box?  I can modify it to include goal and coaching intensity.

I think we should still make this text change under Settings:
OLD: What is your goal in joining this challenge?
NEW: What is your goal in joining this challenge (this will be kept private)?

**Comment by jdaudier** [comment]
Regarding this idea: What about having the calories limit popup after your first upload of photo?

Will this still work if user sends in a photo by phone?

**Comment by loicginoux** [comment]
-  TIP text: "Visit the Settings menu to set up your daily calorie goal and enable Facebook sharing. Do it now before you forget!"
- I changed locally the text, it will be available soon: "What is your goal in joining this challenge (this will be kept private)?"
- if they do the first upload with their phone, I will show this popup the first time they go to their diary page

**Comment by jdaudier** [comment]
How's this?

TIP! Visit the Settings menu to enter your goal, set your daily calorie limit and coaching intensity, and enable Facebook sharing. Do it now before you forget!

**Comment by jdaudier** [comment]
Can you show me what users will see for: calories limit popup after your first upload of photo?

**Comment by jdaudier** [comment]
I think this might be better. Note that we should updated the Leaderboard calculation pop-up to add the goal & coaching intensity points.

TIP! Visit the Settings menu to enter your goal (5 pts.), set your daily calorie limit (5 pts.) and coaching intensity (5 pts.), and enable Facebook sharing (10 pts.). Do it now before you forget!

**Comment by loicginoux** [comment]
I agree it's better if we show the points.

**Comment by jdaudier** [comment]
I don't think this is live yet under Profile and Sign Up pages: What is your goal in joining this challenge? (this will be kept private)

I did see it under Coaching Intensity though.

**Comment by loicginoux** [comment]
I am working on this now, but just thinking about the screenshot on [this comment](https://github.com/loicginoux/joanne_project/issues/266#issuecomment-13284643).
Now that I added the month winner ribbons, there  isn't much space to add the text next to the username...
We may have to redesign how to display a user in the team rubix page, what do you think?

**Comment by loicginoux** [comment]
So to summarize the work to do on this:
- add diet and eating habits in form + settings page
- add a character limit count down for eating habits.
- remove goal and coaching intensity from register form but keep it in settings page
- add a dropdown in leaderboards to filter by diet.
- add eating habits and diet for a user in the leaderboard tables (this includes redesigning as we now have also winner ribbons, you agree with that?)
- add goal and coaching intensity points, 5 points each (in popup + algo to add/remove points + add them when resettings monthly).
- change text: "What is your goal in joining this challenge (this will be kept private)?"
- change TIP text: "TIP! Visit the Settings menu to enter your goal (5 pts.), set your daily calorie limit (5 pts.) and coaching intensity (5 pts.), and enable Facebook sharing (10 pts.). Do it now before you forget!"

**Comment by jdaudier** [comment]
That seems correct.  My only concern is that once we remove goal and coaching intensity from register form that people won't fill them out.  Thoughts?  

Maybe we can leave coaching intensity during sign-up form since it's easy to click the buttons.  And just move goal to Settings since that might take longer to fill out.

**Comment by loicginoux** [comment]
Ok I keep coaching intensity in register form. another thing: http://awesomescreenshot.com/0d3y3qse6

**Comment by jdaudier** [comment]
I think we can leave Goal under Profile and create a new tab called Eating Habits (below Coaching Intensity) for the diet drop down and eating habits.

Just a note to capitalize Rubixsters in this sentence: Describe yourself and your eating habits in one sentence, so other Rubixsters can decide whether to follow you or not.

**Comment by jdaudier** [comment]
Updated text as inspired by Flud app.

OLD: Describe yourself and your eating habits in one sentence, so other Rubixsters can decide whether to follow you or not.

NEW: Describe yourself and your eating habits in one sentence, so other Rubixsters can decide whether to follow you or not.

ex: "40-yr old mom, struggling with juggling so much and eating healthy, especially at night."

![Flud](https://f.cloud.github.com/assets/1666031/171222/d63d2384-7a90-11e2-9be1-7d91700a50de.png)

**Comment by loicginoux** [comment]
about the filter in the team rubix page:
![Screen Shot 2013-02-21 at 19 43 17](https://f.cloud.github.com/assets/824936/181693/b6cc203c-7c56-11e2-851a-57861764e7c7.png)

Let me know if this is fine:
- I added "filter by diets..." that will be the default value of the selectbox. If going to another diet and coming back to this option, It will reload all users (i.e. without fiktering by diets)
- I added an option "All diets", in case people select a diet and want to come back to see all people without filtering by diets, they can choose "All Diets" (which would be equivalent to selecting "Filter by diets...")

I will now see how I can change the desing to integrate nicely the diet and introduction phrase into the user line.

**Comment by jdaudier** [comment]
Can the heading of the filter be just "Filter by" so the font can be more readable?

Low carb should have lowercase "c"

**Comment by jdaudier** [comment]
One solution could be to make the 2 columns wider but will that be too wide for most users' screens?

**Comment by loicginoux** [comment]
The font is the same as on the rest of the app, I guess it's because of the photo, I leave it like this for now until you try it directly on the app and let me know if you still think it's not readable.
I am trying something different for design based on this [twitter page](https://twitter.com/who_to_follow/suggestions), I will show you how it looks.

**Comment by loicginoux** [comment]
What do you think of this design?
http://awesomescreenshot.com/07cyp8626

**Comment by jdaudier** [comment]
Looks good as long as first letter of username is capitalized.

**Comment by jdaudier** [comment]
Were you able to change this? Low carb should have lowercase "c"

**Comment by loicginoux** [comment]
I changed low carb and I will capitalize username

**Comment by loicginoux** [comment]
Now that the coaching intensity is directly in the register page, everyone will have it set, so should we still add points for setting this coaching intensity?
Also another thing, I realised while deploying on  testing site.  Already existing users won't have any diet nor introduction sentence set (see the team rubix page on testing site). Is that a problem?

**Comment by jdaudier** [comment]
I can send an email to ask everyone to set their diet, bio, and coaching intensity.  And then give them points once they do that?

**Comment by loicginoux** [comment]
Ok so we keep as we said about attributing points for these settings.

**Comment by jdaudier** [comment]
How's this feature coming along

**Comment by loicginoux** [comment]
I think the last update on this is already on staging site. I have been working on the performance feature recently. If I remember well, I need to add the points system associated to this 2 fields.

**Comment by jdaudier** [comment]
Can you change the single quotes to double quotes? Applies to sign up page as well.

ex: "40-yr old mom, struggling with juggling so much and eating healthy, especially at night."

**Comment by jdaudier** [comment]
Since coaching intensity is required during sign-up, let's not add points for that. So we'll only add 5 points for setting a goal only.

For the pop-up, we can add this line above "Setting daily calorie goal":

Entering your goal*

change TIP text to:

TIP! Visit the Settings menu to enter your goal (5 pts.), set your daily calorie limit (5 pts.), add a profile photo (5 pts.), and enable Facebook sharing (10 pts.). Do it now before you forget!

**Comment by jdaudier** [comment]
Can we update the "40-yr old" sentence and reconfigure the Leaderboard points by next Fri? I wanna push this to the live site soon to test before April 1. Thanks!

**Comment by loicginoux** [comment]
Yes, I work on that now.

**Comment by loicginoux** [comment]
It looks like it's working on staging site with last changes and points added when goal is filled. You can have a look.

**Comment by jdaudier** [comment]
Can you send me a screenshot of the TIP pop-up so I don't have to create a new account?

**Comment by jdaudier** [comment]
Suggestion

![2013-03-11_1026](https://f.cloud.github.com/assets/1666031/244881/14d99f60-8a71-11e2-8ab8-18dcd8089207.png)

**Comment by loicginoux** [comment]
ok I will do this when I test the user registration process next time.

**Comment by loicginoux** [comment]
here it is: http://awesomescreenshot.com/076116hx59

**Comment by jdaudier** [comment]
looks good!
