### ISSUE TITLE
Profile photo blurry

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#267]
I noticed the profile photo default image is blurry, I will send you a 200x200 SVG file.  Maybe that'll help.
![profile](https://f.cloud.github.com/assets/1666031/139200/87c61d1a-71e3-11e2-82a6-943c7c4dc3b1.png)

**Comment by loicginoux** [comment]
ok

**Comment by loicginoux** [comment]
did you send me this photo or do you want me to do it?

**Comment by jdaudier** [comment]
resent via email
