### ISSUE TITLE
Admin panel broken

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#269]
I couldn't get to this link to delete a user:
http://www.foodrubix.com/admin/users

**Comment by loicginoux** [comment]
I will check this

**Comment by loicginoux** [comment]
working now. this new user "tnurabeb1970" didn't have his preferences created for a reason I couldn't find. I created his preferences but it might happen again.

**Comment by loicginoux** [comment]
creating a new user worked fine for me...

**Comment by jdaudier** [comment]
which preferences?

**Comment by loicginoux** [comment]
this is where I keep all preferences for users. It includes the coaching intensity, the facebook sharing, if the user wants to receive daily and weekly emails, etc...
In the database, One table is to store users, and one table is to store preferences. and each user is attached to one row of the preference table.
What happened here is that it created the user in the "User" table with creating the associated row in the "Preference" table.

**Comment by jdaudier** [comment]
Do we add validation to make sure that users have to choose something for:

What level of coaching intensity would suit you the best?

**Comment by jdaudier** [comment]
Do you know how I can see the goals of each user in admin panel?

**Comment by loicginoux** [comment]
By default, coaching intensity is "low", and about the goal, it is not mandatory to fill it. I will add the description of the goal when viewing a user in the admin panel.
