### ISSUE TITLE
iPhone 4s cannot copy photos or upload

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#271]
Jane B reported today:
I cannot drag and copy pictures on my iPhone 4s or upload from within the program.

**Comment by loicginoux** [comment]
this is two things different:
- cannot drag and copy => because this is not done for mobile as he cannot press ctrl or cmd. this is not a bug. copy and moving by dragging is not supported in mobile.
- cannot upload => this is probably [this issue](https://github.com/loicginoux/joanne_project/issues/188#issuecomment-12235028).

**Comment by jdaudier** [comment]
She tried the suggestion but said "photos" does not show up as an option under "privacy"

**Comment by loicginoux** [comment]
I have "photos" under settings>privacy on my iphone 4s!

**Comment by jdaudier** [comment]
Jane said: I have looked there and it's not an option to turn on or off.

**Comment by loicginoux** [comment]
it must something about the iOS version... I can continue to investigate but I don't think this is something about the app

**Comment by jdaudier** [comment]
I'll find out her iOS version. Since she can't upload, that's not good.

**Comment by loicginoux** [comment]
Ask her if she can test uploading a photo using the same browser app (safari, chrome, etc...) on a service like facebook, instagram or others. 
If she can upload a picture to these sites, our app will be the problem, if she has the same issue, that will be her phone's problem.

**Comment by jdaudier** [comment]
She is using iOS 6.0.1

Jane said today:
I finally got it to upload from within the program, but it took 5 minutes. The others do so in 10 seconds or less.

**Comment by loicginoux** [comment]
this is a performance issue then.
