### ISSUE TITLE
Email recap text update

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#276]
Can we make this minor text change on the Email Recap page?

OLD: Do you want to receive emails to remind you what you have been eating?

NEW: Do you want to receive emails to remind you what you have been eating? (Recommended because you'll become more aware of how many calories you ate for the day, and find out if you've won a Smart Choice or Hot Photo Award)

**Comment by loicginoux** [comment]
in staging site now.

**Comment by jdaudier** [comment]
Can we do this? https://github.com/loicginoux/joanne_project/issues/288

**Comment by loicginoux** [comment]
in live site now.
