### ISSUE TITLE
Hours ago off in Feed page

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#279]
I noticed that the "hours ago" is off in the Feed page.  I just uploaded a batch of photos and some say 8, 9 or 19 hours ago

![2013-02-21_2240](https://f.cloud.github.com/assets/1666031/183828/c287f518-7cba-11e2-986f-5415ae8586c9.png)

**Comment by loicginoux** [comment]
For the first photo, is the upload time "02-21-2013 12:00 pm" correct? this is what I see displayed in this page:
http://www.foodrubix.com/data_points/3975

**Comment by jdaudier** [comment]
I uploaded late at night maybe around 10pm but I ate it for lunch so I put 12pm as the time.

**Comment by loicginoux** [comment]
So to clarify, is the problem from the time you added on the photo or the function that calculate the "X hours ago" from this time?

**Comment by jdaudier** [comment]
The function that calculates the "X hours ago".  I think if I upload around 10pm and set it to 12pm, should it take the time from 12pm?  So it's how long ago did you eat the food.

**Comment by loicginoux** [comment]
The function "X hours ago" is based not on the time you actually uploaded the photo but on the time you ate it, i.e. the time you added to the photo. So in this case it calculates it depending on 12pm.

**Comment by jdaudier** [comment]
Right and it's not calculating correctly then

**Comment by loicginoux** [comment]
Hi Joanne,
I will close this. let me know if you still encounter the issue. It is now calculated in the client side and not on the server side, that might have fixed the problem. 
Unfortunately I can't properly test it as I didn't manage to replicate it. Just keep an eye on it and let me know if you see it again

**Comment by jdaudier** [comment]
This photo was taken 1.5 hours ago but on the feed it says 8 hours ago.

http://www.foodrubix.com/data_points/4363

**Comment by loicginoux** [comment]
I tried something different, can you try again and let me know. Thanks.

**Comment by jdaudier** [comment]
Seems to be working now

**Comment by jdaudier** [comment]
When a user in a different time zone from me uploads a photo, when I see their photo, is the time in their time zone?  For example, Chrissy in Canada eats a banana at 10pm, will I see that as a photo at 10pm, not 7pm?

**Comment by loicginoux** [comment]
you will see it in their local time. So in your example at 10pm.
