### ISSUE TITLE
Time bug 2

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#28]
When trying to update the data point, the time was not shown in 12 hours with AM/PM.

http://screencast.com/t/Y4wPhHr6n

**Comment by loicginoux** [comment]
fixed locally

**Comment by jdaudier** [comment]
Could you push to Heroku so I can test this?  Right now I see this still: http://www.diigo.com/item/image/2yj1s/hgyw

**Comment by loicginoux** [comment]
Sorry, I don't understand.
In your screenshot I see 00:36 AM in the input field for time, is that not what you wanted? I changed the format from 0-24h to 0-12 AM/PM.

**Comment by jdaudier** [comment]
I think it should say 01:36 AM instead like what you see when you click on the dropdown menu.

**Comment by loicginoux** [comment]
well.. the time 01:36 AM is different from 00:36 AM, no?
I  think what is the problem is that 00:36AM should actually be 12:36AM.

**Comment by jdaudier** [comment]
Right - something to replace the 00.

**Comment by loicginoux** [comment]
I will try to change it by 12:36AM

**Comment by loicginoux** [comment]
Ok, that was a bug on the library Date.js that I am using, I updated the library with the most recent one.

**Comment by loicginoux** [comment]
I pushed that on heroku, Can you review and close the issue if it's ok? 
thx

**Comment by jdaudier** [comment]
Looks like this is fixed.
