### ISSUE TITLE
check S3 security 

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#280]
Dear Amazon S3 Customer,

> We’ve noticed that your Amazon S3 account has a bucket with permissions configured to allow anonymous requestors to perform READ operations. As a result, anonymous requestors can list objects in your bucket. The following Amazon S3 buckets grant anonymous access:
> 
> Amazon S3 Buckets:
> foodrubix-production
> foodrubix-testing
> 
> Amazon S3 buckets are private by default. We know some customers prefer to allow anonymous access to simplify development against S3. Bucket READ access, sometimes referred to as "LIST" access, allows anyone to get a complete list of your bucket content. Bucket READ access does not grant permissions to read contents of an object. However, a list of object names can often provide more information than necessary to the public. Some tools and scripts have emerged which scan services like Amazon S3 and identify objects in publicly listable buckets. The use of these tools against your buckets may also produce unintended charges in your account.
> 
> Unless your bucket is configured for serving public static websites, we recommend against anonymous access. To remove anonymous access to your bucket, open the Amazon S3 Management Console at http://console.aws.amazon.com/s3, and follow these simple steps:
> 
> 1) Click on your bucket, and select Properties.
> 
> 2) In the Properties pane, click Permissions. The Permissions pane shows a list of grants, one row per grant, in the bucket ACL. Each row identifies the grantee and the permissions granted.
> 
> 3) Select the row that grants permission to “Everyone”. Click “x” to delete the row. This removes all permissions granted to anonymous requestors. Click “Save”.
> 
> Learn more about protecting your bucket by reading the AWS article on Amazon S3 Bucket Public Access Considerations at http://aws.amazon.com/articles/5050. This article includes alternative options for enabling unauthenticated end users to read and write content. For additional information on managing Amazon S3 permissions, please visit the Amazon S3 Developer Guide at http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAuthAccess.html.

**Comment by jdaudier** [comment]
Can we fix this soon?

**Comment by loicginoux** [comment]
Yes I tried to do as much as I can but the performance stuff takes time to make it works correctly.
If you prefer me to work on this issue before performance sutff let me know. if not, I will finish the work I have left before working on this, i.e. perf issue and  #266

**Comment by jdaudier** [comment]
Sounds good - performance, #266, and then this one.

**Comment by loicginoux** [comment]
done, that wasn't what I think it was and it only took two minutes. It should be fine now
