### ISSUE TITLE
Leaderboard bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#287]
http://www.foodrubix.com/ennekube 

Ennekube was tied with Chrrisy at 174 pt. I liked 2 of her photos and that made her point go up to 178.  However, she also won Smart Choice Award but that didn't get added to her board.

Her total should be 183

**Comment by loicginoux** [comment]
I will have a look in logs. Can you tell me for which photo did you add the award?
Thanks

**Comment by jdaudier** [comment]
Sushi photo from Thur: http://www.foodrubix.com/ennekube

**Comment by loicginoux** [comment]
what was your date and time when you attributed this award?

**Comment by jdaudier** [comment]
I think last night around midnight or so

**Comment by loicginoux** [comment]
Isn't it because the time of the photo is on february while the time you attributed the award was on march?
If this is the case, this would be normal as points wouldn't be added to the monthly leaderboard (march) but only on the total leaderboard as we discussed on a previous thread. 
Also I can see in logs that when you added the awards, points were added to the total leaderboard but not to the monthly one.

**Comment by jdaudier** [comment]
Is there a way for you to see when the award was given? I can't remember the exact time.

**Comment by jdaudier** [comment]
The points should've went somewhere though... I think I gave the award before midnight.

**Comment by jdaudier** [comment]
If I did award it in March, should it go on the Monthly Leaderboard for March?

**Comment by loicginoux** [comment]
For your last question, at the moment, points are only added to total leaderboard. I don't think it should go to the current monthly leaderboard, it doesn't make much sense for me...

This is the line from the log that says when you added the award:

```
2013-03-01 07:23:16+00:00 app web.1     - - 5 points added to ennekube, pass from 178 to 178 points (total: from 184 to 189)
```

So at 7:30 GMT which makes it for you 2013-02-27 11:30 pm. So here is the problem, it calculated that we were on the new month based on the server local time (GMT). Now the thing is that, at the moment, I can't calculate it based on your local time when you are doing this on the admin panel. What I will do is to calculate if we are on the new month based on the timezone of the owner of the photo. That would be a bit more accurate than currently but we will still have some corner cases where we will have a problem.
Anyway this is a problem that will appear only during few hours at the end of each month, when the server is already on the new month while you are still on the previous month.

I do the change now, close this if you are satisfy with the answer.

**Comment by jdaudier** [comment]
ok sounds good

**Comment by jdaudier** [comment]
So it will be based on the timezone of the owner of the photo?  Meaning, if it's before midnight in the photo owner's time zone and I award them, the points will count for this month.

**Comment by loicginoux** [comment]
Yes I will make changes so that points get added to the monthly leaderbaord based on user's timezone.

**Comment by jdaudier** [comment]
is it the user's timezone when I award?  not related to the photo upload time in user timezone, correct?

**Comment by loicginoux** [comment]
Should we close this one as the implementation for the points system has changed. We will re-open or create a new one  if it's happening again. Is that ok?
