### ISSUE TITLE
Email recap text

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#288]
Can we change it from:

Do you want to receive emails to remind you what you have been eating? (Recommended because you'll become more aware of how many calories you ate for the day and it's the easiest way to see if you've won a Smart Choice or Hot Photo Award)

to: (added a line of space)

Do you want to receive emails to remind you what you have been eating? 

(Recommended because you'll become more aware of how many calories you ate for the day and it's the easiest way to see if you've won a Smart Choice or Hot Photo Award)

**Comment by loicginoux** [comment]
this is done, just need to be pushed

**Comment by loicginoux** [comment]
in live site
