### ISSUE TITLE
question about "0 likes 0 comments"

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#290]
Don't you think we should hide "likes" or "comments" when there is none?
http://awesomescreenshot.com/0d611c9ga7

We could only display it when there is more than 1...
Not a big deal but leaving this on the page doesn't bring any more info to the page, I think.

**Comment by jdaudier** [comment]
Agreed - hide when there are no likes or comments and unhide when there is 1 or more

**Comment by loicginoux** [comment]
done and deployed
