### ISSUE TITLE
Repeat photos

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#291]
There were a few repeat photos yesterday:

Is there a way to tell if it's our issue?

http://www.foodrubix.com/data_points/4214

http://www.foodrubix.com/data_points/4218

**Comment by loicginoux** [comment]
I don't see anything wrong with the app.
Mailgun received twice these emails so the app created twice the photos.
In my opinion, if there is a problem it's happening before it reaches the app.
The thing I don't understand is that the first doublon email has been received with 1 minute difference between each photo and in the second case, emails have been received with 11 hours difference...
