### ISSUE TITLE
Header thick

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#297]
At around 11:10pm tonight, I saw this when I went to FoodRubix. Refreshed the page and it was fixed.  It happened several times.

![2013-03-14_11-10pm](https://f.cloud.github.com/assets/1666031/262520/8169658e-8d37-11e2-8a83-03ae53a7c1e8.png)

**Comment by jdaudier** [comment]
Here's video. You'll see me refreshing the page.
http://screencast.com/t/hf93bURuHhPT

**Comment by loicginoux** [comment]
it should be better now
