### ISSUE TITLE
Move photo bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#302]
I moved this photo to Sat Mar 16 but it still shows up on Sun as a repeat
![2013-03-17_0019](https://f.cloud.github.com/assets/1666031/267833/e98fc9e0-8ed2-11e2-921b-127674aed221.png)

**Comment by jdaudier** [comment]
I'm trying to upload a photo via the browser and it's stuck at the progress bar. I'm not sure if it's my internet or the site. Can you check that as well?

**Comment by loicginoux** [comment]
I can upload now, do you still have the problem?
concerning the photo, I see what's wrong, this is a caching issue. I should delete the cache for the current week view as well. This will only happen if you move the photo from a week to another or for a month to another. 
I will correct that soon.

**Comment by loicginoux** [comment]
Ok fixed, that will be pushed shortly

**Comment by jdaudier** [comment]
The pineapple photo on Sunday, I can't seem to delete it. Can you?

**Comment by jdaudier** [comment]
I still have issues uploading - it's stuck at progress bar. Are you able to upload via browser?

**Comment by loicginoux** [comment]
Your photo is actually on Saturday and it has surely been deleted. what remains is the HTML cached to render your view. I will delete it now.
Concerning your upload, I receive again your error in the logs, but doesn't seem to happen to others. I will check what  is going on there.

**Comment by jdaudier** [comment]
Yea... still can't upload. Odd...

**Comment by loicginoux** [comment]
I close this one but opened a new one for the upload issue #305
