### ISSUE TITLE
Weekly email recap

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#307]
What happened to our weekly email recap? I feel like I haven't gotten it in a while.

**Comment by loicginoux** [comment]
Yes. IT was a bug. It should be ok now, there were an issue where it was running a function at 10am everyday but the function was only sending email if it was 7am for the user.
We Should have it ok on Monday.

**Comment by jdaudier** [comment]
Is there a test we can write or something that we can set up to alert us when the recap emails are not going out?

**Comment by loicginoux** [comment]
This particular error was something that can't be tested. It was some
configuration in heroku.

**Comment by jdaudier** [comment]
Are there any tools that will alert us when the emails don't go out?

**Comment by loicginoux** [comment]
I will have a look but I don't think so...

**Comment by loicginoux** [comment]
There were an error while sending the weekly email and it was stopping the process, we received them, the last 2 weeks If I remember.
I close this.
