### ISSUE TITLE
Upload bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#308]
Sometimes when I try to upload an image, it'll be stuck at the progress bar.  It happened a couple of times before but it happened today around 7:40pm when I tried to upload this photo.

![IMAG2463](https://f.cloud.github.com/assets/1666031/322753/e570db52-9a75-11e2-8847-37e4864466d2.jpg)

**Comment by loicginoux** [comment]
HI, I saw that... The server close the connection when a task takes more than 30sec to do a task. I haven't found yet how to correct that and I need to try few different things.

**Comment by loicginoux** [comment]
I don't see this error in logs anymore since the few changes. Can we close this or do you still have issues?
