### ISSUE TITLE
Feed comment red

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#309]
When I enter comments on the Feed page using Firefox, sometimes the feed box is outlined in red instead of blue. Do you know why?
![FR Comment Color Bug](https://f.cloud.github.com/assets/1666031/337886/c4c499f0-9cf7-11e2-8cbb-2c04eefbb177.png)

**Comment by loicginoux** [comment]
I will see what's going on, I noticed that few times as well.

**Comment by loicginoux** [comment]
I don't know the steps to replicate this, can't find how this is happening. Do you know how to replicate this?

**Comment by jdaudier** [comment]
We saw the red highlight in Firefox.

**Comment by loicginoux** [comment]
Do you remember the steps you did exactly to makes it red? Could you replicate it? I still can't do it in Firefox, even if I tried different things.

**Comment by jdaudier** [comment]
Couldn't replicate either.  Will reopen if I can.
