### ISSUE TITLE
Mailgun code

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#31]
Add Joanne's Mailgun code to see if user can send a photo attachment from email with calorie as subject line and have that added to their account automatically.

**Comment by loicginoux** [comment]
ok so just to be clear about the feature:
- user send email to  pic@foodrubix.mailgun.org
- subject: a number
- attached file: a photo of your meal

it should add the meal to the user account associated to the email address that send the picture.

what about validation: if the subject is not a number? if there is no photo or the file is not an image? if the email is not linked to any user account?

can you email me the mailgun login details just if I need to change configuration stuff.

**Comment by jdaudier** [comment]
In my code, I have some validation but not everything.

  #Match sender email to user of the app

```
  current_user = User.find_by_email params["sender"]
  #ap current_user

  #If user entered calories as an integer and they're an existing user of the app

  if params["Subject"].to_i.to_s == params["Subject"] && current_user
```

**Comment by jdaudier** [comment]
Mailgun login:

email: joanne_hwang1223@hotmail.com
pwd: foodrubix

**Comment by jdaudier** [comment]
I also wonder if it'll be easier to do the same thing through the Zapier API: https://zapier.com/developer/

**Comment by loicginoux** [comment]
Ok I added that feature, but few things to note:
- I need to add a validation to have unique email adress, if two users share the same address, this feature won't work (as you could attach a file to the other user sharing the adress)
- I changed the whole email system to use mailgun, so emails sent by the system are sent by mailgun.
- do you want to receive an email to confirm that the file has been added to your account?

At least now, you should be able to upload from your email address :)

**Comment by jdaudier** [comment]
I tried sending a photo to pic@foodrubix.mailgun.org from my phone (jdaudier@outlook.com email) with 500 as the subject and it didn't show up

**Comment by loicginoux** [comment]
That's because  your email is not associated with your account, you need to use joanne_hwang1223@hotmail.com

**Comment by jdaudier** [comment]
My account is jdaudier@outlook.com (I changed it in Settings awhile back)

**Comment by loicginoux** [comment]
ok, I will have to investigate more then...

**Comment by jdaudier** [comment]
Did you try sending a photo from a phone?

**Comment by loicginoux** [comment]
no... I will try if I can do it from a phone, but do you mean that it works with a computer but not with the phone?

**Comment by jdaudier** [comment]
I will try from a computer - haven't tried that yet

**Comment by loicginoux** [comment]
when did you try that? because from the logs of mailgun, I couldn't see any mail received from  jdaudier@outlook.com
can you try now to see if I can track the email and see where it stops?
