### ISSUE TITLE
Stats for Daily Email

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#310]
Can we add something like this for the daily email?  Check www.codecademy.com to see it.

Points chart for: 
YESTERDAY
BEST (most points earned in 1 day) 
TOTAL (points earned for the month)

Streaks:
Days in a row you've posted photos
Personal best streak

![pts](https://f.cloud.github.com/assets/1666031/355770/c2cb16d4-a0ed-11e2-87c2-14119b362376.png)

**Comment by jdaudier** [comment]
And a progress bar for the week. Each day will light up when you've posted a photo.
Text can say: You've posted photos X days out of the 7. 

Progress bar can look something like this...
![Sun](https://f.cloud.github.com/assets/1666031/355793/5c33f466-a0ef-11e2-88fa-72beef10e067.png)

This is how Codecademy does it:
![streaks](https://f.cloud.github.com/assets/1666031/355794/7275ec8e-a0ef-11e2-9af0-48b4f5e1591b.png)

**Comment by loicginoux** [comment]
Hi,
Ok I would have to rework the way I calculate points. At the moment, points is just a field in the user table in the database. I will need to create a model Point, to be able to store the date points get added. This will allow to manipulate points more easily.

**Comment by jdaudier** [comment]
Do you think that'll be complicated?

**Comment by loicginoux** [comment]
This is the feature you want as soon as possible, right?
We need to define a bit more what you want. I am ok with the part about the points but don't you think that the streaks and the progress bar bring the same information twice?
Also where should we put this in the email?

**Comment by jdaudier** [comment]
Yes.  The streaks is a bit different from the progress bar because the bar looks at it from a weekly point of view.  And for streaks, you can have a 13 day streak for example.

I think we can put this either at the very top starting with the progress bar perhaps, followed by streaks, then points.  What do you think?

**Comment by loicginoux** [comment]
Ok, I will add that on top. Do you prefer me to work on the few bugs that come up first or this?

**Comment by jdaudier** [comment]
Bugs first please

**Comment by loicginoux** [comment]
Ok I work on them now

**Comment by loicginoux** [comment]
I finished bugs for now, I am working on that.

**Comment by loicginoux** [comment]
FYI, streaks will be calculated at midnight for each user's local time. at this time, I will see if a photo has been uploaded for the day and readjust streak and best streak.
Said this, note that if a photos is edited and his time changed to a previous day, streaks will not be updated as it will have already been calculated.

**Comment by jdaudier** [comment]
If I only uploaded 1 photo today and set is as yesterday's photo, it won't count in my streak for today.  Did I understand it correctly?

**Comment by loicginoux** [comment]
just to have our minds clear, a photo contains 3 date fields:
- "created_at": creation date
- "updated_at": date of last update
- "uploaded_at": the date we use and display in the app that can be different from the creation date.

Now, your comment made me think. I was going to use the "uploaded_at" date to calculate streaks but as your suggested, It might be more accurate to calculate streaks based on "created_at" date. This way, in your example: 

"If I only uploaded 1 photo today and set is as yesterday's photo,"

It will count on your streak for today and not for yesterday.

Is that clearer?

**Comment by loicginoux** [comment]
another thing about points, The best points earned in a day will start only from the date I put that live. I won't be able to calculate it for the past days as I currently can't tell when points have been awarded.

**Comment by jdaudier** [comment]
OK makes sense to calculate streaks based on "created_at" date.  So as long as you upload a photo today, it doesn't matter which day you set it as.

Agreed regarding most points earned in a day.

**Comment by loicginoux** [comment]
I will also update the app with this changes just before the end of the month. I do this because when I will update, the monthly leaderboard points will be wrong and be equal to the total leadeboard points. When the next month starts , monthly points will be calculated as before.

**Comment by jdaudier** [comment]
The heading for this new email section can be: Your stats

**Comment by loicginoux** [comment]
was the progress bar in an email or in a webpage? Could I access the page or could you forward me the email to inspect the code? 
I am saying that because f you want it this way I will probably need the images? I could redo it in photoshop but that would be longer.

**Comment by jdaudier** [comment]
Which progress bar? I have 2 examples above.

**Comment by loicginoux** [comment]
I was thinking of using the first one with the days. I will light up the previous day you've posted photos. I don't really think the second one fit in to display days you've uploaded photos.

**Comment by loicginoux** [comment]
I have this at the moment, but I would like to add images to the progress bar if possible.
http://awesomescreenshot.com/03716r1n79

**Comment by jdaudier** [comment]
Add images to the progress bar? Can you explain?

Above the bar, can we add this text: You've posted photos X days out of 7.

For the first box under points, should it say: YESTERDAY

**Comment by loicginoux** [comment]
- I mean that the colors for the progress bar are quite simple at the moment (only a background color for each day) compared to the fancy example you have above. I wanted to make it nicer and add images taken from the example above. But if you think that mine is fine, we can also leave it like that and not spend more time making it nicer... as you prefer!
- ok
- ok

**Comment by jdaudier** [comment]
Oh I see. I just have the illustrator files for the images. That probably won't help you, right? 

I'm super excited about these new stat features.

**Comment by jdaudier** [comment]
One idea if you want to try is... adding a circle inside the orange square kinda like the FoodRubix logo. So the letter will be surrounded by a lighter orange circle and the square orange can be darker to match logo.

**Comment by loicginoux** [comment]
Yes that will do with the illustrator file. If you ok to make it fancier, just send me the file and I will extract the images and add it to the progress bar.

**Comment by jdaudier** [comment]
Do you think we should try using the orange logo part so it looks like a little camera for each day?

**Comment by jdaudier** [comment]
I guess we can keep it simple for now and leave it like how to have it. And we can make it fancier later.

**Comment by loicginoux** [comment]
Ok I leave it like this for now.
Another question about the progress bar. Is it based on the date "created_at" or "uploaded_at"? Said in another way,
does a day light up when you sent a photo or when you have a photo displayed in your diary for this day?
I would say based on the fact that you sent a photo to the app ("created_at"), so that it corresponds with the streaks.

**Comment by jdaudier** [comment]
Agreed.

**Comment by loicginoux** [comment]
Hello Joanne,
I have deployed this changes on the testing server. I will leave it there for few days, time to test that emails content are correct. You should activate your daily email on the testing server to check it as well.
The whole point system has changed as well so you now have a way to track points [in the admin panel](http://calm-gorge-1213.herokuapp.com/admin/points).

**Comment by jdaudier** [comment]
Does that mean I have to post images on the staging site for the email stats to work?

**Comment by loicginoux** [comment]
no it will work but you won't have any light in the progress bar neither streaks/points.

**Comment by jdaudier** [comment]
Just to confirm, if I upload photos on Mon and Tue, the progress bar boxes for Mon and Tue will both be lit in orange, correct?

**Comment by loicginoux** [comment]
yes

**Comment by jdaudier** [comment]
I was trying to set a daily calorie goal on the staging site but it says "you can't do that".

**Comment by loicginoux** [comment]
I can't replicate this and can't see what's happening in logs.
- what value did you try to enter?
- which browser and version?
- is it still not working?

**Comment by jdaudier** [comment]
Still not working using the latest Chrome browser. 

Here's a video: http://screencast.com/t/pJGxZj6m6C3

**Comment by jdaudier** [comment]
Can you make the font size bigger for this line?
:-) = You stayed within your daily calorie limit

**Comment by jdaudier** [comment]
When you don't have the daily calorie goal set, the Goal Check section should have the SAMPLE stamp. I think right now it thinks my calorie limit = 0 cal.

![sample](https://f.cloud.github.com/assets/1666031/462954/2b9f8be2-b4fb-11e2-840f-34c8a2186b5c.png)

**Comment by loicginoux** [comment]
On Sunday, we need to display the past week and not the current week on the progress bar.

**Comment by jdaudier** [comment]
Can we add commas here too?
![2013-05-11_1623](https://f.cloud.github.com/assets/1666031/492262/fee45da2-ba91-11e2-8321-a5ed6c4ffd50.png)

**Comment by loicginoux** [comment]
this is done: "On Sunday, we need to display the past week and not the current week on the progress bar."

**Comment by loicginoux** [comment]
timezone issue should be fixed for the progress bar now.

**Comment by jdaudier** [comment]
Can we add some bottom margin below the progress bar?  This is how it look in Outlook.
![2013-05-15_0750](https://f.cloud.github.com/assets/1666031/507593/402b6e0c-bd73-11e2-81cc-a4b5499124d9.png)

**Comment by loicginoux** [comment]
This has been done, correct?
