### ISSUE TITLE
Stats for Weekly Email

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#312]
Instead of showing photos of everything you ate for the week, I'd like to change that to a weekly stats report.

Ideas:

1) A chart with 2 lines one from this week and one from the previous week to compare and text that says:

This week: You stayed within your daily calorie limit of XXXX calories X days out of 7. 
Previous week: You stayed within your daily calorie limit of XXXX calories X days out of 7. 
You did better this week! Good job!
or
Don't give up. Try again next week.

![chart](https://f.cloud.github.com/assets/1666031/355898/ca756820-a0f3-11e2-93b7-170b2e2d6126.png)

2) A chart that graphs the total calories week over week. This way user can see a high-level trend on whether they're eating more calories this week compared to the last week. I think we should chart out 8 weeks of data points in the email.

For the last Sun of each month, the email should include this:
3) This month: You stayed within your daily calorie limit of XXXX calories X days out of XX.
Previous month: You stayed within your daily calorie limit of XXXX calories X days out of XX.

Any other cool stat ideas for reporting? I looked at Google Analytics to give me some dieas.

**Comment by jdaudier** [comment]
The heading for this new email can be: Your stats for the week

**Comment by loicginoux** [comment]
Displaying the charts on the emails is almost impossible. It is so much work that I think it's not worth spending time doing it. I explain why:
INITIAL PROBLEM: Highchart.js uses HTML canvas to render graphics but  HTML canvas are not supported in emails. 

A SOLUTION: Being able to transform and save a chart canvas into a png file in the server and then send the email with this png file like described [here](http://www.highcharts.com/component/content/article/2-news/52-serverside-generated-charts)
PROBLEM: We would need to set up another phantomjs server in heroku to be able to get the png file and being able to communicate and send the file to our app server. I am not sure if all this is possible.

This would require some investigations and tests to see if it's possible but I am really not sure that this would work.

Making this on a webpage and displaying a link in the email is an option but it's not as nice...

**Comment by jdaudier** [comment]
I think we can do the weekly status minus the actual line chart perhaps. Let me think about this.

Would it be hard to have a "COMPARE" button in the weekly view (on the site) that lets you pull up last week's data and compare that against this week's similar to Google Analytics?

**Comment by loicginoux** [comment]
So what the button compare will do/trigger? will it replace the graph? (because the button "previous" will do the same)

**Comment by jdaudier** [comment]
It will draw 2 lines to compare this week with previous week.  Like Google Analytics.
![2013-04-22_0805](https://f.cloud.github.com/assets/1666031/409797/4266396c-ab5e-11e2-9351-6bc66a9d25de.png)

**Comment by loicginoux** [comment]
Ok, this shouldn't be too complicated but what about the month and day views? do you want the the compare button as well?

**Comment by jdaudier** [comment]
Not sure how we can display the difference in day view but it can work for the month view. The only thing with the month view is that the last day stats might be blank for certain months (30 vs 31 days, etc.).

**Comment by jdaudier** [comment]
I moved the compare feature to https://github.com/loicginoux/joanne_project/issues/335

**Comment by jdaudier** [comment]
Here's a mock-up of how I imagine the email to look. Is it possible to do the last chart? If not, I can convert it to just data but the chart makes it so much easier to see the trend.
![Weekly](https://f.cloud.github.com/assets/1666031/435122/800ae852-afa1-11e2-8bea-465190de2330.png)

**Comment by jdaudier** [comment]
Please ignore the attachment I sent. I updated this mock-up. Just click on the image to see larger version.

**Comment by loicginoux** [comment]
Everything in your mockup seems possible except the graph "Trending" at the end for the reason I explained above.
Would that be ok without the graph?

**Comment by jdaudier** [comment]
Could this help with the charting? https://developers.google.com/chart/

**Comment by loicginoux** [comment]
Unfortunately, It won't work. Here is a longer explanation of why charts in
emails don't work.
http://stackoverflow.com/questions/10862767/email-charts-bar-area-and-pie-charts
The only solution is generating an image of the chart but this is quite
complicated to generate on the server.

**Comment by loicginoux** [comment]
ok

**Comment by jdaudier** [comment]
I updated the mock-up above and here's the version if the user don't have daily calorie goal set.
![Weekly2_no_goal_set](https://f.cloud.github.com/assets/1666031/436955/511f42ce-b080-11e2-89c0-bd1c0b4fe7c3.png)

**Comment by jdaudier** [comment]
Here's the updated version

![Weekly2](https://f.cloud.github.com/assets/1666031/436960/7801aad0-b080-11e2-9795-f4fb31e70623.png)

**Comment by loicginoux** [comment]
And should we still display the leaderboard and slackerboard? I would say no because you receive at the same time the daily email with leaderboard in it. What do you think?

**Comment by loicginoux** [comment]
In the weekly recap intro on top, what would be the sentence if you have the same number of days you met your goal as last week?

**Comment by loicginoux** [comment]
Also, just a correction on your image for trending, You missed "a week ago", so what do you prefer to show between these two tables?
- "3 weeks ago", 2, 1, this week
  or 
- "4 weeks ago", 3, 2, 1, this week

Also, could you give me an mock-up of the weekly email  for the first week of a registered user, i.e when we only have data for this week without anything for the previous weeks?
Thanks

**Comment by loicginoux** [comment]
Sorry another question, do you want different colors if it's more or less than last week, like in the weekly recap  from  LearnStreet. If yes, which colors for "up" and "down"?
Thanks.

**Comment by jdaudier** [comment]
And should we still display the leaderboard and slackerboard? I would say no because you receive at the same time the daily email with leaderboard in it. What do you think?

Joanne: Agreed

**Comment by jdaudier** [comment]
In the weekly recap intro on top, what would be the sentence if you have the same number of days you met your goal as last week?

Joanne: You did as well as last week. Keep up the good work!

**Comment by jdaudier** [comment]
Do we have room to show: "4 weeks ago", 3, 2, 1, this week?  If so, I'd go with this.

And yes, I'll work on mock-up when there are no previous weeks.

**Comment by jdaudier** [comment]
Sorry another question, do you want different colors if it's more or less than last week, like in the weekly recap from LearnStreet. If yes, which colors for "up" and "down"?

Joanne: Maybe we can use orange color as an alert color? 
So "up" = orange
"Down" = green (if green looks really bad, then maybe FoodRubix dark gray)

**Comment by jdaudier** [comment]
Updated:

In the weekly recap intro on top, what would be the sentence if you have the same number of days you met your goal as last week?

Joanne: You did as well as last week. Keep up the good work!

**Comment by loicginoux** [comment]
Concerning the two colors, I quite like the colors from Learnstreet as the blue is the complementary color of orange. I will try with this kind of blue. Let me know when we are testing if you don't like it and I will change it.

**Comment by loicginoux** [comment]
inspired by the mail from conspire, what about putting the top right box like this:

**123** daily calorie limit
**3**   day out of 7 you met your goal this week
**5**   day out of 7 you met your goal last week
Well done... bla bla bla

just putting the numbers first and bold to emphasise on them. I am just saying that because figures seem a bit loss in the text when doing it like you said.
see screenshot http://awesomescreenshot.com/035186vjca

Also another question while you have the screenshot opened, under calories breakdown, is that ok to put "n/a" when I haven't uploaded anything for the day. (and as a consequence, the calculation "up" or "down" is also set as "n/a" )?

**Comment by jdaudier** [comment]
OK to try the blue.

How about trying this:
Daily calorie limit: 1,400
This week, you met your goal: 3 days out of 7
Last week, you met your goal: 4 days out of 7
Well done... blah blah blah

And we can bold everything before the colon like "Daily calorie limit", etc. And we can bold the numbers.

**Comment by jdaudier** [comment]
Instead of N/A, what about leaving it blank so keep it clean?

**Comment by loicginoux** [comment]
Hey, this is what I have got so far for the recap and calories breakdown: http://awesomescreenshot.com/038187epc9
few questions/notes:
1 - is the styling of the table for calories breakdown fine with you? (because before doing quite the same for goal check, I want to be sure that it's fine with you)

2 - to have the same height for the two rectangle under the "weekly recap" I would need to have the sentences "You didn't do as well this week. No worries. Try again next week." either removed or the same length of "you did better this week! good job!" in order that it doesn't get to a new line depending on which sentence is used. This would allow me to have always the same height everytime... Can we change these sentences?

3 - I will make different screenshots for the rectangle with "Daily calorie limit: 1,400" with the different propositions. I still think that figures first is better as it will emphasis on them... let discuss about it when we have the images.

4 - if you have any styling request, let me know... for the table expecially.

**Comment by jdaudier** [comment]
It should say: Calorie Breakdown

I'll review more later

**Comment by jdaudier** [comment]
I will update the mockup based on this change:

Sad face should be at end of  first sentence: "you didn't do as well as last week :(  
Then say, no worries....etc.

**Comment by jdaudier** [comment]
![2013-05-01_1251](https://f.cloud.github.com/assets/1666031/450745/2873f2c2-b29a-11e2-915f-96f680834189.png)

**Comment by jdaudier** [comment]
Shortened: You didn't do as well this week. =(  No worries. Try again.

**Comment by jdaudier** [comment]
Here's that mock-up I owed you.  Will send you the emoticons via email.

![weekly2 first week](https://f.cloud.github.com/assets/1666031/452579/2674ffa0-b2f1-11e2-9f54-719ee4a6b97c.png)

**Comment by loicginoux** [comment]
I will keep the arrow on first line as you see putting it in 2 rows doesn't render that good. It's better to have everything aligned in the center http://awesomescreenshot.com/06318a5j13

**Comment by loicginoux** [comment]
This is the 3 different way to display the top right rectangle, let me know which you prefer:
1 - http://awesomescreenshot.com/05b18al83b
2 - http://awesomescreenshot.com/0ca18al613
3 - http://awesomescreenshot.com/00118al554

I prefer the 3rd one after seeing all of them.

Also this is the whole email screenshot, let me know if you see any issues. I took the liberty to change few things compared to your mock-up; basically I applied the rule, orange = "increasing" and blue = "decreasing"
http://awesomescreenshot.com/02c18amib5

**Comment by jdaudier** [comment]
You're using the wrong text for the box on the right. The text you're using if it's their first week.  You should use this text if they have a previous week:

Better this week: You did better this week. Good job! =)
Worse this week: You didn't do as well this week. =(  Try again.
Same as last week: You did as well as last week. Keep it up!

**Comment by jdaudier** [comment]
Can we add in comma in the numbers?  It's missing in the comparison number in top left box and trending section.

![2013-05-02_0908](https://f.cloud.github.com/assets/1666031/454902/b03e0884-b342-11e2-8a78-2010362a4363.png)

![2013-05-02_0913](https://f.cloud.github.com/assets/1666031/454928/508ff162-b343-11e2-8a67-2f9eb2a106c9.png)

**Comment by jdaudier** [comment]
I agree with you on option 3 for top right box.

**Comment by loicginoux** [comment]
"You're using the wrong text for the box on the right"
Ok I didn't understand correctly.

**Comment by jdaudier** [comment]
Oh and this line should have a smiley face image:
Same as last week: You did as well as last week. Keep it up! =)

**Comment by loicginoux** [comment]
note that I haven't set the "SAMPLE" image when no calories is set up. Im waiting that we have finished with the design and we won't touch it anymore before taking a photo of it that I will use for the sample. If you tell me that the design is fine like that, I will add it.

**Comment by jdaudier** [comment]
I think for the sample, it should be closer to the mock-up where we have a few smiley faces.

**Comment by loicginoux** [comment]
Yes I will make a sample image with every type of data, smileys, etc... and what about the design, can I do it from the current styling?

**Comment by jdaudier** [comment]
Can you make the font larger for this line under "Goal Check"?
:-) = You stayed within your daily calorie limit

**Comment by loicginoux** [comment]
links to "view chart" should now go to the correct view with comparison done with previous period.
I remind you that you can preview directly all emails at:
http://calm-gorge-1213.herokuapp.com/admin/mailer/index

**Comment by jdaudier** [comment]
Can we add commas in these places as well?
![2013-05-09_1044](https://f.cloud.github.com/assets/1666031/484080/38567624-b8d0-11e2-9436-56f9aeb23f48.png)

**Comment by jdaudier** [comment]
Is there a way to toggle the "COMPARE" feature on and off when you press on the button on the site?

**Comment by loicginoux** [comment]
no toggle at the moment, You can just compare. Do you want to be able to
toggle the compare feature?

---

_Loïc Ginoux_
Freelance web engineer

Site: loicginoux.com
Email: lginoux http://lginoux.pro/@gmail.com
Twitter: @loicginoux http://twitter.com/#!/loicginoux

## Tel: +34 638 246 893

**Comment by jdaudier** [comment]
Yes because what if user wants to see the regular view after they've seen the comparison?

**Comment by loicginoux** [comment]
not really a big deal as the data is still showing on the graphic, but ok
no problem I will add it.

---

_Loïc Ginoux_
Freelance web engineer

Site: loicginoux.com
Email: lginoux http://lginoux.pro/@gmail.com
Twitter: @loicginoux http://twitter.com/#!/loicginoux

## Tel: +34 638 246 893

**Comment by jdaudier** [comment]
![2013-05-13_0324](https://f.cloud.github.com/assets/1666031/495149/743450a0-bbb7-11e2-8f96-a29eaa7e0f11.png)

**Comment by jdaudier** [comment]
Do you think we're ready to have the beta testers test out the new daily and weekly emails?

**Comment by loicginoux** [comment]
I already augmented the font size, is that not enough?
Yes we could deploy it. Before that, can you do the test about hte issues we had with the photos 120. Can you create a photo after 10pm and see if it appears on the correct day on the progress bar. I should have fixed that but a real test would be good.

**Comment by jdaudier** [comment]
Sure, I will create a photo after 10pm tonight.

Can you make these 3 changes? This is how it looks in Outlook / Hotmail.

![2013-05-13_0843](https://f.cloud.github.com/assets/1666031/496498/2fb52044-bbe4-11e2-9c9d-ff68d38138e0.png)

![2013-05-13_0844](https://f.cloud.github.com/assets/1666031/496501/34485d2e-bbe4-11e2-8548-c3e6a74ba230.png)

![2013-05-13_0845](https://f.cloud.github.com/assets/1666031/496503/3807f5b4-bbe4-11e2-92d3-6cda860f03f7.png)

**Comment by loicginoux** [comment]
These are hotmail specific issues. They render correctly in Gmail. I will fix that. Except these styling issues, seems that that datas are right, at least for my case.

**Comment by loicginoux** [comment]
Are you ok with the changes I made for Hotmail?
