### ISSUE TITLE
Sign up box alignment off

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#313]
Can you see this beta tester's video?
https://betapunch.viewscreencasts.com/9d918100ea7a4733ab01227baea1ba23

The box seems off in Chrome.
![2013-04-09_1042](https://f.cloud.github.com/assets/1666031/358315/46c2722a-a13e-11e2-94e1-53bdbd009442.png)

**Comment by loicginoux** [comment]
It seem that it appeared when she clicked the select box above. I have never seen that before!!! 
I can't replicate this in my Chrome. Can you?

**Comment by loicginoux** [comment]
After looking at it twice, I think this is due to on of her browser add ons, as you can see when she hover over the textarea there is a small green circle in the textarea. My guess is that this is causing the issue.

**Comment by jdaudier** [comment]
OK - I didn't notice this in Chrome so will close this.
