### ISSUE TITLE
Daily calorie counter not working

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#314]
Please watch this beta tester use our app: https://betapunch.viewscreencasts.com/9d918100ea7a4733ab01227baea1ba23

And can we add this text so people don't think the counter will automatically enter the calories into the text box.
![2013-04-09_1054](https://f.cloud.github.com/assets/1666031/358403/f5e7bc2c-a140-11e2-998b-35208cd8861d.png)

**Comment by jdaudier** [comment]
I would prefer to have it on the page. Can we try this inline code and see if the bug will disappear?
https://gist.github.com/jdaudier/5372396

**Comment by loicginoux** [comment]
I will have a look and see what I can do.

**Comment by jdaudier** [comment]
ok

**Comment by loicginoux** [comment]
Have you noticed that the wolfram box doesn't work? it says "computing" for ever.
Also, your last script didn't display anything? is it in a collapse mode or something?

**Comment by loicginoux** [comment]
I haven't done anything on that as the widget is not working, should I remove it?

**Comment by jdaudier** [comment]
Can you look into the code here and see if you get it working?  We are using the orange color one.

http://www.wolframalpha.com/widgets/gallery/view.jsp?id=3f0b9e714dc05b05aad90cae08d25e3b

**Comment by loicginoux** [comment]
Sorry I didn't mean to close it, I will check with this new one

**Comment by loicginoux** [comment]
None of the different option they have work. Either there is always this grey area with "computing" or when submitting the form, the result doesn't show. Should we just make a link to the wolfram page as we do for the upload box?

**Comment by jdaudier** [comment]
How about this? "(help me calculate)" is a link.
![2013-04-15_0734](https://f.cloud.github.com/assets/1666031/381135/b61b0f2a-a5d9-11e2-80b5-6990cc35181e.png)

**Comment by loicginoux** [comment]
ok
