### ISSUE TITLE
Photo upload not recognized with large photos

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#315]
Can only upload photos under 2mb?

Reported by: Nishant
Date: 4/10/2013 2:35:39 PM  
Internet browser: Chrome 26.0.1410
Operating system: Windows 7

**Comment by loicginoux** [comment]
This is working with files under 3MB, I just tried it. Can he forward his photo?

**Comment by jdaudier** [comment]
Just emailed you the photo.

He said:
Uploads don't show up if I'm using a large photo either way (sending from phone or using computer). Once I reduced the size the uploads were visible in my diary.

**Comment by loicginoux** [comment]
Let's discuss here and not by email.
As I said on email, the photo you forwarded is over 3Mb, should we put the limit at 4Mb?
I will also add an error message when size limit is reached.

**Comment by jdaudier** [comment]
Yes, let's try 4MB as limit with an error popup when it's the user uploaded something over that amount.

**Comment by loicginoux** [comment]
Uploading is already in a popup and it's not possible to display another one on top. I will just display the erro message under the photo like I do for other errors (no calories entered for example)

**Comment by jdaudier** [comment]
Right - that's what I meant

**Comment by loicginoux** [comment]
limit is now 4Mb with error message when uploading both by email and in app.

**Comment by jdaudier** [comment]
What does the email message say?  I can help review the copy.
