### ISSUE TITLE
Size limit

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#317]
Can we add in this text?
![size](https://f.cloud.github.com/assets/1666031/368987/e4890c72-a2cd-11e2-9d8b-05ad33441d17.png)

**Comment by jdaudier** [comment]
Can we add this but change it to 4MB?

**Comment by loicginoux** [comment]
Ok but I will only display the message after a attempt to send a photo over 4Mb.
Do you also want me to send an email when this error appear from an upload made by mail?

**Comment by jdaudier** [comment]
Yes - we can make it not as a text below the box but as a warning that pops up after they upload a large photo.

I think it would be nice if we can tell them via email if the photo they sent is too large.

**Comment by jdaudier** [comment]
If we do the email, can I review the text?

**Comment by loicginoux** [comment]
Ok this is the email:
subject: [FoodRubix] Please upload photo under 4 Mb
body:
Hi there,
We are sorry, but the email you just sent to upload a photo did not go through.
Please upload a photo under 4Mb.

**Comment by jdaudier** [comment]
How about this?

subject: [FoodRubix] Please re-send a photo under 4 MB
body:

Hi there,

We are sorry, but the file size of the photo you just sent was too large. 

Please re-send a photo that's less than 4 MB.

**Comment by loicginoux** [comment]
done
