### ISSUE TITLE
closing Tip box

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#319]
when first log in, a tip box appears.
I will make it close on first click on the screen, wherever it is on the box or outside.

**Comment by jdaudier** [comment]
I think we should have a X or CLOSE button so that we are sure they read it before closing it.

**Comment by loicginoux** [comment]
ok

**Comment by loicginoux** [comment]
here it is:
http://awesomescreenshot.com/031164eqc7

**Comment by jdaudier** [comment]
Can "Settings menu" be orange?  And can we add a line of space above the last sentence?

**Comment by loicginoux** [comment]
this is done with the list and the empty space before last sentence.
