### ISSUE TITLE
Time added to new upload

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#32]
Can we have an option to change the time during the new upload?  The time can be set to the current time but user can change if they're uploading an older photo.

**Comment by loicginoux** [comment]
Better: I will change the current "new upload" page by the same form as the "edit" box, with image on the side, and date and time prefiltered.
Also, instead of having it on a new page, I will keep it in a popup box like the edit form.
do we agree on that?

**Comment by jdaudier** [comment]
sounds good

**Comment by loicginoux** [comment]
done and deployed in heroku. to be tested.

**Comment by jdaudier** [comment]
I submitted 2 bug entries about this:
1) Submit button is way on the right
2) First time you click upload, the time is not current time

**Comment by loicginoux** [comment]
ok thx

**Comment by loicginoux** [comment]
I close this one as this is working and deployed.
