### ISSUE TITLE
wolfram box in setting page makes it unresponsive

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#320]
I am watching the video of the tester. At about 8min, she goes to settings page and clicking on the different menu doesn't respond. This is due to the Wolfram calories counter in the daily calories limit that takes time to load and make the page unresponsive.
Wouldn't it be better to have a link that open either a popup box a go to the wolfram site. This would avoid the few seconds of waiting.  
What do you think?

**Comment by jdaudier** [comment]
Let's discuss on https://github.com/loicginoux/joanne_project/issues/314
