### ISSUE TITLE
Uploading photos from phone results in wrong timestamp

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#322]
My (UK) time: 11:08am 
Timestamp: 3:08am 

Maybe the time difference between your server and my location is not reflected?

Reported by: Nishant
Date: 4/12/2013 12:10:46 PM

**Comment by loicginoux** [comment]
I can't find the photo we are talking about, Can he tell me which one it was? (or some more information about it, calories, description, etc..)

**Comment by jdaudier** [comment]
Nishant said:
If you see the one I uploaded today, Monday, at 9:03, shown as 1:03am

**Comment by loicginoux** [comment]
ok thanks.
Note for me: id = 4904, 15 april

**Comment by loicginoux** [comment]
In the example of this photo 4904 sent by mail, the header of the email says that it was sent at 1:03am PST.
I check for different users and the date on the email header was correct for all of them.
This must be a problem with the email server from sky.com as his email address is from there "nmittal@sky.com".
He should try changing his email address to another provider and see if sending photos email results in the wrong timestamp.
