### ISSUE TITLE
New GA Tracking Code

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#323]
Can you replace our GA code with this new one? https://gist.github.com/jdaudier/4f18a0b8d58bbea5b554

You can delete the old codes. More info here:
http://blog.kissmetrics.com/universal-analytics

**Comment by loicginoux** [comment]
this should be live

**Comment by jdaudier** [comment]
So old code is removed, right?  I will close that in GA as well.

**Comment by loicginoux** [comment]
ok
