### ISSUE TITLE
FB signup

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#325]
Can you check whether there is something wrong with our FB signup process?

This beta tester couldn't sign up using his email and then tried FB but it would take him to the same screen each time.

https://betapunch.viewscreencasts.com/02035508c6164cd6a8c95c3f1bf67d08

**Comment by loicginoux** [comment]
I'll write my comments while watching the video:
- first when he tries to login for the first time, he is not using his username but his email address. So the app says that user doesn't exist.
- second problem, the lost password page doesn't find the user. This is actually a bug where he tries with his email with capital letters "Myemail@gmail.com" but the user is registered with "myemail@gmail.com". I correct that now. This is a quick fix.
- I agree about the video on the homepage that doesn't bring any information about the app.

I will test now why his Facebook registering didn't work.

**Comment by loicginoux** [comment]
The Facebook registering process works only if you allow the app to publish on your wall. If you disallow it as he did, you come back to the register page with no message to help you understand what's going on. How do you think we should we handle this case?

**Comment by jdaudier** [comment]
Can we make it so they can log in with FB without publishing?

And then we can add FB connect for sharing under settings > social sharing?

**Comment by jdaudier** [comment]
Should we remove the video on the homepage for now, and figure out what to put there, if anything, later?  Thoughts?

**Comment by loicginoux** [comment]
About the video, just as a test this is how it would look like without the video http://awesomescreenshot.com/0bd15x4e7f
I am not sure what is best, but to be fair, a good design made by a pro designer would make the homepage a lot more attractive.
I am looking into the Fb registration.

**Comment by loicginoux** [comment]
Ok I found the bug about Fb. I was caching the register page so when you come back to the register page after registering with FB, you see the same exact page.

**Comment by loicginoux** [comment]
I will also allow people to log in using their email and not their username.

**Comment by jdaudier** [comment]
Can you try these changes?  I like the fact the users don't have to scroll much to read.
![2013-04-15_0729](https://f.cloud.github.com/assets/1666031/381097/27fcc1e8-a5d9-11e2-811c-cf880904a44d.png)

**Comment by loicginoux** [comment]
Should I remove the orange banner entirely then or only the icons? If I remove just the icons, would it not look weird an empty banner in the middle?
the floating is nothing, appeared when doing the snapshot.

**Comment by jdaudier** [comment]
Can I see how it looks just with icons removed?  The ribbon is a nice touch I think.

**Comment by loicginoux** [comment]
I added the possibility to login using your email, this is in testing.
This is how it would look: http://awesomescreenshot.com/032164oue8

**Comment by jdaudier** [comment]
Looks good to me. You?

**Comment by loicginoux** [comment]
Ok, it's not too bad, but I think the banner is a bit big and that makes an empty space, should I do it but with a smaller banner?

**Comment by loicginoux** [comment]
I'll close this issue and open a new one for the homepage

**Comment by loicginoux** [comment]
I think the problem from Facebook should be gone now.

**Comment by jdaudier** [comment]
So now users can sign up and choose not to share via FB and have an account created, correct?

**Comment by loicginoux** [comment]
They don't need to allow the app to publish on their  wall to registered and never needed to. That was a bug that appeared after I put the caching system in the app.
