### ISSUE TITLE
See user goals in admin panel

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#329]
Is there a way to view user goals in admin panel?

**Comment by loicginoux** [comment]
I will add it

**Comment by loicginoux** [comment]
sorry, it's already there, not in the index page but if you view a user details, you will see his goal

**Comment by jdaudier** [comment]
I viewed the user details but couldn't find this info.

**Comment by loicginoux** [comment]
Is that not this one?
http://awesomescreenshot.com/03a16kkk53

**Comment by jdaudier** [comment]
Could we add it as a column to the main user table?

**Comment by loicginoux** [comment]
ok

**Comment by loicginoux** [comment]
done locally, will be push later

**Comment by jdaudier** [comment]
Could the column for the goal be wider so that each row is less tall?

**Comment by loicginoux** [comment]
this is wider now. I close this if it's all right with you.

**Comment by jdaudier** [comment]
Can we double the length?  Right now it's still a little narrow to me.
![2013-05-22_0907](https://f.cloud.github.com/assets/1666031/549451/c1dd12b2-c2f9-11e2-9a37-ef0d139593da.png)

**Comment by loicginoux** [comment]
ok
