### ISSUE TITLE
add name and/or description to a photo

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#33]
I think a text added to a photo is necessary for several reasons:
- you can remember what the photo is, what you actually ate that day, "a delicious orange juice with croissant and jam" (btw the best breakfast ever ;) )
- when there is a notification for a comment or a yum, it will be easier if we have a name for the photo.
- when we share on facebook as well, it will be good to add a name.

when uploading, do you think it should be required to add a description? if it's not required and a photo doesn't have name, how should we name it when notifying? something like "photo of Jul 29, taken at 1:30 pm"?

Your thought on this?

**Comment by jdaudier** [comment]
I feel like this can be added in a future sprint but not this one.  I think we should keep it easy for people to track what they eat.  Maybe this can be added after we have some users testing the site.  We can ask if they want this feature.

If someone comments or yums a photo, I think you should get an email that says, personX yummed/commented on one of your photos.  And then there's a link where you can click the link and get to the large popup of your photo with yums and comments.  Thoughts?

**Comment by loicginoux** [comment]
fine with me

**Comment by loicginoux** [comment]
I think it wil be good to add that now for sprint 5

**Comment by loicginoux** [comment]
this is done and deployed. you can test and close the issue if there is no bug

**Comment by jdaudier** [comment]
Do you think we should have it one less click where the description text box already shows up without having to click "+Add a description"?

**Comment by loicginoux** [comment]
I like it this way because it shows that it's optional... but we could make it differently

**Comment by jdaudier** [comment]
So everything else is required except this right?  Maybe we can write it as "Description (optional)"

**Comment by loicginoux** [comment]
If you tell me that you prefer your way, I can change it. just let me know

**Comment by jdaudier** [comment]
OK - i think i prefer having it already with a text box with this text: Description (optional)

**Comment by loicginoux** [comment]
ok

**Comment by loicginoux** [comment]
pushed

**Comment by loicginoux** [comment]
I close this one, reopen if anything wrong.
