### ISSUE TITLE
Picture upload bug (Anjali)

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#330]
Anjali reported:

the picture wouldn't move over to the right day. 
e.g. the french fry pic on sunday should be on saturday. 
i tried twice and then gave up. 
saturday should have two more pics. i uploaded via my phone on sunday and 
then tried to move them by "editing" the date. in the process they were 
deleted. i did not try uploading/moving them again. too much of a time sink.

**Comment by loicginoux** [comment]
Is that a reproducible bug? Is she still experiencing this? If yes can she tells with which photo this is happening again? It will help me finding the bug in logs.

**Comment by jdaudier** [comment]
So far she hasn't experienced this again, so I'm closing it.
