### ISSUE TITLE
Description bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#332]
Signatures should not be showing up such as "Sent from my iPhone"

Is there a way to remove all signatures that are currently showing?

**Comment by loicginoux** [comment]
The description is taken from the body of the email. There is no way to separate the automatic signature from the rest of the body as they are all part of the body. I can't see a pattern to remove the description.
see the different email body I copy/pasted from the logs, you will see that there is no definite rule to remove the signature:
- with custom signature :

```
"stripped-text"=>"..says iPhone"
```
- with iphone signature: 

```
"stripped-text"=>"Sent from my iPhone"
```
- with yahoo signature: 

```
"stripped-text"=>"Sent from Yahoo! Mail on Android"
```
- some user put the signature correctly:

```
"stripped-text"=>"\"Chili\"", "stripped-signature"=>"Sent from my iPhone"
```
- with no body at all:

```
"stripped-text"=>""
```

I don't know why sometimes the signature is correctly added to the field signature and sometimes directly in the body. I could remove everything after "Sent from..." but custo signature will pass through.

**Comment by jdaudier** [comment]
This bug only started after the latest push. Did you change something because we told the users to put description in quotes "   ".  This way the signature should not be showing up.

**Comment by jdaudier** [comment]
Is there a way to remove all signatures that are currently showing, so that it looks cleaners in the Feed?

**Comment by loicginoux** [comment]
ah right, I forgot about these two brackets. I will correct the bug and remove the signature from the last photos, I will just do it by editing the photos in the admin panel.

**Comment by loicginoux** [comment]
This has been fixed now. I close it
