### ISSUE TITLE
Points not calculating correctly

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#339]
Points are not calculating correctly - says I had 81 points yesterday in email.

![daily-stats](https://f.cloud.github.com/assets/1666031/513053/db6cc4ec-be36-11e2-8056-fb02f46cbd00.png)

**Comment by jdaudier** [comment]
Is the streak only 1 day since the feature just launched so the highest it can be is 1?

**Comment by loicginoux** [comment]
the point issue is because I updated the point system yesterday, I transfered all monthly points to yesterday.
See the new page http://www.foodrubix.com/admin/points for more details about points.
For streaks, it's the same, it started with 0 and everyday at midnight it adds +1 if you uploaded during the day. Because the streak was initialised with 0, highest score is 1.

**Comment by jdaudier** [comment]
Will the daily points calculate correctly starting tomorrow then?

**Comment by loicginoux** [comment]
I updated it, I think it's fine, I leave that open and will close it after few days if you didn't notice anything since.

**Comment by loicginoux** [comment]
is that ok now? can we close it?

**Comment by jdaudier** [comment]
I got 10 points yesterday.  Do you know how?

**Comment by loicginoux** [comment]
you can see all the details on the admin page:
http://www.foodrubix.com/admin/points?commit=Filter&order=attribution_date_desc&q%5Baction_eq%5D=&q%5Battribution_date_gte%5D=&q%5Battribution_date_lte%5D=&q%5Buser_id_eq%5D=12&utf8=%E2%9C%93

Let me know if there is something wrong.

**Comment by jdaudier** [comment]
Somehow I have pts from the 19th (today) that got added as yesterday?
![2013-05-19_1304](https://f.cloud.github.com/assets/1666031/523506/64834a46-c0bf-11e2-878e-ae4cc20f2508.png)

**Comment by loicginoux** [comment]
Where did they got added? in the email you mean?

**Comment by jdaudier** [comment]
It's in the email under "Yesterday" and "Best" box for 5/19.

**Comment by jdaudier** [comment]
![2013-05-20_0808](https://f.cloud.github.com/assets/1666031/536765/3c93360e-c15f-11e2-8e87-bd5748db95d1.png)

**Comment by loicginoux** [comment]
This bug is appearing because the date for the points use the the date in UTC timezone. I will update that.

**Comment by loicginoux** [comment]
I made some changes. Let me know if you see this bug again.

**Comment by jdaudier** [comment]
Are we sure about how points are calculated now?  Meaning, I shouldn't get 10 pts. like that time.

**Comment by loicginoux** [comment]
I think this can be closed. Please reopen if you have another strange points behaviour.
