### ISSUE TITLE
Weekly email msg check

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#340]
Can you confirm all the messages for the right box? Right how it says I'm doing better when it's the same. We should be using the message for same.

![2013-05-16_0744](https://f.cloud.github.com/assets/1666031/513082/4719b3da-be37-11e2-9b53-74d2ba07035a.png)

**Comment by jdaudier** [comment]
Better this week: You did better this week. Good job! =)
Worse this week: You didn't do as well this week. =( Try again.
Same as last week: You did as well as last week. Keep it up!

**Comment by jdaudier** [comment]
Is there a way for me to see the sample weekly emails when user don't have their calorie goal set?

**Comment by loicginoux** [comment]
set your calorie limit to 0 in admin user edit page and go to:
http://www.foodrubix.com/admin/mailer/preview_weekly

I just realised that text is off in the top right box.

**Comment by jdaudier** [comment]
Did that and it looked the same - didn't see sample

**Comment by loicginoux** [comment]
I updated your calorie limit to 0 on the admin panel. check the link again. It might not have work because of the bug where you can't update your calorie limit...

**Comment by loicginoux** [comment]
I think this can be close now. I corrected this bug.
