### ISSUE TITLE
Right align sentence and add top margin

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#341]
Can we right align this sentence and add a line of space above it?
![2013-05-16_0801](https://f.cloud.github.com/assets/1666031/513222/8ec84c3a-be39-11e2-97ef-465bca7faaa4.png)

**Comment by loicginoux** [comment]
I think we can close this one.

**Comment by jdaudier** [comment]
Can you show me a screenshot?

**Comment by loicginoux** [comment]
http://awesomescreenshot.com/01d1bz7h8c
