### ISSUE TITLE
Daily calorie counter not working

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#342]
Does this work for you now? If not, we should remove it.
![2013-05-16_0821](https://f.cloud.github.com/assets/1666031/513369/5df2a10c-be3c-11e2-9e47-459809f0e9cc.png)

**Comment by loicginoux** [comment]
There is a bug in there code since I update Jquery's version and some functions have been deprecated. Until they update their code, this is useless in our site. A link to the widget in their site will still work though. I'll remove it for now.

**Comment by jdaudier** [comment]
OK, let's add a link to their site (open new window).  So we can't get it to work on our site using the embed code, correct?

**Comment by loicginoux** [comment]
No I will add a link to open it in a new window because, it doesn't work in our site.

**Comment by loicginoux** [comment]
This is done now. Close this if you are ok with it.
