### ISSUE TITLE
Wrong page after updating daily calorie goal

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#343]
After I update daily calorie goal, the page jumps to this one

![2013-05-16_0822](https://f.cloud.github.com/assets/1666031/513381/8c527a90-be3c-11e2-95f6-c6d07c82b070.png)

**Comment by loicginoux** [comment]
You would like to go to the panel "daily calorie goal" correct? It has always worked like it is now but I can change it.

**Comment by jdaudier** [comment]
Ok that will be ideal. Thanks!

**Comment by loicginoux** [comment]
This is implemented now.
