### ISSUE TITLE
Weekly email with no calorie goal set

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#344]
Box border is off and font is off.
![2013-05-17_2108](https://f.cloud.github.com/assets/1666031/521127/f16be080-bf70-11e2-8f73-af0d5ee6c4d5.png)

![2013-05-17_2109](https://f.cloud.github.com/assets/1666031/521128/fb183bc4-bf70-11e2-9371-0b5a1aa1da19.png)

**Comment by jdaudier** [comment]
I think "Did you know?" should be bigger and bolder font.
And then next line: If you go under Settings...

**Comment by jdaudier** [comment]
When you click on Settings, can we actually link to the calorie goal setting tab?

**Comment by jdaudier** [comment]
Can we fix these bugs before the weekly stat emails goes out this Sunday?

**Comment by jdaudier** [comment]
![2013-05-18_1445](https://f.cloud.github.com/assets/1666031/522195/8d737720-c004-11e2-8cc1-76e2c032f832.png)

**Comment by loicginoux** [comment]
I will push this email to the prod, is that ok?
http://awesomescreenshot.com/00d1ahxnd1
link goes to the daily calorie limit tab as well.

**Comment by jdaudier** [comment]
Can you make "Did you know?" a tad larger font?

![2013-05-19_1156](https://f.cloud.github.com/assets/1666031/523424/f94a8478-c0b5-11e2-85d4-3139209b926e.png)

**Comment by loicginoux** [comment]
Can we close this one?
