### ISSUE TITLE
Sample daily & weekly email link

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#346]
Can we add a "(sample)" and link it to:

https://dl.dropboxusercontent.com/u/125982/FoodRubix-Images/New-Features/Stats/Weekly-Email-Sample.png

![2013-05-21_0000](https://f.cloud.github.com/assets/1666031/540236/415e7aec-c1e4-11e2-981e-703d9fe7f317.png)

**Comment by jdaudier** [comment]
OLD: 
Daily emails?

NEW: 
Daily emails? (sample)

Link "sample" to:
https://dl.dropboxusercontent.com/u/125982/FoodRubix-Images/New-Features/Stats/Daily-Email-Sample.png

**Comment by loicginoux** [comment]
This is implemented but There is a small styling issue that appeared in the production site where the text "sample" goes on the line underneath. I will correct that and close the issue.

**Comment by jdaudier** [comment]
OK I'm good with "sample" being on the same line for both daily and weekly lines
