### ISSUE TITLE
Email recap text update under Settings

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#347]
OLD:
(Recommended because you'll become more aware of how many calories you ate for the day and it's the easiest way to see if you've won a Smart Choice or Hot Photo Award)

NEW: (I removed the parenthesis too)

Highly recommended because you'll become more aware of how many calories you ate for the day, and it's the easiest way to see if you've won a Smart Choice or Hot Photo Award. Plus, you'll get detailed reporting with weekly comparison and trends!

**Comment by loicginoux** [comment]
done!

**Comment by jdaudier** [comment]
Can you move "(sample)" for Daily Emails to the next line so both are consistent?

**Comment by loicginoux** [comment]
see #346

**Comment by jdaudier** [comment]
Ignore last comment since you'll make them all on the same line
