### ISSUE TITLE
Text edit for FB sharing

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#35]
Can we make a minor text edit when you share an image to FB?

OLD: What do you think about my latest meal?

NEW: This is what I've been eating. What have you been eating?‏

**Comment by loicginoux** [comment]
done. this is in testing. close the issue when you are happy with it.

**Comment by jdaudier** [comment]
The "Settings" feature has a broken link for me so I couldn't change my sharing feature.

**Comment by loicginoux** [comment]
what link is broken? when you click on settings on the top right? where does it go to? which url?

**Comment by jdaudier** [comment]
Yes top right.  It goes to a page that says: We're sorry, but something went wrong.

**Comment by loicginoux** [comment]
should be fixed now, it is because I pushed the code while adding the picture tab to the settings (this tab is not working yet). At least you should be able to change your other settings
