### ISSUE TITLE
Photo upload not working

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#350]
I tried to upload this photo just now (3.4 MB), and it's not working.  

![20130523_130108](https://f.cloud.github.com/assets/1666031/559144/b6706a3e-c441-11e2-92e0-4b9765373ec1.jpg)

**Comment by loicginoux** [comment]
It's not a bug, the limit is 3Mb. You should have had an error message or a mail back to tel you it's too big, maybe this is not working?!

**Comment by jdaudier** [comment]
Didn't get the error message.   Can we make the limit 4 MB?

**Comment by loicginoux** [comment]
Ok

**Comment by jdaudier** [comment]
Can you check on the error message too?

**Comment by loicginoux** [comment]
Ok this is changed to 4Mb and error message is correct.
