### ISSUE TITLE
Faster loading Intercom javascript

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#355]
We now serve the Intercom javascript from a CDN. This means faster load times for your users, no matter where in the world they live.

To take advantage, change your script tag from using https://api.intercom.io/api/js/library.js to https://static.intercomcdn.com/intercom.v1.js

If you're using our intercom-rails gem, then the latest version will do this for you.

**Comment by loicginoux** [comment]
ok done
