### ISSUE TITLE
Profile photo won't update

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#357]
Anjali reported 3 Jun, 10:22am:
I tried to update my profile picture, but the program wouldn't update it.

**Comment by jdaudier** [comment]
She is using Chrome.

**Comment by loicginoux** [comment]
could you send me the picture she tried to upload? 
Thank you.

**Comment by jdaudier** [comment]
Here it is: https://static.intercomcdn.com/attachments/51714-7cd8f2ad2474f9c3a43dab7d1f5f866662c292e7-Anjali_Gupta.JPG?1370375730

**Comment by loicginoux** [comment]
it should be working now. It was an issue with Cloudfront.
