### ISSUE TITLE
Upload photo stretched

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#37]
When you upload a photo, it looks all stretched in the preview thumbnail

http://screencast.com/t/HupfKstS9Jg2

**Comment by loicginoux** [comment]
I noticed that before as well. For this one, I am afraid I won't be able to do anything, I can explain why:
when it appears on the grid view, the image we are rendering has been processed by the media processor, it has cropped the image and centered it. When previewing the image before uploading, we are just reading the image data from the computer of the user and rendering it in a box of 200px*200px. The image is just rendered as it is. The image is not processed neither cropped before and this can't be done easily.
I don't think this is vital for now, this would involve quite some research, time and money. I would concentrate on features more important (That's my opinion, but if you want it, I can try to fix it)

**Comment by jdaudier** [comment]
Would it be an easier fix if we put the proportions of the preview image closer to what the typical images being uploaded would be?  For instance, maybe like 334 x 200 px?  That seems to be the proportion of the images taken by my phone.

**Comment by loicginoux** [comment]
yes this would be the easy fix, but are all phones taking the same picture size?

**Comment by jdaudier** [comment]
Is there a way to keep the height at 200 and just have the width be proportionally sized down?

**Comment by loicginoux** [comment]
to fit in the popup box, I would do the contrary, keep a width at 200 fixed and have a variable height.

**Comment by jdaudier** [comment]
I agree with having a width of 200 fixed and variable height.

**Comment by loicginoux** [comment]
this is in testing in heroku now. close this issue if you are happy with it.
