### ISSUE TITLE
Default time bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#38]
When I uploaded the first photo today, the time was not matching the current time.  The other photos I uploaded after this one worked.

http://screencast.com/t/X4ZcGXRsqgF

**Comment by jdaudier** [comment]
Oh yea, meant to ask you is it typical to be charged for fixing bugs?

**Comment by loicginoux** [comment]
Yes, I am sorry, this is part of the developement time to fix bugs found in the development process. This is impossible to have a project with no bugs.
more links on the questions to check other opinions:
[link 1](http://programmers.stackexchange.com/questions/153620/should-i-pay-my-developers-for-bugs-fixes-for-a-project-or-work-thats-still-in)
[link 2](http://programmers.stackexchange.com/questions/33526/who-should-pay-for-fixes-bugs)
[link 3](http://stackoverflow.com/questions/426319/should-you-charge-a-customer-for-bug-fixes)

**Comment by jdaudier** [comment]
ok makes sense.  I was just wondering.

**Comment by loicginoux** [comment]
So are you still having this timezone bug or is it working now?

**Comment by jdaudier** [comment]
Still not working for the first image I try to upload.  It seems to set the time 7 hours ahead.

**Comment by loicginoux** [comment]
ok I will check

**Comment by jdaudier** [comment]
When do I the first upload, the time is still set 7 hours ahead (this was at 8/11 @ 9:45 pm)
http://screencast.com/t/AJdTBaJE

**Comment by loicginoux** [comment]
yes, I didn't look into that yet. I am gonna do it now

**Comment by loicginoux** [comment]
Sorry I try to understand where is the problem coming from as I can't replicate this issue.
what do you mean by only the first photo has this bug? is it that:
- you upload the first photo ---> time is wrong
- you upload the second photo ---> time is ok?

so is the time ok for the second photo?
is the time correct when you edit a photo? I mean by correct if it's the time you set when you created the photo.

**Comment by loicginoux** [comment]
ok I think I fixed it. Can you try it. I also committed the ongoing work for sprint 4. You can now see people, follow them, see their dashboard and upload a new profile picture
