### ISSUE TITLE
Date & time dropdown menus not working

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#40]
I'm trying to upload a photo and changing the date to yesterday, and the dropdown menus for the date and time are not working

http://screencast.com/t/H3Wry1khs

**Comment by loicginoux** [comment]
Ok, locally it's working, I can't commit the new code now because I am in the middle of the development of the new page but as soon as I can, I will commit to fix the bugs.

**Comment by loicginoux** [comment]
I deployed it. let me know if it's still not working for you.

**Comment by jdaudier** [comment]
I noticed the bug is still there for the first time I try to upload an image and adjust the day and time at that moment.  Both day and time dropdown menus are not showing up.  It works if I post the image first and then click update to adjust, just not the first time before posting.

http://screencast.com/t/3S9L8lbf
