### ISSUE TITLE
Update photo bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#41]
When I tried to update a photo, I wasn't sure if you wanted it to look like this: http://content.screencast.com/users/joannedaudier/folders/Jing/media/6826deee-1d09-4818-82f2-309fe82ba08d/2012-08-11_2236.png

**Comment by loicginoux** [comment]
no I didn't want to make it like that :)
can you let me know your firefox version please, I will install it and check on this one.
what you can try as wel is clearing the cache of your firefox (that must be in the browser settings). that will update the css file (for styling)

**Comment by jdaudier** [comment]
I have the latest Firefox v14.0.1.

**Comment by loicginoux** [comment]
I can't replicate this in firefox 14... can you try clearing your browser cache and let me know if it's still there.

**Comment by jdaudier** [comment]
It looks like this still: http://screencast.com/t/1DMHSbaLtv1

**Comment by loicginoux** [comment]
same response as for #49. 
I can't replicate, we will try that during skype call and screen sharing.
thanks
