### ISSUE TITLE
Can't log in via FB

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#42]
Tried to log in via FB after I did the alias change and got this error: http://www.diigo.com/item/image/2yj1s/ri3n

**Comment by loicginoux** [comment]
yes ok, I know what's the issue,
i'll fix that

**Comment by loicginoux** [comment]
ok this is fixed. For future problem with facebook, I had to log in to the facebook apps page and change the url of the app foodrubix.
