### ISSUE TITLE
Image details popup

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#48]
Question:

http://screencast.com/t/AeoLpmheR

http://screencast.com/t/pNrrrdK0nE

**Comment by loicginoux** [comment]
first one: almost the same, except for the comments, I removed the scrollbar on the full view page. I also put a bigger image for the full view page.
I agree with the like button behaviour. the only small thing that I see about that is that if I implement it only the comment icon will be clickable to open the popup box, compared to now where the whole image is clickable.... (or maybe I leave the whole image clickable and only change the behaviour when clicking the like icon? what do you think?)

**Comment by jdaudier** [comment]
first one: Can the popup image also have bigger image and no scrollbar to match full view page (similar to FB image comments page)?

2nd one: ideally it'd be nice to be able to LIKE directly from the thumbnails and then clicking the comment will link to the image details popup

**Comment by loicginoux** [comment]
first one: 
The popup box has been made to display less information. it has a fixed width and fixed height. 
If you prefer I can change it to how Facebook does it. I mean big image (the same as on the full view page) on the left side with information and comments on the right side, this right side will be scrollable if there is too many comments. the width will be bigger as well.

**Comment by loicginoux** [comment]
and I agree for the second one, clicking on the heart, likes the photo, but I still think that the whole image should be clickable to open the popup, only the comment icon is a too small area for that much information to display. I will do it this way and we will see how it feels.

**Comment by jdaudier** [comment]
I like your idea of making the popup box similar to FB.  Do you think that wi'll look better?

I agree that whole image should be clickable to open popup.  Makes me wonder if we should CONSOLIDATE it this way:

1) Click on heart to LIKE
2) Click on image to open popup to see comments and likes but ALSO edit the data point at the same time if the photo belongs to you (similar to how FB does it: http://screencast.com/t/eVuifMpYI)

**Comment by loicginoux** [comment]
at the moment I changed it to this locally http://awesomescreenshot.com/0b0f1usf5

**Comment by loicginoux** [comment]
I like the idea of having the edit action on the same popup, make things clearer. 
Ok so from the screenshot I attached previously, if you are the owner you have a 3rd button "edit" that will change the read-only information (calories and date) to the input we have on the edit page and it will add a button "change photo" on top of the image as well.
when you are editing, you can then save or cancel to pass back to the read only mode.
does it sound good?
do you want me to finish the comments and likes properly first or do you prefer me to do the mailgun feature first?

**Comment by jdaudier** [comment]
Sounds good - maybe do the comments and likes first if it won't take too much time

**Comment by loicginoux** [comment]
Hey,
I changed the way to display and edit a photo, are you ok with this way of doing it?

**Comment by jdaudier** [comment]
looks good
