### ISSUE TITLE
Add daily calorie goal line to week and month view

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#54]
Should be in a different color: http://screencast.com/t/5JoWlxP0F

Add pop-up:
TIP! Visit the Settings menu on the top right corner to set up your daily calorie goal and enable Facebook sharing. Do it now before you forget!"

**Comment by jdaudier** [comment]
Did you mean to have it like this if no calories were entered? http://screencast.com/t/L51ruF7PQ

**Comment by jdaudier** [comment]
Minor text update: http://screencast.com/t/nyAIefXxs

**Comment by jdaudier** [comment]
Top of the graph seems cut off: http://screencast.com/t/FOqZ61lcROf

**Comment by loicginoux** [comment]
hey, 
- top of graph should be fine
- text change is done
- the one with no calories entered, I couldn't replicate it...

**Comment by jdaudier** [comment]
To replicate this: http://screencast.com/t/L51ruF7PQ

Perhaps try having one photo the day before and no photo for today.  Log in and have the calorie goal set to zero.
