### ISSUE TITLE
Adding spacing around images for week view

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#55]
Maybe add CSS?

**Comment by jdaudier** [comment]
can we work on this next?  maybe this week?

**Comment by loicginoux** [comment]
yes ok

**Comment by loicginoux** [comment]
do you like it like that?
week view: http://awesomescreenshot.com/06fjvrk4c
month view: http://awesomescreenshot.com/0b0jvrp4c
day view: http://awesomescreenshot.com/0aajvrr24
much better I think.
