### ISSUE TITLE
FB login logo

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#56]
When you log in using FB, there's a square that shows up when you allow the app to connect.  We should use our logo there.  Do I need to resize it?  It seems to be 75x75 px.  Is that right?

**Comment by loicginoux** [comment]
which logo do you want to use here? if we use the one "foodrubiX" the logo will be 75*21... do you just want to use the logo for the X of foodrubix? that will be more square.
what do you think?

**Comment by loicginoux** [comment]
this is when you first login using facebook:
http://awesomescreenshot.com/0aajxtwbb

**Comment by jdaudier** [comment]
Nice!  Will it say FoodRubix without the "dev" part?

**Comment by loicginoux** [comment]
yes
