### ISSUE TITLE
Basic front end design integration

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#57]
Joanne to design very basic front end design so that Loic can add it to the homepage for beta testers

**Comment by loicginoux** [comment]
Have you got something on this? I don'think this wil be possible for the end of the week

**Comment by jdaudier** [comment]
I will add photo collage to the bottom of the homepage like this so we can pull random photos from users: http://themecurve.com/Site/themes/Flybird/Dark/index.html

**Comment by jdaudier** [comment]
I finally finished a temporary homepage.  Sorry it's very simple since I just started coding HTML/CSS.  Can you integrate it to the site tomorrow?  Note that I have my own CSS in there for that page.  https://github.com/jdaudier/html_template

**Comment by jdaudier** [comment]
Here are 2 screenshots of how it should look: 

https://www.evernote.com/shard/s23/sh/09181ced-cc7b-40ec-8205-dd757f69dfb9/130124a8800e2272cb7271da5a19c2c4

https://www.evernote.com/shard/s23/sh/71f3d098-0148-4978-9026-dd566c92d4b9/487c8fd2e7eeaa34e89375150a79416b

**Comment by jdaudier** [comment]
I just pushed up another version to GitHub just now

**Comment by jdaudier** [comment]
I pushed to GitHub - updated YouTube embed code.  Can you please update?  https://github.com/jdaudier/html_template

**Comment by loicginoux** [comment]
I hope I have updated everything there were to update. The only change I have seen was the <iframe> line.
So I just change this.
were there something else?

**Comment by jdaudier** [comment]
i updated the HTML/CSS homepage code
now we have images for each step and i converted the mailgun email into an image to prevent spam
Can you update: https://github.com/jdaudier/html_template

**Comment by jdaudier** [comment]
I also converted to HTML5 and updated the 2 orange buttons just now. And added a chat box.  You'll have to remove my email on this page's footer too (and any applicable pages): http://www.foodrubix.com/login

**Comment by jdaudier** [comment]
Just updated logo to say BETA and updated 2 orange buttons

**Comment by jdaudier** [comment]
Please use this updated FoodRubix logo - it has the BETA tag: https://www.dropbox.com/s/u5v7lxdttaomlq7/foodrubix-logo.svg

Don't need to update the logo for the email - just the web site is fine.

**Comment by jdaudier** [comment]
Made log in button gray and added drop shadow (kinda like www.mint.com)

**Comment by loicginoux** [comment]
ok updated

**Comment by jdaudier** [comment]
some things are off... 
1) top 2 buttons missing the CSS code that makes them lighter (and text stays white when you hover).
2) chat box missing
3) CSS missing for the text in the steps
4) FoodRubix log should move left a tad to aline with container below

**Comment by loicginoux** [comment]
about the chat box, I cloned your repository and didn;t see it in your page... are you sure you added it?

**Comment by jdaudier** [comment]
Are you using the latest index.html file from me?  It's in the head section

**Comment by jdaudier** [comment]
I also updated all the tags to html5 in the latest html file

**Comment by jdaudier** [comment]
Sorry can you update the CSS again?  I noticed a difference when it's live so I made the boxes for the steps shorter and moved up the image for step 3 up a tad by 2px.

https://github.com/jdaudier/html_template/commit/5700ab272f4cb607eadac5d6e9854ec4ee7c7e79

**Comment by jdaudier** [comment]
The FoodRubix logo with BETA looks off.  The font I used for the BETA text looks different.  Any idea why?

**Comment by jdaudier** [comment]
I updated the logo to fix the BETA font issue: please use this new logo: https://www.dropbox.com/s/u5v7lxdttaomlq7/foodrubix-logo.svg

I also did a push to GitHub with the updated logo: https://github.com/jdaudier/html_template

Did you get a chance to add the JS code for the chat box?

**Comment by loicginoux** [comment]
ok I updated the homepage with new logo, css changes, chat box, html5 tags and 2 buttons css. Let me know if it's ok?

**Comment by loicginoux** [comment]
are we good on this one? can it be closed?

**Comment by jdaudier** [comment]
I think you still need to push with the 3 new step image, CSS, html changes from last night?

**Comment by loicginoux** [comment]
yes sorry I thought I did that. I just pushed it now
