### ISSUE TITLE
Daily and weekly emails

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#63]
As a user, I can choose to receive daily and weekly emails with photo recaps of what i ate

Purpose: To keep FoodRubix on user's top of mind

**Comment by loicginoux** [comment]
I will need the content of the email

**Comment by jdaudier** [comment]
Daily email (sent really late at night - past midnight)

Subject: This is what you ate today

Same as day view on site (photo + calories?)

**Comment by jdaudier** [comment]
Weekly email (sent really late Sun night)

Subject: This is what you ate this week

Same as weekly view (photos + calories?)

**Comment by loicginoux** [comment]
what if there is no photo for the day or the week? should I send the email?

**Comment by jdaudier** [comment]
I think we should, but there can be a funny image and text so it becomes a reminder for them - something like...

Image of an empty plate

You must be STARVING since we haven't seen any photos of your meals!

TIP! If you forget to take a photo, try these awesome workarounds:
1) Google an image of what you ate and upload that.
2) Write down or draw what you ate on a peace of paper, and take a photo of that.
3) Have you eaten this meal before? Use the previous photo.

**Comment by loicginoux** [comment]
for daily emails, what time of the day should I send it? (my opinion 10pm)
for weekly emails, what day and time  should I send it? (my opinion saturday 4pm)

**Comment by loicginoux** [comment]
displaying the graphic in the mail is not possible, only images will be displayed, I will print for each image number of comments and likes, date and time. Styling will also be different from the one on the site, this is because of email clients not allowing every css rules that a browser use.

**Comment by loicginoux** [comment]
Ignore my qestion  about time for sending email, I didn't see it on your previous answer. 
- daily: midnight
- weekly: sunday midnight

**Comment by loicginoux** [comment]
few notes on this one that need your opinion:
- personally I think that a daily reminder is too much and not needed, weekly or monthly would be better...
- for daily email this is not too much of a problem, but for weekly email, you can have a lot of images do you want to display all of them in the mail or have a link to show more?

this is how the daily email look like at the moment:
http://awesomescreenshot.com/04fkpjz1c

I will use the same template for weekly but grouped by day

**Comment by loicginoux** [comment]
more thoughts:
- sending daily emails risks to be expensive if there are lot of people joining the site. I mean that mailgun must have a limit of emails to send freely per month (and heroku as well in terms of time for process to run)
- I need to set up a time for sending emails. you told me midnight but which midnight did you mean? midnight in California? or midnight UTC? I guess it doesn't matter that much and decided midnight UTC, let me know if you want to change that.

**Comment by jdaudier** [comment]
Midnight in CA

**Comment by jdaudier** [comment]
For the weekly email, perhaps we can make the images smaller?  Let's go with both daily and weekly for the 12 beta testers and we can always turn it off later if they don't find it useful.

**Comment by jdaudier** [comment]
Hi Loic: How close are we on this?  Maybe I can start the testing next Monday if this is ready by then?

**Comment by loicginoux** [comment]
this is deployed (you can see your preferences in "settings")
I just need to change the mail when there is no photo for the day/week.

**Comment by jdaudier** [comment]
Can we have it turned on by default?

**Comment by loicginoux** [comment]
it is weekly by default

**Comment by jdaudier** [comment]
Can we turn on the daily as well by default?

**Comment by loicginoux** [comment]
I didn't implement it to have both... for me it was one or the other, but if you want it differently I will change it

**Comment by jdaudier** [comment]
I think it'd be great to have both on by default and they can turn it off it they want.

**Comment by loicginoux** [comment]
ok

**Comment by loicginoux** [comment]
ok this should be done now

**Comment by jdaudier** [comment]
does this mean starting tomorrow I will get daily and weekly emails with photos automatically?

**Comment by loicginoux** [comment]
yes, can you just checked in your settings that I set correctly the default
to both checked checkbox?
I created another account on heroku with your outlook email account. you
should have received a confirmation email.
I will use that to transfer the site and create a test instance as well.

**Comment by jdaudier** [comment]
Yes, both are checked.  I will let you know if I start getting the emails tomorrow.
And I got Heroku email and set up an account.

Date: Sat, 3 Nov 2012 02:54:28 -0700

**Comment by jdaudier** [comment]
Yes, both are checked.  I will let you know if I start getting the emails tomorrow.

And I got Heroku email and set up an account.

**Comment by loicginoux** [comment]
for next sprint I will start configuring the new heroku account.
I will need your details to log in to heroku.
we can talk about it later

**Comment by jdaudier** [comment]
pwd: foodrubix1223

**Comment by jdaudier** [comment]
I haven't received any daily emails yet even though it's checked under Settings.

**Comment by loicginoux** [comment]
me neither... I will debug that today

**Comment by jdaudier** [comment]
Just got daily email.  

Manage your preferences goes to a broken link though

**Comment by jdaudier** [comment]
Text update:

OLD:  
You are receiving this because you registered to FoodRubix.com. Any questions? please email us at jdaudier@outlook.com

NEW:

**Comment by jdaudier** [comment]
Right now I'm getting these at 11pm PST, can we push it out by 1 more hour to 12 am PST (midnight)?

**Comment by jdaudier** [comment]
Do you think we should say: This is what you ate yesterday? instead of today?

**Comment by loicginoux** [comment]
Ok sorry for late response, I was travelling for the last 2 days, I am updating now all these small changes and let you know when it's done

**Comment by loicginoux** [comment]
I agree with "yesterday" instead of today, I change it

**Comment by loicginoux** [comment]
one question: where do you want the link to go to? at the moment it goes to the settings page, and you need to uncheck manually the email checkbox if you don't want to receive the daily and weekly emails.
what do you think about adding this:
- a link in the email to "unsubscribe to emails" that will completely turn off all emails (likes, comments, recaps...)
- the email page has more checkbox to also unsubscribe to comments, likes...

because at the moment there is no way to not receive emails from comments and likes.
and apparently legally you need in emails a link to unsubscribe (see http://www.dotmailer.co.uk/articles/email_marketing_mistakes_to_avoid_making.aspx)

the rest of the work should be done, I will check tonight to see if emails is now correctly set up.

**Comment by jdaudier** [comment]
Right now I'm getting these at 11pm PST, can we push it out by 3 more hours to 2 am PST?

**Comment by loicginoux** [comment]
ok, that will be ok for next one

**Comment by jdaudier** [comment]
Regarding your questions above, I think we should take them to the Settings page.  Could they unsubscribe from all emails from the Settings page as well?  Meaning, we'll just link to the Settings page and they can decide all their communications from there.  This way we prevent them from unsubscribing from all by mistake.  Thoughts?

**Comment by loicginoux** [comment]
ok, good with me, so should we add the possibility to unsubscribe to other kind of emails?

**Comment by jdaudier** [comment]
Another thought.  We can do this...http://screencast.com/t/GACrQhwrw

Get recap: Daily · Weekly · Never

**Comment by jdaudier** [comment]
And maybe on the Settings page, they an unsubscribe to other kind of emails.

**Comment by loicginoux** [comment]
if you want for now we can just leave the unsubscribe from other email. we will implement it if needed.
for your previous suggestion, do yo want "Get recap: Daily · Weekly · Never"  in the setting page?

**Comment by loicginoux** [comment]
it's ok now, no? except the settings page that I need to change. The email came ok for me.

**Comment by jdaudier** [comment]
Typo I had for the empty email.

OLD: 2) Write down or draw what you ate on a peace of paper, and take a photo of that.

NEW: 2) Write down or draw what you ate on a piece of paper, and take a photo of that.

OLD: TIP! If you forget to take a photo, try these awesome workarounds:

NEW: TIP! If you forget to take a photo, try these easy workarounds:

**Comment by jdaudier** [comment]
Can we add this image to the empty email: http://farm8.staticflickr.com/7057/6892866040_ae888c61ce_d.jpg

Here's a mock-up: https://dl.dropbox.com/u/125982/FR.jpg

**Comment by loicginoux** [comment]
Hey,
ok so I think I finished these:
- update for text in empty email + add image
- links should redirect you to your edit page, logged in or not

if you want to try without waiting the daily email, just comment/like  one of your photo and let me know

**Comment by jdaudier** [comment]
Can you send the weekly recap on Sundays at 2am PST?  I think right now it's sending them on Saturdays.

**Comment by loicginoux** [comment]
it's set up for 10:00 am UTC so it should be at right time (-8 hours for your time)

**Comment by jdaudier** [comment]
I tried again to manage preferences from the email while logged out.  It takes me to log in page and then throws me to the diary page, not settings.  Can we have it go to settings page?

**Comment by loicginoux** [comment]
that's weird... this works for me. I will do more tests.

**Comment by jdaudier** [comment]
Just got the weekly email today (Sat) @ 2am.  Can you push out back by 24 hours so users will get it on Sunday in the US?  Thanks!

**Comment by loicginoux** [comment]
can you forward me your mail sent by foodrubix with which you can't go to the settings page?

**Comment by jdaudier** [comment]
Sorry - I meant to say to change the time 24 hours later to Monday @ 2 a.m., not Sunday.

**Comment by jdaudier** [comment]
Just forwarded you an email sent by foodrubix which doesn't go to settings page.

**Comment by jdaudier** [comment]
Weekly email:
Can we change the date from... 
Wed 14 Nov 2012

to

Wed Nov 14, 2012

(day after the month and added a comma)

**Comment by loicginoux** [comment]
ok I hcanged it and put it on Monday. I just need to check why you cannot acces the link when logged out

**Comment by loicginoux** [comment]
it should be fine now. you can close it if it's working for you.
