### ISSUE TITLE
create testing instance

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#64]
I thought the process of testing the app should be improved.
the problem we have now is that sometimes when I deploy in Heroku in the live instance, there are still bugs and this can make the live app not working at all.some bugs are inherent to the deployement or Heroku and can't be tested before the actual deployment in Heroku.
So what I thought would be good is that we have 3 instances:
the dev instance: the one I am working on, this is my local instance
the test one: when work is finished locally, I upload it to the test instance, hosted in heroku. you and I can test it here without impacting live site.
the live instance: when work is tested and functional in test instance, we can deploy in live instance.

This should reduce the possibility of important bugs in the live instance.

how does that sound? it's a better process no?
should we plan that for sprint 6 or later?

**Comment by jdaudier** [comment]
sure, we can plan for sprint 6 if timing works for you

**Comment by loicginoux** [comment]
moving to sprint 7

**Comment by loicginoux** [comment]
sorry back to 6, I will put the live instance in a heroku account at your name and with your details, the test account will go under my account.
doing this,  these are the consequences:
- the live app will be the only one to run in your account, contrary to my account where i have several sites running. I hope this should speed up a bit the site.
- when creating your heroku account, you will be asked to enter your CB details. In case we overpass the free limit, you will be charged by heroku. (note that it hasn't happen to my account yet, even with everything running on it.) This could start being the case if you want the site to use more process/memory (so being faster) or if we start having more users ()which is linked to memory/speed.
- I will then need the details to access your account and being able to upload the code to the live instance.

**Comment by jdaudier** [comment]
I have a Heroku account.  Do you need my login?

**Comment by loicginoux** [comment]
Yes please send them by email please

**Comment by jdaudier** [comment]
sent

**Comment by loicginoux** [comment]
Hi Joanne,
we now have a staging instance at this address:
http://calm-gorge-1213.herokuapp.com/
This is deployed on heroku and all the config is as close as the live site configuration as it can be.
Every new features will now be first tested and approved in this environment before deploying to the live site. This should avoid to have lot of bugs when deploying new features to the live site.
Note that the database is different from the live site, so for logging in you will have to create a new account on this instance.
Also now, all github issues labeled as "in testing" will be deployed in this instance. There will then be ready to push to live site when you are happy with it in testing instance.

**Comment by jdaudier** [comment]
I get this bug when I try to sign up with FB?
{
   "error": {
      "message": "Invalid redirect_uri: Given URL is not allowed by the Application configuration.",
      "type": "OAuthException",
      "code": 191
   }
}

**Comment by loicginoux** [comment]
I need to create another facebook app to work in this environment. For now use the normal login system

**Comment by loicginoux** [comment]
facebook works on this app too. I consider this task as finished
