### ISSUE TITLE
protect model attributes

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#69]
add attr_protected to models to avoid malicious use

**Comment by jdaudier** [comment]
Is there anything else we need to secure down before giving the 12 beta testers access?

**Comment by loicginoux** [comment]
this is not a major issue and you need to be an expert but this need to be done for later

**Comment by loicginoux** [comment]
for the beta tester, we don't need lot of security. what we should plan later is to make a backup of the database every X days. this will ensure to not loose the data for users if something get wrong.
