### ISSUE TITLE
change Amazon s3 account

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#70]
this is currently at my name, At the moment there isn't any fee because we don't have a lot of images but when more people will use it, they may charge us something, I would prefer the account to be at your name rather than making at mine and making transfer, etc... is that ok with you?

**Comment by jdaudier** [comment]
sure - how do we do the switch?

**Comment by loicginoux** [comment]
it's not that urgent, I will do that when I will habe a bit of time

**Comment by jdaudier** [comment]
Have you heard of this? Would this be cheaper for me once we have more users? https://nimbus.io/

**Comment by loicginoux** [comment]
I don't think so, S3 is really cheap and the best on the market... I wouldn't advise you to change for anything else.
This is the pricing of S3 http://aws.amazon.com/s3/pricing/

**Comment by jdaudier** [comment]
How about this one? https://www.digitalocean.com/price-comparison-chart

**Comment by loicginoux** [comment]
looks good but with this one you don't have anything for free, also this is more to host your entire app rather than assets like S3. After a bit of research there is not yet any descent alternative to S3. Also this is the most documented, reliable and fast provider, It would be an error to change to something else.
this is my invoice from them at the moment:
http://awesomescreenshot.com/0edtddhc7

it means at the moment it costs 0$

**Comment by jdaudier** [comment]
OK. Let me know when you've switched over?

Is the charge because we went over the free limit in storage?

**Comment by loicginoux** [comment]
I moved all files today and tried to switch over but had a problem of permissions and couldn't read the assets, so I switched back to my S3 account. tomorrow when you guys are sleeping I will transfer the newly created assets from today and try again.
S3 is not free but the fees are so small that you need a lot of data to start paying something.
What you see on the screenshot is that:
- storage is free for the amount of assets we add per month (under 1Gb of files/month is free)
- the cost of 0.02$ and 0.01$ are for the requests to access the files and edit or create the images.

I think there is a minimum for them to start charging as charging 0.03$ is not worth it. I am not sure what is this limit though

**Comment by loicginoux** [comment]
this has been updated now

**Comment by jdaudier** [comment]
so now it's under my Amazon S3 account?  Can I change my Amazon password back to old one or do you still need access?

**Comment by loicginoux** [comment]
I shouldn't need access anymore, Thanks.
