### ISSUE TITLE
check performances of server before more people join

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#71]
At the moment we use a free server on Heroku. this is nice but not fitted for real condition. you can note that it is already quite slow (in my opinion). this is due to server and might think about either upgrading the heroku account or see another solution (because Heroku are quite expensive)

**Comment by jdaudier** [comment]
ok what are our options?

**Comment by loicginoux** [comment]
If you want, after sprint 5 has passed. I will have a look at different options and prices and let you know.

**Comment by jdaudier** [comment]
any idea why it takes so long to load the www.foodrubix.com page?  Is it the redirect or Heroku?

**Comment by loicginoux** [comment]
no, can't see anything on new relic, and it's loading ok for me

**Comment by jdaudier** [comment]
http://www.zbugs.com/
zBugs will take all the JS and CSS files on your server and compress them using Minify and GZip methods. Simply enter your website’s URL, download the compressed files and update them on the server. Done!

Read about this here: http://web.appstorm.net/roundups/web-development/10-tiny-yet-useful-web-apps-for-web-developers/

**Comment by jdaudier** [comment]
More references: 
http://webdevchecklist.com/
http://mir.aculo.us/dom-monster/

**Comment by loicginoux** [comment]
FYI, js and css files are already compressed and joined in one file to avoid lot of http requests. the web dev checklist is quite good.

**Comment by jdaudier** [comment]
One more reference: http://csswizardry.com/2013/01/front-end-performance-for-web-designers-and-front-end-developers/

**Comment by loicginoux** [comment]
ok, although reading it quickly, it seems lot of it is done but I will check everything. 
another think I forgot is database indexes: http://tomafro.net/2009/08/using-indexes-in-rails-index-your-associations

**Comment by jdaudier** [comment]
another reference: http://designmodo.com/optimizing-website-speed

**Comment by loicginoux** [comment]
another: http://csswizardry.com/2013/01/front-end-performance-for-web-designers-and-front-end-developers/?utm_source=html5weekly&utm_medium=email

**Comment by jdaudier** [comment]
A few more:
https://speakerdeck.com/chriscoyier/lets-do-a-bunch-of-simple-stuff-to-make-websites-faster

http://www.stormconsultancy.co.uk/blog/development/6-ways-to-get-more-bang-for-your-heroku-buck-while-making-your-rails-site-super-snappy/?utm_source=rubyweekly&utm_medium=email

The issues in github could be titled as:
- using cloudfront and asset_synch for asset storage
- externalizing uploading and processing files from the heroku dyno
- add background jobs for sending emails, etc...
- offload complex searches (this one is not needed for us)
- add caching with Memcache
- use Unicorn for concurrent connections

**Comment by jdaudier** [comment]
Sometimes I would try to go to the site and it takes almost 30 sec before the page loads (3:38am)

**Comment by loicginoux** [comment]
I noticed that as well and the problem is the following:
in the heroku plan we have at the moment, the process running the server is not always up, this is part of the free plan If I remember, so we don't have a process running 24h/24h. When someone request a page and the site hasn't been loaded for quite some time, it starts the server before getting the page back to the user. Sometimes I see errors coming saying that the server hasn't started correctly, so it restarts the server and this  takes some time.
I don't know the cause of this "Boot timeout error" yet. I would need to investigate, this is part of my work for the performance improvment. I will check at this point what's going on.

**Comment by loicginoux** [comment]
Hi,
just an update on this one: I have been working on that recently and this is the work that is deployed at the moment on testing instance:
- I transfered all javascript/css/images to Amazon S3 so that requests to them don't pass by Heroku.
- all files hosted on S3 are now accessed via Cloudfront, this is a Content Delivery Network that distributes files in edge servers. This servers are all around the world so that when you access the file, it gets it to the closests server possible.
  see http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/images/Paying.gif  
- I also started caching in rails using "memcache"

**Comment by loicginoux** [comment]
Also note that cloudfront is like S3 and start having a price when you start having some traffic.
http://aws.amazon.com/cloudfront/pricing/

**Comment by jdaudier** [comment]
Got it

**Comment by loicginoux** [comment]
Ok It worked great locally but since I tried putting it on the staging site, I had problem integrating all changes to the heroku environment. As this is taking now quite a lot of time, I will leave this for now. At the moment, only caching is working on heroku. background workers and the process to upload quicker doesn' work in Heroku.
I will come back to that when I will have a bit more time. I will work on other issues for now.

**Comment by jdaudier** [comment]
Sounds good... as long as we have some time to test it before the 2 editors start on Apr 1

**Comment by jdaudier** [comment]
http://browserdiet.com/

**Comment by loicginoux** [comment]
known techniques that remain to be done to make things faster. Note that these techniques might not be available or feasible in our environment.
- Gzip compression or at least html compression 
- image optimisation
- use of background worker for image uploading and processing.

The rest of the techniques from your link are already used in our app.

**Comment by loicginoux** [comment]
So I think I finished on this one, I optimised and compress all images. I am also now serving gzip compressed files for css and js.
Do you feel that the site is quicker?
a next thing that could be done is "use of background worker for image uploading and processing." I won't do that for now but will create an issue for the future just to not forget.
Doing this will decrease the time to wait when uploading a photo.
I won't do that for several reasons:
- the effect is seen only if you upload from the browser and people mostly upload from mailgun
- It will use a background worker and this will cost money
- I already tried and get stucked, so I stopped because I didn't want to spend too much time on it.

I will create different issues for the performance enhancement I didn't implement and I can think of. This can be done at a later point.

**Comment by jdaudier** [comment]
Another article with tips in case any applies to us: http://blog.teamtreehouse.com/speeding-up-page-load-times

**Comment by jdaudier** [comment]
Interesting read when you have time: http://csswizardry.com/2013/01/front-end-performance-for-web-designers-and-front-end-developers/

**Comment by loicginoux** [comment]
Ok thanks. I think I already made all of the tips in these links.
Do you think it's still slow?

**Comment by jdaudier** [comment]
Seems ok to me... was just sharing the knowledge in case there was anything new.
