### ISSUE TITLE
backup plan

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#72]
this is for later but need to think about it.
we will need to make recurrent backup of data every X days ( 2 weeks? 4?)

**Comment by loicginoux** [comment]
A backup of the database is now done every day automatically and are kept for a week.

**Comment by jdaudier** [comment]
By kept for a week, are you saying that we store rolling 7 day back ups?

**Comment by loicginoux** [comment]
yes the last 7 backups are stored. So In case of a problem with datas, we can reload the database with data from a week ago. Normally keeping the backup from last day is enough.
Usually I also do a manual backup before doing any upgrade a bit big, to be sure to have a fresh backup in case of a problem.
