### ISSUE TITLE
"feed" page

### ISSUE THREAD

**Issue by loicginoux** [loicginoux/joanne_project#73]
I think we should implement a "feed" page. This will show, like the main page of facebook or twitter, the latest photos of your friends. this will help to get the application more social.
I think that following what your friends exactely eat is quite hard at the moment, you would need to go to the diary of each of your friends one by one... this is not the best user experience in my opinion.
a feed page (or wall or news) also makes people more addicted to the app, this is the only way to know the latest meal eaten by their friends.

**Comment by jdaudier** [comment]
ok maybe sprint 7

**Comment by loicginoux** [comment]
similar to #128

**Comment by jdaudier** [comment]
Close since it's a repeat of https://github.com/loicginoux/joanne_project/issues/128
