### ISSUE TITLE
Intercom tracking code

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#74]
Can you please add this code to our web app?  It's for Intercom.io to track users and send them emails.

I will send the code via email.

**Comment by loicginoux** [comment]
this will work in the live site only, so you won;t be polluted by my development site.
if you want to add custom data in future to use a custom filters, let me know.

**Comment by loicginoux** [comment]
this is deployed now

**Comment by jdaudier** [comment]
thanks

**Comment by jdaudier** [comment]
what is considered custom data?

**Comment by loicginoux** [comment]
you can find it on intercom.io https://www.intercom.io/apps/oxkhdxqk/custom_data
