### ISSUE TITLE
Couldn't change email

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#76]
I tried to change my email address but it would not take

Also, username field has an up/down arrow for entering numbers.  Is that a mistake?

**Comment by loicginoux** [comment]
I don;t know how it appeared but this will be fixed on next push.

**Comment by jdaudier** [comment]
ok - and let me know if you find out why I couldn't update email

**Comment by loicginoux** [comment]
it's because of the bug for the username field that blocks everything during validation of the form datas

**Comment by loicginoux** [comment]
looks like it's working now, I am closing it.
