### ISSUE TITLE
SendHub and Twilio investigation

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#78]
- add phone number to sign in page
- add to the settings page a way to turn on/off sms 
- actually send sms every days to the people that requested it
- option to choose the time when they want to receive the text

**Comment by loicginoux** [comment]
# 

This is more  a note for me. this is technically what need to be done:
- add to user model:
  - [string] phone_number
  - [boolean] receive_sms
  - [string] receive_sms_hour (this hour need to be kept in database in UTC time)
- create cron job "send_sms" to run every hour
- create rake task "send_sms". this will be run every hour, each hour it will find the users that have the "receive_sms_hour" set to the current time and send them the sms reminder
- add part "sms reminder" to the settings page
- add phone number to settings page (profile tab)

add in register page the field for phone number.

# 

Joanne, running a rake task every hour can make heroku pass the limit of free usage (see http://stackoverflow.com/questions/10956540/do-heroku-scheduler-tasks-cost-money). this is just for your information.

Then I will need the text of the sms.

estimation: 
between 7 and 10 hours. (sendhub looks good, I just hope that I can send sms worldwide and not just in US, for testing on myself that will be easier)

**Comment by jdaudier** [comment]
Will we have to run a rake task every hour?  What does that do?

**Comment by loicginoux** [comment]
a rake task is used to run automatic code (in this case sending a sms to a group of users). Added to a scheduler system, it allows us to run a piece of code at certain interval of time. If users can choose the hour they want to receive an sms, we need to schedule the tasks to send sms every hour.

**Comment by jdaudier** [comment]
What if we only made it available in the morning time?  Would save save rake run?

**Comment by loicginoux** [comment]
yes the only problem are the different timezones of users. sending sms once in a day means that while you receive it in the morning, I will receive it in the afternoon.

**Comment by jdaudier** [comment]
Is there any other way to lower the rake run?  Maybe we give users only 4 time choices to send sms?

**Comment by loicginoux** [comment]
wither we can try every 2 hours and see if we go past the free limit or we forget about the sms idea for now (this could come later if the app makes money)

**Comment by jdaudier** [comment]
how about every 4 hours?

**Comment by loicginoux** [comment]
ok if you prefer

**Comment by loicginoux** [comment]
I just installed new relics (http://newrelic.com/) for monitoring the use of heroku ressources. that will be easier to track everything about the app on heroku (the use of our free ressources for example)

**Comment by jdaudier** [comment]
cool

**Comment by loicginoux** [comment]
I close this one, I will use sendhub and in settings you will be able to choose between 6 different times in the day to receive the sms (every 4 hours)

**Comment by jdaudier** [comment]
Should we close this when it's actually implemented or add the implementation as new issue?

**Comment by loicginoux** [comment]
this was investigation only, the actual implemtation issue is #81

**Comment by jdaudier** [comment]
ok - closed it is
