### ISSUE TITLE
Logo is behaving weird

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#83]
It's stretched out when I first load the page and then goes to normal size - maybe conflict in CSS?

http://screencast.com/t/V2gzk6e89LM

**Comment by jdaudier** [comment]
Logo seems stretched out here too: http://screencast.com/t/qs3zy53Rb1aQ

**Comment by loicginoux** [comment]
it should be fine now.

**Comment by jdaudier** [comment]
do you know what was wrong before?  just curious.

**Comment by jdaudier** [comment]
Following and Team Rubix pages are broken.  Maybe it's because you're updating?

Error msg: We're sorry, but something went wrong.

**Comment by loicginoux** [comment]
I was applying a css rule to the img but apparently it didn't like it. I just removed it and rearange the css to appear like in your template

**Comment by loicginoux** [comment]
ithese pages are working now, no? It was probably during deployement of the new code.

**Comment by jdaudier** [comment]
Still down but maybe it'll fix itself in a few min
