### ISSUE TITLE
Add note to sign up page

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#87]
IMPORTANT! If you're planning to send in photos using your phone, please create an account using the SAME email address.

Bold: "important" and "same"

As long as user can see whether they sign up by creating a new account or FB

**Comment by loicginoux** [comment]
this is after registering with facebook:
http://awesomescreenshot.com/042n4gee7
and this when filling the register form and focusing in the email field
http://awesomescreenshot.com/0afn4gzf9

**Comment by jdaudier** [comment]
Can "important" and "same" be the same font size but just bold?

**Comment by jdaudier** [comment]
I don't see this change yet - is it because you have to push?

**Comment by loicginoux** [comment]
Sorry I don't understand...
- go to http://www.foodrubix.com/register
- focus on Email field (i.e. click on the field)
  ===> message appears underneath the field

OR with facebook 
- go to http://www.foodrubix.com/register
- connect through fb
  ====> you are redirected to register page to add your password and you can see the message

do you not have that?

**Comment by jdaudier** [comment]
I'm using Chrome and don't see the text when I click on email field.

Can we make "important" and "same" be the same font size as the rest of the text but just bold?

**Comment by loicginoux** [comment]
Ok This was due to offerchat making the app not working. I sent you an email to exaplin a bit more about it. the change will be pushed shortly.

**Comment by loicginoux** [comment]
This should be now working, can we close it?

**Comment by jdaudier** [comment]
Can we make the 2 minor changes?  This will apply to the FB login text too.

http://screencast.com/t/OFVQCbt1KGx

**Comment by loicginoux** [comment]
This is done. The chatbox style is also fixed. close it if you are happy with it

**Comment by jdaudier** [comment]
looks great!
