### ISSUE TITLE
Sign up bug

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#89]
My friend Ethan tried to sign up and ran into a bug.  He said he didn't get confirmation email either.

Error msg:  something went wrong
[11/21/12 3:10:19 AM] Chiahao Li: then it told me my email has been used

**Comment by loicginoux** [comment]
Just to let you know, the confirmation email is sent only when using the form. When using facebook the email doesn;t need to be confirmed as this is directly the one from facebook.

**Comment by jdaudier** [comment]
gotcha... so the fact he showed up on the users list means he probably used FB to log in?  He got a broken page though.

**Comment by loicginoux** [comment]
Hi joanne,
there were the verifying account email which had a bug and wasn't sent.

**Comment by loicginoux** [comment]
this is fixed now
