### ISSUE TITLE
Black bar to pages

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#93]
Would it be hard to add the black bar on the homepage to all the inside pages as well underneath the charts?  The only difference I would suggest is to have it go all the way across instead of just 960pix.  Thoughts?

http://screencast.com/t/MvG6XWxGvqTE

**Comment by loicginoux** [comment]
I added it.

**Comment by jdaudier** [comment]
For the FOLLOWING page, is it possible to have the bar show up at the bottom if you only have a few followers?  
http://screencast.com/t/4qcD9jsV

**Comment by loicginoux** [comment]
done

**Comment by jdaudier** [comment]
The bar is messing up the DIARY pages though... for those pages, it should show up at the bottom, right?  When there are more users added to FOLLOWING and TEAM RUBIX, will the bar continue to show up only at the bottom?

**Comment by loicginoux** [comment]
it should be better now.

**Comment by jdaudier** [comment]
What do you think we should do when there are no photos in DAY view?  Should we have the bar at the bottom too like the FOLLOWING and TEAM RUBIX pages?  http://screencast.com/t/eBgM6AhAtqm

**Comment by jdaudier** [comment]
When there are more users added to FOLLOWING and TEAM RUBIX, will the bar continue to show up only at the bottom?

**Comment by loicginoux** [comment]
Ok I found the solution. here is the demo:
http://www.cssreset.com/demos/layouts/how-to-keep-footer-at-bottom-of-page-with-css/

and you can see it in action directly on the site. basically, if the content is too small it sticks to the bottom of the page and if the content of the site is higher than the creen it pushes the footer to the bottom

**Comment by jdaudier** [comment]
awesome!
