### ISSUE TITLE
Following pages

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#96]
I just realized that when you go under FOLLOWING and look at other user's diary, you can't easily tell whose diary it is and that you're no longer in your own diary.  Thoughts on how we should make that more obvious?

**Comment by loicginoux** [comment]
We could easily add the name on the page but the question is how to integrate it nicely...

**Comment by jdaudier** [comment]
I wonder if it would be weird if "GO JOANNE" on the top right changes to "GO LOIC" when I'm looking at your diary.

**Comment by loicginoux** [comment]
something like JOANNE'S DIARY and I would remove the dropdown to access settings when I am on your page, no?

**Comment by jdaudier** [comment]
Right that works

**Comment by loicginoux** [comment]
Ok I just implemented that as this was a quick win. will be deployed soon

**Comment by jdaudier** [comment]
nice!
