### ISSUE TITLE
Login error (IMPORTANT)

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#97]
Beta tester Sydney says: I signed up, confirmed via the new email, and when i try to login, it tells me "we're sorry, but something went wrong"

**Comment by loicginoux** [comment]
close if this is fixed

**Comment by jdaudier** [comment]
Grace had issues loggin in via FB: I tried logging in with FB today, but when I submit the permissions, I got the "something went wrong" page.

**Comment by loicginoux** [comment]
looking at it now

**Comment by loicginoux** [comment]
I Joanne, I couldn't replicate the issue but from what I saw on the logs, I think i fixed the issue that we had. I also added the facebook picture automatically when registering.
